import { FileRule } from '../types';

export const apiRules: FileRule[] = [
  {
    id: 'API_001',
    title: 'Swagger/OpenAPI publicamente acessível',
    category: 'API',
    severity: 'low',
    description: 'Documentação Swagger exposta publicamente em produção.',
    impact: 'Facilita reconhecimento e descoberta de endpoints internos por atacantes.',
    remediation: 'Proteja a documentação com autenticação em produção ou desabilite em produção.',
    safeExample: "if (process.env.NODE_ENV !== 'production') {\n  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));\n}",
    reference: 'OWASP API9:2023 - Improper Inventory Management',
    patterns: [
      /swagger-ui|swaggerUi|swagger\.json/i,
      /\/api-docs|\/swagger/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_002',
    title: 'GraphQL Introspection habilitada em produção',
    category: 'API',
    severity: 'medium',
    description: 'GraphQL com introspection habilitada permite descoberta do schema completo.',
    impact: 'Atacantes podem mapear toda a API GraphQL, incluindo types, fields e resolvers internos.',
    remediation: 'Desabilite introspection em produção.',
    safeExample: "const server = new ApolloServer({\n  introspection: process.env.NODE_ENV !== 'production'\n});",
    reference: 'OWASP API9:2023 - Improper Inventory Management',
    patterns: [
      /introspection\s*:\s*true/i,
      /new\s+ApolloServer\s*\(/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_003',
    title: 'Endpoint de debug exposto',
    category: 'API',
    severity: 'medium',
    description: 'Endpoint de debug ou diagnóstico encontrado sem proteção adequada.',
    impact: 'Exposição de informações internas, estado da aplicação, versões.',
    remediation: 'Remova endpoints de debug em produção ou proteja com autenticação forte.',
    safeExample: "// Remova ou proteja endpoints de debug:\nif (process.env.NODE_ENV !== 'production') {\n  app.get('/debug', adminOnly, debugHandler);\n}",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    patterns: [
      /(?:router|app)\.(?:get|post)\s*\(["'`]\/(?:debug|diagnostics|health-detail|internal)[^"'`]*["'`]/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_004',
    title: 'API sem rate limiting',
    category: 'API',
    severity: 'medium',
    description: 'Rotas de API sem limitação de requisições configurada.',
    impact: 'DoS, scraping de dados, brute force de endpoints.',
    remediation: 'Implemente rate limiting global e por endpoint sensível.',
    safeExample: "app.use('/api', rateLimit({ windowMs: 60000, max: 100 }));",
    reference: 'OWASP API4:2023 - Unrestricted Resource Consumption',
    patterns: [
      /app\.use\(["'`]\/api/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_005',
    title: 'Paginação ausente em endpoint de listagem',
    category: 'API',
    severity: 'low',
    description: 'Endpoint que retorna lista de recursos sem paginação.',
    impact: 'Endpoint pode retornar todos os registros do banco, causando DoS e vazamento de dados em massa.',
    remediation: 'Implemente paginação em todos os endpoints de listagem.',
    safeExample: "const { page = 1, limit = 20 } = req.query;\nconst skip = (page - 1) * limit;\nconst items = await db.item.findMany({ skip, take: Math.min(limit, 100) });",
    reference: 'OWASP API4:2023 - Unrestricted Resource Consumption',
    patterns: [
      /\.findMany\s*\(\s*\{(?![^}]*(?:take|limit|skip))[^}]*\}\s*\)/i,
      /\.find\s*\(\s*\{(?![^}]*(?:limit|skip))[^}]*\}\s*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_006',
    title: 'Erros detalhados expostos na API',
    category: 'API',
    severity: 'medium',
    description: 'Mensagens de erro internas sendo retornadas diretamente ao cliente.',
    impact: 'Exposição de informações sobre a estrutura interna, banco de dados, versões.',
    remediation: 'Retorne erros genéricos ao cliente. Logue detalhes internamente.',
    safeExample: "catch (err) {\n  logger.error(err); // log interno completo\n  res.status(500).json({ error: 'Internal server error' }); // genérico\n}",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    patterns: [
      /res\.(?:json|send)\s*\(\s*\{[^}]*message\s*:\s*(?:err|error)\.message/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'API_007',
    title: 'Métodos HTTP perigosos expostos',
    category: 'API',
    severity: 'medium',
    description: 'Métodos HTTP como TRACE ou DELETE estão habilitados sem restrição.',
    impact: 'TRACE pode facilitar ataques XST (Cross-Site Tracing). DELETE sem controle destrói dados.',
    remediation: 'Desabilite TRACE. Proteja DELETE com autenticação e autorização rigorosas.',
    safeExample: "// Remova TRACE:\napp.use((req, res, next) => {\n  if (req.method === 'TRACE') return res.status(405).end();\n  next();\n});",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    patterns: [
      /(?:router|app)\.trace\s*\(/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
];
