import { FileRule } from '../types';

export const apiAuthRules: FileRule[] = [
  {
    id: 'AUTHZ_010',
    title: 'Acesso a objeto por ID sem ownership (BOLA/IDOR)',
    category: 'Autorização',
    severity: 'high',
    confidence: 'medium',
    description: 'Consulta de objeto usando um ID vindo diretamente da requisição (req.params/query/body) sem verificar se o objeto pertence ao usuário autenticado.',
    impact: 'Broken Object Level Authorization (BOLA/IDOR): um usuário pode ler ou alterar registros de outros usuários apenas trocando o ID na URL.',
    attackScenarioDefensive: 'Um atacante autenticado como usuário A faz GET /api/pedidos/123 e, ao incrementar o ID para 124, acessa o pedido de outro cliente porque a query usa req.params.id sem filtrar pelo ownerId da sessão.',
    remediation: 'Inclua sempre o identificador do dono na cláusula de busca (ex.: where: { id, ownerId: req.user.id }) ou verifique a propriedade após carregar o objeto, retornando 403/404 quando não pertencer ao usuário.',
    safeExample: "// Seguro: amarra a busca ao usuário autenticado\nconst pedido = await prisma.pedido.findFirst({\n  where: { id: req.params.id, ownerId: req.user.id }\n});\nif (!pedido) return res.status(404).end();",
    testSuggestion: 'Autentique como usuário A e tente acessar/alterar um recurso criado pelo usuário B trocando o ID; o servidor deve responder 403 ou 404.',
    reference: 'OWASP API Security Top 10 API1:2023 - Broken Object Level Authorization; CWE-639',
    patterns: [
      /\.(?:findById|findByIdAndUpdate|findByIdAndDelete)\s*\(\s*req\.(?:params|query|body)\./,
      /\.(?:findUnique|findFirst|findOne)\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:\s*req\.(?:params|query|body)\.[A-Za-z0-9_]+\s*\}\s*\}/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'AUTHZ_011',
    title: 'Autorização confiando em role/flag do cliente',
    category: 'Autorização',
    severity: 'high',
    confidence: 'medium',
    description: 'Decisão de autorização baseada em um campo de role/admin/permissão enviado pelo cliente (req.body/query/headers/params) em vez de derivar do servidor.',
    impact: 'Escalonamento de privilégios: o cliente controla totalmente o valor enviado e pode se declarar admin, ignorando o controle de acesso.',
    attackScenarioDefensive: 'Um atacante adiciona "role":"admin" ou "isAdmin":true no corpo da requisição e a rota concede acesso administrativo porque verifica req.body.role === "admin" em vez de consultar a role real do usuário no banco.',
    remediation: 'Derive a role e as permissões a partir da sessão/token validado no servidor (ex.: req.user.role carregado do banco após autenticação). Nunca confie em flags de privilégio enviadas pelo cliente.',
    safeExample: "// Seguro: a role vem do usuário autenticado, não do corpo\nif (req.user.role !== 'admin') {\n  return res.status(403).json({ erro: 'Acesso negado' });\n}",
    testSuggestion: 'Envie um corpo de requisição contendo role/isAdmin/permission falsificados como usuário comum e confirme que o acesso permanece negado.',
    reference: 'OWASP API Security Top 10 API5:2023 - Broken Function Level Authorization; CWE-285',
    patterns: [
      /req\.(?:body|query|headers|params)\.(?:role|isAdmin|admin|userRole|permission|scope)\s*(?:===?|!==?)/i,
      /if\s*\(\s*req\.(?:body|query)\.[A-Za-z0-9_]*[Aa]dmin/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'AUTHZ_012',
    title: 'GraphQL introspection habilitado em produção',
    category: 'Autorização',
    severity: 'medium',
    confidence: 'medium',
    description: 'Servidor GraphQL com introspection, playground ou GraphiQL habilitados, expondo o schema completo da API.',
    impact: 'A introspection revela todos os tipos, queries, mutations e campos, facilitando o mapeamento da superfície de ataque e a descoberta de operações sensíveis.',
    attackScenarioDefensive: 'Um atacante consulta o endpoint GraphQL com a query __schema, obtém o mapa completo de mutations administrativas e usa essas informações para encadear chamadas de elevação de privilégio.',
    remediation: 'Desabilite introspection, playground e graphiql em produção (introspection: false, playground: false). Habilite-os apenas em ambientes de desenvolvimento controlados.',
    safeExample: "const server = new ApolloServer({\n  schema,\n  introspection: process.env.NODE_ENV !== 'production',\n  plugins: [process.env.NODE_ENV === 'production'\n    ? ApolloServerPluginLandingPageDisabled()\n    : ApolloServerPluginLandingPageLocalDefault()],\n});",
    testSuggestion: 'Em produção, envie uma query de introspection ({ __schema { types { name } } }) e confirme que o servidor a rejeita.',
    reference: 'OWASP API Security Top 10 API9:2023 - Improper Inventory Management; CWE-200',
    patterns: [
      /introspection\s*:\s*true/i,
      /(?:playground|graphiql)\s*:\s*true/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'MASS_001',
    title: 'Mass assignment (req.body inteiro em create/update)',
    category: 'Autorização',
    severity: 'high',
    confidence: 'medium',
    description: 'Persistência de objeto usando req.body completo em operações de create/update/save sem allowlist de campos permitidos.',
    impact: 'Mass assignment: o cliente pode injetar campos não previstos (isAdmin, role, ownerId, saldo) e modificar atributos protegidos do modelo.',
    attackScenarioDefensive: 'Ao atualizar o perfil, o atacante adiciona "isAdmin":true ao corpo; como o handler faz update({ data: req.body }), o flag é gravado e o usuário ganha privilégios administrativos.',
    remediation: 'Selecione explicitamente apenas os campos permitidos antes de persistir (allowlist), por exemplo via desestruturação ou validação de schema (Zod/Joi), nunca passando req.body bruto.',
    safeExample: "// Seguro: allowlist de campos\nconst { nome, email } = req.body;\nawait prisma.usuario.update({\n  where: { id: req.user.id },\n  data: { nome, email },\n});",
    testSuggestion: 'Envie campos extras como isAdmin/role/ownerId no corpo de uma criação ou atualização e verifique que eles são ignorados na persistência.',
    reference: 'OWASP API Security Top 10 API3:2023 - Broken Object Property Level Authorization; CWE-915',
    patterns: [
      /\.(?:create|update|updateOne|findByIdAndUpdate|save)\s*\(\s*\{\s*(?:data\s*:\s*)?req\.body\s*[},]/,
      /Object\.assign\s*\(\s*[A-Za-z0-9_]+\s*,\s*req\.body\s*\)/,
      /new\s+[A-Z][A-Za-z0-9_]*\s*\(\s*req\.body\s*\)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'OAUTH_001',
    title: 'redirect_uri com wildcard/validação aberta',
    category: 'Autenticação',
    severity: 'high',
    confidence: 'medium',
    description: 'Configuração ou validação de redirect_uri usando wildcard (*) ou comparações fracas (startsWith/includes/test) em vez de correspondência exata.',
    impact: 'Open redirect no fluxo OAuth: um atacante pode desviar o code/token de autorização para um domínio controlado por ele, sequestrando a conta da vítima.',
    attackScenarioDefensive: 'Com redirect_uri validado por startsWith("https://app.exemplo.com"), o atacante usa https://app.exemplo.com.evil.com como redirect e recebe o authorization code da vítima.',
    remediation: 'Cadastre e valide redirect_uris por correspondência exata (igualdade de string completa) contra uma allowlist registrada. Nunca use wildcards nem comparações por prefixo/substring.',
    safeExample: "const REDIRECTS_PERMITIDOS = new Set([\n  'https://app.exemplo.com/oauth/callback',\n]);\nif (!REDIRECTS_PERMITIDOS.has(redirectUri)) {\n  return res.status(400).json({ erro: 'redirect_uri inválido' });\n}",
    testSuggestion: 'Tente iniciar o fluxo OAuth com um redirect_uri que apenas começa com o domínio confiável (ex.: sufixo .evil.com) e confirme que é rejeitado.',
    reference: 'OWASP API Security Top 10 API8:2023 - Security Misconfiguration; CWE-601',
    patterns: [
      /redirect_?uri[s]?\s*[:=][^;\n]*["'`][^"'`]*\*[^"'`]*["'`]/i,
      /redirect_?uri\b[\s\S]{0,40}\.(?:startsWith|includes|test)\s*\(/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs', '.json'],
  },
  {
    id: 'OAUTH_002',
    title: 'Fluxo OAuth sem parâmetro state (CSRF login)',
    category: 'Autenticação',
    severity: 'medium',
    confidence: 'low',
    description: 'Requisição de autorização OAuth com response_type=code que não inclui o parâmetro state.',
    impact: 'Login CSRF: sem o state, o callback não pode ser vinculado à sessão que iniciou o fluxo, permitindo que um atacante force a vítima a autenticar com a conta do atacante.',
    attackScenarioDefensive: 'O atacante inicia um fluxo OAuth, captura seu próprio code e induz a vítima a abrir o callback com esse code; sem state, a aplicação associa a conta do atacante à sessão da vítima.',
    remediation: 'Gere um valor state aleatório e imprevisível por requisição, armazene-o na sessão e valide-o no callback antes de trocar o code por token.',
    safeExample: "const state = crypto.randomBytes(16).toString('hex');\nreq.session.oauthState = state;\nconst url = `${authEndpoint}?response_type=code&client_id=${id}&state=${state}`;\n// No callback: if (req.query.state !== req.session.oauthState) abortar.",
    testSuggestion: 'Inicie o fluxo e verifique que a URL de autorização contém um state aleatório; no callback, force um state divergente e confirme que o fluxo é abortado.',
    reference: 'OWASP API Security Top 10 API8:2023 - Security Misconfiguration; CWE-352',
    patterns: [
      /response_type=code(?![^"'`]*state)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'OAUTH_003',
    title: 'Cliente OAuth público sem PKCE',
    category: 'Autenticação',
    severity: 'medium',
    confidence: 'low',
    description: 'Fluxo de authorization code (response_type=code) sem code_challenge (PKCE) ou usando code_challenge_method=plain.',
    impact: 'Sem PKCE, um authorization code interceptado por um cliente público (SPA/mobile) pode ser trocado por tokens, comprometendo a conta do usuário.',
    attackScenarioDefensive: 'Em um app mobile, um aplicativo malicioso intercepta o redirect e captura o authorization code; sem PKCE (ou com method "plain"), ele troca o code por tokens válidos da vítima.',
    remediation: 'Use PKCE com code_challenge_method=S256 em todos os clientes públicos: gere um code_verifier aleatório, envie seu hash SHA-256 como code_challenge e valide-o na troca do code.',
    safeExample: "const verifier = base64url(crypto.randomBytes(32));\nconst challenge = base64url(crypto.createHash('sha256').update(verifier).digest());\nconst url = `${authEndpoint}?response_type=code&code_challenge=${challenge}&code_challenge_method=S256`;",
    testSuggestion: 'Confirme que a requisição de autorização inclui code_challenge com method S256 e que o servidor rejeita a troca do code sem o code_verifier correto.',
    reference: 'OWASP API Security Top 10 API8:2023 - Security Misconfiguration; CWE-352',
    patterns: [
      /response_type=code(?![\s\S]{0,200}code_challenge)/,
      /code_challenge_method\s*[:=]\s*["'`]plain["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'CSRF_001',
    title: 'Cookie de sessão sem SameSite (em código)',
    category: 'Autenticação',
    severity: 'medium',
    confidence: 'high',
    description: 'Configuração de cookie de sessão sem o atributo sameSite, ou com sameSite: "none" sem secure: true.',
    impact: 'Cookies enviados em requisições cross-site permitem ataques de CSRF; sameSite "none" sem secure expõe o cookie em conexões não criptografadas.',
    attackScenarioDefensive: 'Sem sameSite, um site malicioso submete um formulário oculto para a aplicação alvo; o navegador anexa o cookie de sessão da vítima e a ação state-changing é executada com a identidade dela.',
    remediation: 'Defina sameSite como "lax" ou "strict" nos cookies de sessão. Se precisar de "none" (cenários cross-site legítimos), combine sempre com secure: true.',
    safeExample: "app.use(session({\n  cookie: { httpOnly: true, secure: true, sameSite: 'strict' },\n}));",
    testSuggestion: 'Inspecione o cabeçalho Set-Cookie da sessão e confirme a presença de SameSite=Strict/Lax (ou SameSite=None acompanhado de Secure).',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-1275; CWE-352',
    patterns: [
      /cookie\s*:\s*\{(?:(?!sameSite)[^}])*\}/i,
      /sameSite\s*:\s*["'`]none["'`](?![^}]*secure\s*:\s*true)/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'CSRF_002',
    title: 'Proteção CSRF desabilitada em rota state-changing',
    category: 'Autenticação',
    severity: 'medium',
    confidence: 'medium',
    description: 'Middleware CSRF desabilitado (csrf: false) ou ignorando métodos state-changing (POST/PUT/DELETE/PATCH) em ignoreMethods.',
    impact: 'Rotas que alteram estado ficam sem proteção CSRF, permitindo que um site terceiro dispare ações em nome de um usuário autenticado.',
    attackScenarioDefensive: 'Com ignoreMethods incluindo "POST", o atacante hospeda uma página que faz um POST automático para /api/transferir; o navegador da vítima envia o cookie e a transferência ocorre sem token CSRF.',
    remediation: 'Mantenha a proteção CSRF ativa para todos os métodos que alteram estado. Restrinja ignoreMethods apenas a métodos seguros (GET, HEAD, OPTIONS) ou use tokens/SameSite consistentemente.',
    safeExample: "import csrf from 'csurf';\napp.use(csrf({\n  cookie: { httpOnly: true, secure: true, sameSite: 'strict' },\n  ignoreMethods: ['GET', 'HEAD', 'OPTIONS'],\n}));",
    testSuggestion: 'Envie um POST/PUT/DELETE sem token CSRF a partir de uma origem externa e confirme que a requisição é rejeitada (403).',
    reference: 'OWASP A01:2021 - Broken Access Control; CWE-352',
    patterns: [
      /csrf\s*:\s*false/i,
      /ignoreMethods\s*:\s*\[[^\]]*["'`](?:POST|PUT|DELETE|PATCH)["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
];
