import { FileRule } from '../types';

export const authorizationRules: FileRule[] = [
  {
    id: 'AUTHZ_001',
    title: 'Rota admin sem middleware de autenticação',
    category: 'Autorização',
    severity: 'critical',
    description: 'Rota com prefixo /admin registrada sem middleware de autenticação aparente.',
    impact: 'Acesso não autorizado a funcionalidades administrativas.',
    remediation: 'Sempre aplique middleware de autenticação e autorização antes das rotas admin.',
    safeExample: "router.use('/admin', authenticate, requireRole('admin'), adminRoutes);",
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /(?:router|app)\.[a-z]+\(["'`]\/admin[^"'`]*["'`],\s*(?!.*(?:auth|middleware|protect|verify|guard))[a-z]/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'AUTHZ_002',
    title: 'userId vindo do body da requisição',
    category: 'Autorização',
    severity: 'high',
    description: 'O userId está sendo lido do corpo da requisição em vez de extraído do token de autenticação.',
    impact: 'Usuários podem manipular o userId para agir como outros usuários (Broken Object Level Authorization).',
    remediation: 'Extraia sempre o userId do token JWT verificado, nunca do corpo da requisição.',
    safeExample: "// Correto:\nconst userId = req.user.id; // do JWT verificado\n// Nunca:\nconst userId = req.body.userId;",
    reference: 'OWASP API1:2023 - Broken Object Level Authorization',
    patterns: [
      /const\s+(?:userId|user_id)\s*=\s*req\.body\.(?:userId|user_id)/i,
      /req\.body\.(?:userId|user_id|ownerId)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'AUTHZ_003',
    title: 'Update/Delete sem verificação de ownership',
    category: 'Autorização',
    severity: 'high',
    description: 'Operações de modificação ou exclusão sem verificar se o recurso pertence ao usuário logado.',
    impact: 'Insecure Direct Object Reference (IDOR): qualquer usuário pode modificar/deletar recursos de outros.',
    remediation: 'Sempre verifique que o recurso pertence ao usuário autenticado antes de modificar.',
    safeExample: "const post = await db.post.findFirst({\n  where: { id: postId, authorId: req.user.id }\n});\nif (!post) return res.status(403).json({ error: 'Forbidden' });",
    reference: 'OWASP API1:2023 - Broken Object Level Authorization',
    patterns: [
      /(?:update|delete|destroy)\s*\(\s*\{\s*where\s*:\s*\{\s*id\s*:/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'AUTHZ_004',
    title: 'Supabase sem Row Level Security (RLS)',
    category: 'Autorização',
    severity: 'high',
    description: 'Tabelas no Supabase provavelmente sem RLS configurado.',
    impact: 'Qualquer usuário autenticado pode ler/escrever dados de outros usuários.',
    remediation: 'Habilite RLS em todas as tabelas e crie políticas adequadas.',
    safeExample: "-- Habilitar RLS:\nALTER TABLE posts ENABLE ROW LEVEL SECURITY;\n-- Política:\nCREATE POLICY \"Users can only see own posts\" ON posts\n  FOR SELECT USING (auth.uid() = user_id);",
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /supabase\.from\(["'`][^"'`]+["'`]\)\.(?:select|insert|update|delete)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'AUTHZ_005',
    title: 'Firebase Realtime Database rules permissivas',
    category: 'Autorização',
    severity: 'critical',
    description: 'Regras do Firebase permitem leitura/escrita pública.',
    impact: 'Qualquer pessoa pode ler ou modificar todo o banco de dados.',
    remediation: 'Configure rules específicas por caminho, autenticação e ownership.',
    safeExample: '{\n  "rules": {\n    "users": {\n      "$uid": {\n        ".read": "$uid === auth.uid",\n        ".write": "$uid === auth.uid"\n      }\n    }\n  }\n}',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /".read"\s*:\s*"true"/,
      /".write"\s*:\s*"true"/,
    ],
    fileExtensions: ['.json'],
    fileNamePatterns: [/database\.rules\.json/, /firestore\.rules/],
  },
  {
    id: 'AUTHZ_006',
    title: 'GraphQL sem controle de autorização por campo',
    category: 'Autorização',
    severity: 'medium',
    description: 'Resolvers GraphQL sem verificação de permissão por campo ou tipo.',
    impact: 'Usuários podem acessar campos sensíveis que não deveriam ver.',
    remediation: 'Use shield, directives de autenticação, ou verificações manuais em cada resolver sensível.',
    safeExample: "const resolvers = {\n  Query: {\n    adminData: (_, __, ctx) => {\n      if (!ctx.user?.isAdmin) throw new ForbiddenError('Unauthorized');\n      return getAdminData();\n    }\n  }\n};",
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /typeDefs\s*=\s*gql`/,
      /new\s+GraphQLSchema/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'AUTHZ_007',
    title: 'Endpoint com potencial IDOR',
    category: 'Autorização',
    severity: 'medium',
    description: 'Endpoint com parâmetro de ID no path sem verificação de ownership aparente.',
    impact: 'Acesso não autorizado a recursos de outros usuários.',
    remediation: 'Sempre verifique que o ID solicitado pertence ao usuário autenticado.',
    safeExample: "router.get('/orders/:id', auth, async (req, res) => {\n  const order = await Order.findOne({ _id: req.params.id, userId: req.user.id });\n  if (!order) return res.status(404).json({ error: 'Not found' });\n});",
    reference: 'OWASP API1:2023 - Broken Object Level Authorization',
    patterns: [
      /(?:router|app)\.[a-z]+\(["'`]\/[^"'`]*\/:id["'`]/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
];
