import { FileRule } from '../types';

export const databaseRules: FileRule[] = [
  {
    id: 'DB_001',
    title: 'MongoDB URI com credenciais exposta',
    category: 'Banco de Dados',
    severity: 'critical',
    description: 'URI de conexão com MongoDB contendo usuário e senha hardcoded.',
    impact: 'Acesso direto ao banco de dados.',
    remediation: 'Use variável de ambiente para armazenar a URI de conexão.',
    safeExample: 'const uri = process.env.MONGODB_URI;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /mongodb(?:\+srv)?:\/\/[^"'\s]+:[^"'\s]+@[^"'\s]+/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.env'],
  },
  {
    id: 'DB_002',
    title: 'Redis exposto sem autenticação',
    category: 'Banco de Dados',
    severity: 'high',
    description: 'Conexão Redis sem senha ou com configuração de acesso aberto.',
    impact: 'Acesso não autorizado ao cache/sessões. Possível RCE via Redis eval em versões antigas.',
    remediation: 'Configure senha no Redis (requirepass). Restrinja acesso por IP/firewall.',
    safeExample: 'const redis = new Redis({ host: "localhost", port: 6379, password: process.env.REDIS_PASSWORD });',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    patterns: [
      /new\s+Redis\s*\(\s*\{\s*host\s*:[^}]*\}\s*\)(?!.*password)/s,
      /redis:\/\/(?!:)[^@"\s]+/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'DB_003',
    title: 'Supabase service key exposta no cliente',
    category: 'Banco de Dados',
    severity: 'critical',
    description: 'A service role key do Supabase foi encontrada em código do cliente.',
    impact: 'Service key tem acesso de admin ao banco, bypassando RLS.',
    remediation: 'Use apenas a anon key no frontend. A service key deve ficar apenas no backend.',
    safeExample: '// Frontend: use apenas SUPABASE_ANON_KEY\n// Backend: use SUPABASE_SERVICE_ROLE_KEY em variável de ambiente',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /SUPABASE_SERVICE(?:_ROLE)?_KEY\s*=\s*["'`]?ey[A-Za-z0-9]+/,
      /service_role[^a-z].*["'`]ey[A-Za-z0-9]+/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.env'],
  },
  {
    id: 'DB_004',
    title: 'Firebase rules completamente abertas',
    category: 'Banco de Dados',
    severity: 'critical',
    description: 'Regras do Firestore ou Realtime Database permitem leitura/escrita pública.',
    impact: 'Qualquer pessoa pode ler e escrever no banco de dados sem autenticação.',
    remediation: 'Configure rules específicas com autenticação e ownership.',
    safeExample: 'rules_version = \'2\';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /{document=**} {\n      allow read, write: if request.auth != null;\n    }\n  }\n}',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /allow\s+read,\s*write\s*:\s*if\s+true/,
      /allow\s+read,\s*write/,
    ],
    fileNamePatterns: [/firestore\.rules/, /database\.rules\.json/],
  },
  {
    id: 'DB_005',
    title: 'Conexão de banco sem SSL/TLS',
    category: 'Banco de Dados',
    severity: 'medium',
    description: 'Conexão com banco de dados sem criptografia SSL/TLS.',
    impact: 'Dados em trânsito podem ser interceptados (man-in-the-middle).',
    remediation: 'Configure SSL nas conexões de banco em produção.',
    safeExample: "const db = new Pool({\n  connectionString: process.env.DATABASE_URL,\n  ssl: { rejectUnauthorized: true }\n});",
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /ssl\s*:\s*false/i,
      /sslmode\s*=\s*disable/i,
    ],
    fileExtensions: ['.js', '.ts', '.env'],
  },
  {
    id: 'DB_006',
    title: 'Migrations com dados sensíveis',
    category: 'Banco de Dados',
    severity: 'high',
    description: 'Arquivo de migration contendo dados sensíveis como senhas ou seeds de usuário admin.',
    impact: 'Dados sensíveis versionados e acessíveis a todos com acesso ao repositório.',
    remediation: 'Nunca inclua dados sensíveis em migrations. Use seeds separados e seguros.',
    safeExample: '// Seeds em scripts separados, não em migrations:\n// Não inclua senhas reais em migrations.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:INSERT INTO|VALUES)\s*\([^)]*(?:password|secret|token)[^)]*\)/i,
    ],
    fileExtensions: ['.sql', '.js', '.ts'],
  },
];
