import { FileRule } from '../types';

export const dockerRules: FileRule[] = [
  {
    id: 'DOCKER_001',
    title: 'Container rodando como root',
    category: 'Docker/DevOps',
    severity: 'high',
    description: 'Dockerfile sem instrução USER para definir usuário não-root.',
    impact: 'Se o processo do container for comprometido, o atacante tem acesso de root no container.',
    remediation: 'Adicione um USER no Dockerfile para rodar com usuário com permissões mínimas.',
    safeExample: "# No Dockerfile:\nRUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser\nUSER appuser",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^FROM\s+/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_002',
    title: 'Imagem Docker usando tag :latest',
    category: 'Docker/DevOps',
    severity: 'medium',
    description: 'Imagem base usando tag :latest sem versão específica.',
    impact: 'Builds não reproduzíveis. Atualizações automáticas podem introduzir vulnerabilidades.',
    remediation: 'Especifique sempre uma versão exata da imagem base.',
    safeExample: "FROM node:20.11-alpine3.19\n# Em vez de: FROM node:latest",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^FROM\s+[a-z0-9/._-]+:latest/im,
      /^FROM\s+[a-z0-9/._-]+\s*$/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_003',
    title: 'Arquivo .env copiado no Dockerfile',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Arquivo .env sendo copiado para dentro da imagem Docker.',
    impact: 'Secrets ficam incorporados na imagem. Qualquer pessoa com acesso à imagem obtém os secrets.',
    remediation: 'Nunca copie .env para a imagem. Use variáveis de ambiente em tempo de execução ou secrets do Docker/Kubernetes.',
    safeExample: "# Use --env-file ou secrets em runtime:\ndocker run --env-file .env myapp\n# Ou Docker secrets:\nRUN --mount=type=secret,id=env cat /run/secrets/env",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^COPY\s+(?:\.env|\.env\.[a-z]+)/im,
      /^ADD\s+(?:\.env|\.env\.[a-z]+)/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_004',
    title: 'docker.sock montado no container',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'O socket do Docker daemon está sendo montado no container.',
    impact: 'Acesso completo ao Docker daemon: criar containers privilegiados, acessar todos os containers/volumes do host.',
    remediation: 'Evite montar docker.sock. Se necessário, use um proxy de socket com permissões mínimas (tecnativa/docker-socket-proxy).',
    safeExample: "# Em vez de montar docker.sock:\n# Use um proxy com acesso mínimo:\nservices:\n  dockerproxy:\n    image: tecnativa/docker-socket-proxy\n    environment:\n      CONTAINERS: 1 # acesso mínimo",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /\/var\/run\/docker\.sock/,
    ],
    fileNamePatterns: [/docker-compose(?:\.[a-z]+)?\.ya?ml$/i],
  },
  {
    id: 'DOCKER_005',
    title: 'Container com modo privileged',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Container rodando em modo privilegiado no docker-compose.',
    impact: 'Container tem acesso total ao host: dispositivos, capacidades de kernel, possibilidade de escape do container.',
    remediation: 'Remova privileged: true. Use capabilities específicas se necessário.',
    safeExample: "# Em vez de privileged: true, use apenas o necessário:\ncap_add:\n  - NET_ADMIN\n# Nunca use privileged: true em produção",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /privileged\s*:\s*true/i,
    ],
    fileExtensions: ['.yml', '.yaml'],
  },
  {
    id: 'DOCKER_006',
    title: 'Container com network_mode: host',
    category: 'Docker/DevOps',
    severity: 'high',
    description: 'Container usando rede do host diretamente.',
    impact: 'Container tem acesso direto à interface de rede do host, eliminando isolamento de rede.',
    remediation: 'Use redes bridge isoladas. Exponha apenas as portas necessárias.',
    safeExample: "services:\n  app:\n    networks:\n      - app-network\nnetworks:\n  app-network:\n    driver: bridge",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /network_mode\s*:\s*["'`]?host["'`]?/i,
    ],
    fileExtensions: ['.yml', '.yaml'],
  },
  {
    id: 'DOCKER_007',
    title: 'Arquivo .dockerignore ausente',
    category: 'Docker/DevOps',
    severity: 'medium',
    description: 'Sem arquivo .dockerignore o contexto de build inclui arquivos desnecessários e sensíveis.',
    impact: 'node_modules, .env, .git, secrets podem ser incluídos na imagem inadvertidamente.',
    remediation: 'Crie .dockerignore com pelo menos: .env, node_modules, .git, dist, *.log',
    safeExample: "# .dockerignore\n.env\n.env.*\nnode_modules\n.git\n.gitignore\ndist\nbuild\n*.log\n*.md\ncoverage",
    reference: 'CIS Docker Benchmark',
    patterns: [/^FROM\s+/im],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_008',
    title: 'Secrets hardcoded no docker-compose',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Passwords ou secrets definidos diretamente no docker-compose.yml.',
    impact: 'Secrets versionados no repositório ficam expostos a todos com acesso ao código.',
    remediation: 'Use variáveis de ambiente (${}), arquivos .env externos ou Docker Secrets.',
    safeExample: "services:\n  db:\n    environment:\n      POSTGRES_PASSWORD: ${DB_PASSWORD} # do .env não versionado",
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:POSTGRES_PASSWORD|MYSQL_ROOT_PASSWORD|MONGO_INITDB_ROOT_PASSWORD)\s*:\s*["']?[a-zA-Z0-9!@#$%^&*]{4,}/,
    ],
    fileNamePatterns: [/docker-compose(?:\.[a-z]+)?\.ya?ml$/i],
  },
  {
    id: 'DOCKER_010',
    title: 'USER root explícito / volta para root',
    category: 'Docker/DevOps',
    severity: 'high',
    confidence: 'medium',
    description: 'O Dockerfile define explicitamente USER root (ou USER 0), frequentemente revertendo um usuário não-privilegiado configurado antes.',
    impact: 'O processo principal do container roda como root. Se a aplicação for comprometida, o atacante tem privilégios de root dentro do container, facilitando montagem de volumes sensíveis, escrita em caminhos protegidos e tentativas de escape.',
    attackScenarioDefensive: 'Um atacante que explora uma RCE na aplicação herda o usuário root do container. A partir daí pode instalar ferramentas, alterar binários do sistema e, combinado com uma capability ou montagem indevida, escalar para o host. Garantir um usuário não-root reduz a superfície dessa cadeia.',
    remediation: 'Não use USER root como instrução final. Crie um usuário dedicado de baixo privilégio e mantenha-o como o último USER antes do CMD/ENTRYPOINT. Use root apenas temporariamente durante a instalação de dependências, voltando ao usuário restrito em seguida.',
    safeExample: "RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser\n# instale dependências como root, se necessário, e então:\nUSER appuser\nCMD [\"node\", \"server.js\"]",
    testSuggestion: 'Verifique a saída de "docker run --rm sua-imagem id"; o uid/gid não deve ser 0. Garanta que a última instrução USER do Dockerfile aponte para um usuário não-root.',
    reference: 'CIS Docker Benchmark 4.1 - Create a user for the container',
    patterns: [
      /^USER\s+(?:root|0)\s*$/im,
    ],
    fileNamePatterns: [/(?:^|\/)Dockerfile(?:\.[\w.-]+)?$/i],
  },
  {
    id: 'DOCKER_011',
    title: 'Secret hardcoded em ENV/ARG',
    category: 'Docker/DevOps',
    severity: 'critical',
    confidence: 'medium',
    description: 'Senha, token ou chave de API definidos como valor literal em uma instrução ENV ou ARG do Dockerfile.',
    impact: 'Valores em ENV ficam embutidos na imagem e visíveis para qualquer processo do container e para quem executar "docker inspect". Valores em ARG persistem no histórico de camadas da imagem ("docker history"), expondo o secret mesmo que ele não esteja na imagem final.',
    attackScenarioDefensive: 'Um atacante que obtém acesso de leitura à imagem (registry comprometido, imagem pública ou cache de CI) extrai o secret inspecionando o histórico de camadas ou as variáveis de ambiente, sem precisar comprometer o runtime. Isso permite reutilizar a credencial contra os serviços associados.',
    remediation: 'Nunca coloque secrets literais em ENV/ARG. Injete credenciais em tempo de execução via variáveis de ambiente, --env-file ou orquestrador, e durante o build use BuildKit secrets (RUN --mount=type=secret) que não persistem nas camadas.',
    safeExample: "# Build com BuildKit, sem persistir o secret nas camadas:\nRUN --mount=type=secret,id=npm_token \\\n    NPM_TOKEN=$(cat /run/secrets/npm_token) npm ci\n# Em runtime: docker run --env-file .env minha-imagem",
    testSuggestion: 'Rode "docker history --no-trunc sua-imagem" e "docker inspect sua-imagem" procurando por valores que pareçam credenciais. Adicione um scan de secrets (ex.: trufflehog/gitleaks) no pipeline de build da imagem.',
    reference: 'OWASP A02:2021 - Cryptographic Failures; Docker build secrets',
    patterns: [
      /^(?:ENV|ARG)\s+\w*(?:PASSWORD|SECRET|TOKEN|API[_-]?KEY|PRIVATE[_-]?KEY|ACCESS[_-]?KEY)\w*\s*[=\s]\s*["']?[A-Za-z0-9/+_-]{8,}/im,
    ],
    fileNamePatterns: [/(?:^|\/)Dockerfile(?:\.[\w.-]+)?$/i],
  },
  {
    id: 'DOCKER_012',
    title: 'ADD com URL remota',
    category: 'Docker/DevOps',
    severity: 'medium',
    confidence: 'high',
    description: 'Instrução ADD usada para baixar um arquivo a partir de uma URL HTTP/HTTPS remota durante o build.',
    impact: 'ADD com URL baixa conteúdo remoto sem verificação de integridade e sem cache previsível. Se a origem for comprometida, sofrer MITM (HTTP) ou mudar de conteúdo, a imagem passa a conter artefatos maliciosos, comprometendo todos os containers derivados.',
    attackScenarioDefensive: 'Um atacante que controla ou intercepta a URL remota substitui o artefato baixado por uma versão maliciosa. Como o ADD não valida checksum, o build incorpora o payload silenciosamente. Usar download explícito com verificação de hash torna a adulteração detectável.',
    remediation: 'Prefira COPY para arquivos locais. Quando precisar buscar conteúdo remoto, use RUN com curl/wget seguido de verificação explícita de checksum (sha256sum -c) e remova os artefatos temporários na mesma camada.',
    safeExample: "RUN curl -fsSL https://exemplo.com/app.tar.gz -o /tmp/app.tar.gz \\\n && echo \"<sha256-esperado>  /tmp/app.tar.gz\" | sha256sum -c - \\\n && tar -xzf /tmp/app.tar.gz -C /opt \\\n && rm /tmp/app.tar.gz",
    testSuggestion: 'Faça grep por "^ADD\\s+https\\?://" nos Dockerfiles do repositório. Confirme que todo download remoto possui verificação de checksum associada antes de uso.',
    reference: 'Docker Dockerfile best practices - ADD vs COPY',
    patterns: [
      /^ADD\s+https?:\/\//im,
    ],
    fileNamePatterns: [/(?:^|\/)Dockerfile(?:\.[\w.-]+)?$/i],
  },
  {
    id: 'DOCKER_013',
    title: 'apt-get install sem limpeza de cache',
    category: 'Docker/DevOps',
    severity: 'low',
    confidence: 'medium',
    description: 'Instrução apt-get install sem remoção das listas de pacotes (rm -rf /var/lib/apt/lists/*) na mesma camada.',
    impact: 'As listas de pacotes do apt permanecem na camada da imagem, aumentando desnecessariamente o tamanho da imagem e a superfície de ataque. Camadas maiores também demoram mais para distribuir e podem reter metadados de pacotes desatualizados.',
    attackScenarioDefensive: 'Embora não seja uma vulnerabilidade direta, imagens infladas e com cache de pacotes facilitam o reconhecimento por um atacante (versões exatas de pacotes instalados) e dificultam auditoria. Imagens enxutas reduzem o que um invasor encontra após comprometer o container.',
    remediation: 'Combine apt-get update e install com a limpeza na mesma instrução RUN, usando --no-install-recommends e removendo /var/lib/apt/lists/* ao final para não deixar resíduo na camada.',
    safeExample: "RUN apt-get update \\\n && apt-get install -y --no-install-recommends curl ca-certificates \\\n && rm -rf /var/lib/apt/lists/*",
    testSuggestion: 'Compare o tamanho da imagem com "docker images" antes e depois de adicionar a limpeza. Use um linter como hadolint (regra DL3009) no pipeline para detectar apt-get sem limpeza de cache.',
    reference: 'Hadolint DL3009; Docker best practices - minimize layers',
    patterns: [
      /apt-get\s+install(?![\s\S]{0,300}rm\s+-rf\s+\/var\/lib\/apt\/lists)/i,
    ],
    fileNamePatterns: [/(?:^|\/)Dockerfile(?:\.[\w.-]+)?$/i],
  },
];
