import { FileRule } from '../types';

export const dockerRules: FileRule[] = [
  {
    id: 'DOCKER_001',
    title: 'Container rodando como root',
    category: 'Docker/DevOps',
    severity: 'high',
    description: 'Dockerfile sem instrução USER para definir usuário não-root.',
    impact: 'Se o processo do container for comprometido, o atacante tem acesso de root no container.',
    remediation: 'Adicione um USER no Dockerfile para rodar com usuário com permissões mínimas.',
    safeExample: "# No Dockerfile:\nRUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser\nUSER appuser",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^FROM\s+/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_002',
    title: 'Imagem Docker usando tag :latest',
    category: 'Docker/DevOps',
    severity: 'medium',
    description: 'Imagem base usando tag :latest sem versão específica.',
    impact: 'Builds não reproduzíveis. Atualizações automáticas podem introduzir vulnerabilidades.',
    remediation: 'Especifique sempre uma versão exata da imagem base.',
    safeExample: "FROM node:20.11-alpine3.19\n# Em vez de: FROM node:latest",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^FROM\s+[a-z0-9/._-]+:latest/im,
      /^FROM\s+[a-z0-9/._-]+\s*$/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_003',
    title: 'Arquivo .env copiado no Dockerfile',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Arquivo .env sendo copiado para dentro da imagem Docker.',
    impact: 'Secrets ficam incorporados na imagem. Qualquer pessoa com acesso à imagem obtém os secrets.',
    remediation: 'Nunca copie .env para a imagem. Use variáveis de ambiente em tempo de execução ou secrets do Docker/Kubernetes.',
    safeExample: "# Use --env-file ou secrets em runtime:\ndocker run --env-file .env myapp\n# Ou Docker secrets:\nRUN --mount=type=secret,id=env cat /run/secrets/env",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /^COPY\s+(?:\.env|\.env\.[a-z]+)/im,
      /^ADD\s+(?:\.env|\.env\.[a-z]+)/im,
    ],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_004',
    title: 'docker.sock montado no container',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'O socket do Docker daemon está sendo montado no container.',
    impact: 'Acesso completo ao Docker daemon: criar containers privilegiados, acessar todos os containers/volumes do host.',
    remediation: 'Evite montar docker.sock. Se necessário, use um proxy de socket com permissões mínimas (tecnativa/docker-socket-proxy).',
    safeExample: "# Em vez de montar docker.sock:\n# Use um proxy com acesso mínimo:\nservices:\n  dockerproxy:\n    image: tecnativa/docker-socket-proxy\n    environment:\n      CONTAINERS: 1 # acesso mínimo",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /\/var\/run\/docker\.sock/,
    ],
    fileNamePatterns: [/docker-compose(?:\.[a-z]+)?\.ya?ml$/i],
  },
  {
    id: 'DOCKER_005',
    title: 'Container com modo privileged',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Container rodando em modo privilegiado no docker-compose.',
    impact: 'Container tem acesso total ao host: dispositivos, capacidades de kernel, possibilidade de escape do container.',
    remediation: 'Remova privileged: true. Use capabilities específicas se necessário.',
    safeExample: "# Em vez de privileged: true, use apenas o necessário:\ncap_add:\n  - NET_ADMIN\n# Nunca use privileged: true em produção",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /privileged\s*:\s*true/i,
    ],
    fileExtensions: ['.yml', '.yaml'],
  },
  {
    id: 'DOCKER_006',
    title: 'Container com network_mode: host',
    category: 'Docker/DevOps',
    severity: 'high',
    description: 'Container usando rede do host diretamente.',
    impact: 'Container tem acesso direto à interface de rede do host, eliminando isolamento de rede.',
    remediation: 'Use redes bridge isoladas. Exponha apenas as portas necessárias.',
    safeExample: "services:\n  app:\n    networks:\n      - app-network\nnetworks:\n  app-network:\n    driver: bridge",
    reference: 'CIS Docker Benchmark',
    patterns: [
      /network_mode\s*:\s*["'`]?host["'`]?/i,
    ],
    fileExtensions: ['.yml', '.yaml'],
  },
  {
    id: 'DOCKER_007',
    title: 'Arquivo .dockerignore ausente',
    category: 'Docker/DevOps',
    severity: 'medium',
    description: 'Sem arquivo .dockerignore o contexto de build inclui arquivos desnecessários e sensíveis.',
    impact: 'node_modules, .env, .git, secrets podem ser incluídos na imagem inadvertidamente.',
    remediation: 'Crie .dockerignore com pelo menos: .env, node_modules, .git, dist, *.log',
    safeExample: "# .dockerignore\n.env\n.env.*\nnode_modules\n.git\n.gitignore\ndist\nbuild\n*.log\n*.md\ncoverage",
    reference: 'CIS Docker Benchmark',
    patterns: [/^FROM\s+/im],
    fileNamePatterns: [/^Dockerfile(?:\.[a-z]+)?$/i],
  },
  {
    id: 'DOCKER_008',
    title: 'Secrets hardcoded no docker-compose',
    category: 'Docker/DevOps',
    severity: 'critical',
    description: 'Passwords ou secrets definidos diretamente no docker-compose.yml.',
    impact: 'Secrets versionados no repositório ficam expostos a todos com acesso ao código.',
    remediation: 'Use variáveis de ambiente (${}), arquivos .env externos ou Docker Secrets.',
    safeExample: "services:\n  db:\n    environment:\n      POSTGRES_PASSWORD: ${DB_PASSWORD} # do .env não versionado",
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:POSTGRES_PASSWORD|MYSQL_ROOT_PASSWORD|MONGO_INITDB_ROOT_PASSWORD)\s*:\s*["']?[a-zA-Z0-9!@#$%^&*]{4,}/,
    ],
    fileNamePatterns: [/docker-compose(?:\.[a-z]+)?\.ya?ml$/i],
  },
];
