import { FileRule } from '../types';

export const dosRules: FileRule[] = [
  {
    id: 'DOS_001',
    title: 'Express sem rate limiting global',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'A aplicação instancia o Express, mas o projeto não declara nenhum middleware de rate limiting global (express-rate-limit, rate-limiter-flexible, @fastify/rate-limit ou @nestjs/throttler).',
    impact: 'Sem limitação de requisições, a API fica exposta a brute force de credenciais, scraping massivo e exaustão de recursos que pode derrubar o serviço (DoS na camada de aplicação).',
    attackScenarioDefensive: 'Um atacante automatiza milhares de requisições por segundo contra um endpoint custoso (busca, login, geração de relatório). Sem teto de requisições, a CPU e a memória do servidor saturam e usuários legítimos passam a receber timeouts.',
    remediation: 'Aplique um limitador global como primeiro middleware e limitadores mais estritos em rotas sensíveis. Combine com proteção de borda (WAF/CDN) quando possível.',
    safeExample: "import rateLimit from 'express-rate-limit';\nconst limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 });\napp.use(limiter);",
    testSuggestion: 'Envie uma rajada de requisições acima do teto configurado e verifique se as excedentes recebem HTTP 429 com header Retry-After.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-770',
    patterns: [/\bexpress\s*\(\s*\)/],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
    suppressIfProjectMatches: /express-rate-limit|rate-limiter-flexible|@fastify\/rate-limit|@nestjs\/throttler|\brateLimit\s*\(/,
  },
  {
    id: 'DOS_002',
    title: 'Body parser sem limit / limit excessivo',
    category: 'Negação de Serviço (DoS)',
    severity: 'medium',
    confidence: 'high',
    description: 'Um body parser (express.json/urlencoded/raw/text ou bodyParser) é usado sem opções, ou define um limit muito alto (dezenas de MB ou mais).',
    impact: 'Corpos de requisição grandes consomem memória e CPU no parsing, permitindo que poucos atacantes esgotem os recursos do servidor (DoS por memória).',
    attackScenarioDefensive: 'Um atacante envia repetidamente payloads JSON de muitos megabytes. Sem limite (ou com limite generoso), cada requisição aloca grande quantidade de memória durante o parse, levando o processo a OOM e à queda do serviço.',
    remediation: 'Defina explicitamente um limit conservador (ex.: 100kb–1mb) compatível com o caso de uso real e rejeite payloads acima disso com HTTP 413.',
    safeExample: "app.use(express.json({ limit: '100kb' }));\napp.use(express.urlencoded({ extended: true, limit: '100kb' }));",
    testSuggestion: 'Envie um payload acima do limite esperado e confirme que o servidor responde HTTP 413 (Payload Too Large) sem alocar o corpo inteiro.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-770',
    patterns: [
      /(?:express|bodyParser)\.(?:json|urlencoded|raw|text)\s*\(\s*\)/,
      /limit\s*:\s*['"`]\s*(?:[1-9]\d|\d{3,})\s*mb['"`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_003',
    title: 'ReDoS: regex literal com backtracking catastrófico',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Uma expressão regular literal contém quantificadores aninhados (ex.: (a+)+, (.*)+ , (?:..+)+) que podem causar backtracking exponencial.',
    impact: 'Uma única entrada cuidadosamente construída faz a regex demorar segundos ou minutos para avaliar, bloqueando o event loop e congelando todo o servidor (ReDoS).',
    attackScenarioDefensive: 'Um atacante envia uma string que ativa o caminho de backtracking catastrófico do padrão vulnerável. O processo Node fica preso em 100% de CPU avaliando a regex e deixa de atender qualquer outra requisição.',
    remediation: 'Reescreva o padrão para evitar quantificadores aninhados e grupos ambíguos. Prefira engines lineares (RE2) ou imponha timeout/limite de tamanho à entrada antes do match.',
    safeExample: "// Em vez de /(\\w+)+$/ use uma forma sem aninhamento:\nconst re = /^\\w+$/;\n// ou valide com RE2 para garantir tempo linear",
    testSuggestion: 'Meça o tempo de execução do padrão contra entradas patológicas crescentes (ex.: "aaaa...!"); o tempo não deve crescer de forma super-linear.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-1333',
    patterns: [
      /\(([^()]*[+*])\)[+*]/,
      /\((?:\.\*|\.\+)\)[+*]/,
      /\(\?:[^)]*[+*]\)[+*][^?]/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_004',
    title: 'http/https server sem timeouts (Slowloris)',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Um servidor HTTP/HTTPS é criado (createServer/listen) sem configurar timeouts (requestTimeout, headersTimeout, keepAliveTimeout ou server.setTimeout) em nenhum ponto do projeto.',
    impact: 'Conexões lentas ou inativas mantidas abertas indefinidamente esgotam o pool de conexões, impedindo novos clientes legítimos de se conectarem (ataque Slowloris).',
    attackScenarioDefensive: 'Um atacante abre centenas de conexões e envia bytes de cabeçalho muito lentamente, sem nunca completar a requisição. Sem headersTimeout/requestTimeout, o servidor mantém todas abertas até saturar e parar de aceitar conexões.',
    remediation: 'Configure requestTimeout, headersTimeout e keepAliveTimeout no servidor. Em produção, posicione um proxy reverso/WAF que aplique timeouts agressivos.',
    safeExample: "const server = http.createServer(app);\nserver.headersTimeout = 60_000;\nserver.requestTimeout = 120_000;\nserver.keepAliveTimeout = 5_000;\nserver.listen(3000);",
    testSuggestion: 'Abra uma conexão e envie cabeçalhos byte a byte com pausas longas; o servidor deve encerrar a conexão ao atingir o headersTimeout.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-400',
    patterns: [
      /\.listen\s*\(/,
      /(?:http2?|https)\.createServer\s*\(/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
    suppressIfProjectMatches: /requestTimeout|headersTimeout|keepAliveTimeout|\.setTimeout\s*\(/,
  },
  {
    id: 'DOS_005',
    title: 'Timeout de servidor desabilitado (=0)',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'high',
    description: 'Um timeout de servidor (server.timeout, requestTimeout, headersTimeout, keepAliveTimeout ou setTimeout) é explicitamente definido como 0, desabilitando-o.',
    impact: 'Com o timeout zerado, conexões podem permanecer abertas para sempre, abrindo caminho para Slowloris e exaustão de conexões.',
    attackScenarioDefensive: 'Um atacante percebe que o timeout foi desativado e mantém conexões ociosas ou lentas indefinidamente. O servidor nunca as encerra, esgotando descritores de arquivo e o pool de conexões até a indisponibilidade.',
    remediation: 'Nunca zere timeouts em produção. Defina valores finitos e razoáveis para todos os timeouts de conexão e requisição.',
    safeExample: "server.requestTimeout = 120_000; // nunca 0\nserver.headersTimeout = 60_000;",
    testSuggestion: 'Verifique no código e em tempo de execução que nenhum timeout do servidor está em 0 e que conexões inativas são encerradas.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-400',
    patterns: [
      /(?:server\.timeout|requestTimeout|headersTimeout|keepAliveTimeout)\s*=\s*0\b/,
      /\.setTimeout\s*\(\s*0\b/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_006',
    title: 'GraphQL sem depth/complexity limit',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Um servidor GraphQL (ApolloServer, GraphQL Yoga, express-graphql ou Mercurius) é inicializado sem limites de profundidade (depthLimit) ou de complexidade/custo de consulta.',
    impact: 'Consultas profundamente aninhadas ou com muitos aliases podem gerar carga computacional explosiva no resolver, derrubando a API (DoS por complexidade de query).',
    attackScenarioDefensive: 'Um atacante envia uma query GraphQL com aninhamento recursivo profundo (ex.: amigos de amigos de amigos...) ou centenas de aliases. Sem limite de profundidade/custo, o backend resolve uma árvore enorme e esgota CPU/memória.',
    remediation: 'Imponha depth limit e análise de custo/complexidade de query, além de timeout por requisição. Bloqueie introspecção em produção quando não necessária.',
    safeExample: "import depthLimit from 'graphql-depth-limit';\nconst server = new ApolloServer({\n  schema,\n  validationRules: [depthLimit(7)],\n});",
    testSuggestion: 'Envie uma query com profundidade acima do limite e confirme que é rejeitada na validação antes de qualquer resolução.',
    reference: 'OWASP API4:2023 - Unrestricted Resource Consumption; CWE-770',
    patterns: [
      /new\s+ApolloServer\s*\(/,
      /createYoga\s*\(/,
      /graphqlHTTP\s*\(/,
      /mercurius/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
    suppressIfProjectMatches: /depthLimit|graphql-depth-limit|costAnalysis|query-complexity|graphql-query-complexity|maxAliases/,
  },
  {
    id: 'DOS_007',
    title: 'Paginação/limit sem teto (unbounded)',
    category: 'Negação de Serviço (DoS)',
    severity: 'medium',
    confidence: 'medium',
    description: 'Um valor de limit/take/pageSize é passado diretamente a partir de input do usuário (req.query/req.body/req.params/ctx.query) sem um teto máximo.',
    impact: 'O usuário pode solicitar a leitura de um número arbitrário de registros, sobrecarregando o banco de dados e a memória da aplicação (DoS por consulta ilimitada).',
    attackScenarioDefensive: 'Um atacante envia ?limit=10000000 a um endpoint de listagem. Sem clamp, a consulta tenta carregar milhões de linhas em memória e serializá-las, esgotando recursos e degradando o serviço para todos.',
    remediation: 'Sempre limite (clamp) o valor de paginação a um máximo seguro e use um valor padrão. Valide e converta o input antes de usá-lo na consulta.',
    safeExample: "const MAX = 100;\nconst limit = Math.min(Number(req.query.limit) || 20, MAX);\nconst rows = await repo.find({ take: limit });",
    testSuggestion: 'Requisite um limit muito acima do máximo e verifique que a resposta retorna no máximo o teto configurado de itens.',
    reference: 'OWASP API4:2023 - Unrestricted Resource Consumption; CWE-770',
    patterns: [
      /\.(?:limit|take)\s*\(\s*(?:Number\s*\(\s*)?(?:req\.query|req\.params|req\.body|ctx\.query)\./,
      /(?:take|limit|pageSize)\s*:\s*(?:Number\s*\(\s*)?(?:req\.query|req\.body|req\.params)\./,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_008',
    title: 'Recursão/loop sem bound a partir de input',
    category: 'Negação de Serviço (DoS)',
    severity: 'medium',
    confidence: 'low',
    description: 'Um laço for/while usa um valor vindo de input do usuário (req.body/query/params ou ctx.) como condição de parada, sem limite máximo.',
    impact: 'O usuário pode forçar o servidor a iterar um número arbitrariamente grande de vezes, bloqueando o event loop e consumindo CPU (DoS por loop ilimitado).',
    attackScenarioDefensive: 'Um atacante define um campo numérico controlado (ex.: count=99999999) que alimenta diretamente a condição do laço. O processo Node fica preso iterando e deixa de atender outras requisições até concluir ou travar.',
    remediation: 'Valide e limite (clamp) qualquer contador vindo do usuário a um teto seguro antes de usá-lo como limite de iteração.',
    safeExample: "const count = Math.min(Number(req.body.count) || 0, 1000);\nfor (let i = 0; i < count; i++) { /* trabalho limitado */ }",
    testSuggestion: 'Envie um valor de contador extremamente alto e confirme que a iteração é truncada no teto e que o servidor permanece responsivo.',
    reference: 'OWASP API4:2023 - Unrestricted Resource Consumption; CWE-834',
    patterns: [
      /for\s*\([^;]*;\s*[A-Za-z_$][\w$.]*\s*<\s*(?:req\.(?:body|query|params)|ctx\.)[\w.]+/,
      /while\s*\(\s*(?:req\.(?:body|query|params))[\w.]+/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_009',
    title: 'Descompressão sem limite (zip bomb)',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Operações de descompressão (zlib.gunzip/inflate/unzip/brotliDecompress) ou bibliotecas de zip (adm-zip, unzipper, node-stream-zip, yauzl) são usadas sem limite de tamanho descomprimido.',
    impact: 'Um arquivo pequeno e altamente comprimido (zip bomb) pode expandir para gigabytes, esgotando memória e disco e derrubando o serviço.',
    attackScenarioDefensive: 'Um atacante faz upload de um arquivo de poucos KB que descomprime para muitos GB. Sem teto no tamanho de saída, a aplicação tenta materializar todo o conteúdo e sofre OOM ou enche o disco.',
    remediation: 'Imponha um limite máximo de bytes descomprimidos e aborte ao excedê-lo. Use streaming com contagem de bytes e valide a razão de compressão antes de processar.',
    safeExample: "const MAX = 50 * 1024 * 1024; // 50MB\nlet total = 0;\nstream.on('data', (chunk) => {\n  total += chunk.length;\n  if (total > MAX) stream.destroy(new Error('descompressão excedeu o limite'));\n});",
    testSuggestion: 'Processe um arquivo de teste cuja saída descomprimida excede o limite e confirme que a operação é abortada antes de esgotar a memória.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-409',
    patterns: [
      /zlib\.(?:gunzip|inflate|unzip|brotliDecompress)(?:Sync)?\s*\(/,
      /require\(\s*['"](?:adm-zip|unzipper|node-stream-zip|yauzl)['"]\s*\)/,
      /from\s+['"](?:adm-zip|unzipper|node-stream-zip|yauzl)['"]/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_010',
    title: 'HTTP/2 server sem limites de stream (Rapid Reset)',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Um servidor HTTP/2 (http2.createSecureServer/createServer) é criado sem configurar maxConcurrentStreams ou maxSessionMemory.',
    impact: 'A ausência de limites de streams concorrentes abre caminho para o ataque HTTP/2 Rapid Reset (CVE-2023-44487), capaz de saturar a CPU do servidor com baixo custo para o atacante.',
    attackScenarioDefensive: 'Um atacante abre e cancela (RST_STREAM) milhares de streams HTTP/2 imediatamente, em loop. Sem maxConcurrentStreams, o servidor cria e destrói trabalho continuamente, saturando a CPU e ficando indisponível.',
    remediation: 'Configure maxConcurrentStreams e maxSessionMemory ao criar o servidor HTTP/2 e mantenha o runtime atualizado com as mitigações de Rapid Reset.',
    safeExample: "const server = http2.createSecureServer({\n  key, cert,\n  settings: { maxConcurrentStreams: 100 },\n  maxSessionMemory: 10,\n});",
    testSuggestion: 'Abra muitos streams e cancele-os rapidamente; verifique que o servidor aplica o teto de streams concorrentes e permanece responsivo.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-770 (CVE-2023-44487)',
    patterns: [
      /http2\.(?:createSecureServer|createServer)\s*\(/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
    suppressIfProjectMatches: /maxConcurrentStreams|maxSessionMemory/,
  },
  {
    id: 'DOS_011',
    title: 'Ausência de circuit breaker em chamadas externas',
    category: 'Negação de Serviço (DoS)',
    severity: 'low',
    confidence: 'low',
    description: 'Chamadas HTTP a serviços externos (axios, fetch) são feitas sem circuit breaker, timeout ou AbortController em nenhum ponto do projeto.',
    impact: 'Se um serviço externo ficar lento ou indisponível, as requisições acumulam e bloqueiam recursos da aplicação, propagando a falha (DoS por exaustão em cascata).',
    attackScenarioDefensive: 'Uma dependência externa começa a responder lentamente. Sem timeout nem circuit breaker, cada requisição do usuário fica pendurada aguardando o terceiro; as conexões e threads se esgotam e a aplicação inteira para de responder.',
    remediation: 'Aplique timeouts em todas as chamadas externas e use um circuit breaker (ex.: opossum, cockatiel) com fallback. Use AbortController/signal para cancelar requisições lentas.',
    safeExample: "import CircuitBreaker from 'opossum';\nconst call = () => axios.get(url, { timeout: 3000 });\nconst breaker = new CircuitBreaker(call, { timeout: 3000, errorThresholdPercentage: 50 });",
    testSuggestion: 'Simule um serviço externo lento/indisponível e verifique que as chamadas sofrem timeout e que o circuit breaker abre, evitando acúmulo de requisições.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-400',
    patterns: [
      /axios\.(?:get|post|put|delete|request)\s*\(/,
      /\bfetch\s*\(/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
    suppressIfProjectMatches: /\bopossum\b|\bcockatiel\b|AbortController|timeout\s*:\s*\d|\bsignal\s*:/,
  },
  {
    id: 'DOS_012',
    title: 'compression() sobre conteúdo dinâmico sensível',
    category: 'Negação de Serviço (DoS)',
    severity: 'low',
    confidence: 'low',
    description: 'O middleware compression() é habilitado, podendo comprimir respostas dinâmicas que misturam segredos e dados refletidos do usuário.',
    impact: 'Comprimir respostas com conteúdo sensível e reflexo do usuário pode habilitar ataques de oráculo de compressão (BREACH/CRIME) que vazam tokens.',
    attackScenarioDefensive: 'Um atacante observa o tamanho de respostas comprimidas enquanto varia uma entrada refletida. Variações no tamanho comprimido revelam, byte a byte, um segredo (ex.: token CSRF) presente na mesma resposta.',
    remediation: 'Não comprima respostas que misturem segredos e input refletido. Desabilite compressão para conteúdo sensível ou separe segredos do reflexo do usuário e use mitigações anti-BREACH.',
    safeExample: "app.use(compression({\n  filter: (req, res) => !res.getHeader('X-Sensitive') && compression.filter(req, res),\n}));",
    testSuggestion: 'Verifique que respostas contendo tokens/segredos com dados refletidos não são comprimidas ou aplicam mitigação anti-BREACH.',
    reference: 'OWASP A02:2021 - Cryptographic Failures; CWE-310 (BREACH)',
    patterns: [
      /\bcompression\s*\(\s*\)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'DOS_013',
    title: 'GitHub Actions sem timeout-minutes',
    category: 'Negação de Serviço (DoS)',
    severity: 'low',
    confidence: 'medium',
    description: 'Um workflow do GitHub Actions define jobs (runs-on) sem timeout-minutes, permitindo execuções sem limite de tempo.',
    impact: 'Jobs travados ou maliciosos podem consumir minutos de CI indefinidamente, esgotando cota e recursos do runner (DoS de pipeline e custo).',
    attackScenarioDefensive: 'Um pull request introduz um passo que entra em loop ou aguarda para sempre. Sem timeout-minutes, o job ocupa o runner por horas, bloqueando a fila de CI e consumindo a cota da organização.',
    remediation: 'Defina timeout-minutes em todos os jobs (e idealmente em passos críticos) para garantir que execuções sejam encerradas após um limite razoável.',
    safeExample: "jobs:\n  build:\n    runs-on: ubuntu-latest\n    timeout-minutes: 15\n    steps:\n      - uses: actions/checkout@v4",
    testSuggestion: 'Revise todos os workflows e confirme que cada job declara timeout-minutes com um valor finito.',
    reference: 'OWASP A05:2021 - Security Misconfiguration; CWE-400',
    patterns: [
      /^\s*runs-on\s*:/m,
    ],
    fileExtensions: ['.yml', '.yaml'],
    fileNamePatterns: [/\.github\/workflows\/[^/]+\.ya?ml$/],
  },
  {
    id: 'DOS_014',
    title: 'ReDoS: RegExp construído com input do usuário',
    category: 'Negação de Serviço (DoS)',
    severity: 'high',
    confidence: 'medium',
    description: 'Uma instância de RegExp é construída dinamicamente a partir de input do usuário (req./body./params./query.) ou por concatenação de variáveis.',
    impact: 'O atacante controla o próprio padrão da regex e pode injetar uma expressão com backtracking catastrófico, bloqueando o event loop (ReDoS) — ou alterar a lógica de validação.',
    attackScenarioDefensive: 'Um atacante envia um valor que vira o padrão de um new RegExp(userInput). Ele fornece uma expressão patológica que, ao ser avaliada contra qualquer texto, entra em backtracking exponencial e congela o servidor.',
    remediation: 'Nunca construa RegExp a partir de input do usuário. Use comparações literais, escape o input com uma função de escape de regex, ou valide contra um conjunto fixo de padrões com engine de tempo linear (RE2).',
    safeExample: "function escapeRegex(s) {\n  return s.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n}\nconst re = new RegExp(escapeRegex(req.query.term));",
    testSuggestion: 'Garanta que nenhum padrão de RegExp deriva de input do usuário; teste com entradas patológicas e meça o tempo de avaliação.',
    reference: 'OWASP A03:2021 - Injection; CWE-1333',
    patterns: [
      /new\s+RegExp\s*\([^)]*(?:req\.|body\.|params\.|query\.)[A-Za-z_]/,
      /new\s+RegExp\s*\(\s*[A-Za-z_$][\w$]*\s*\+/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
];
