import { FileRule } from '../types';

export const firebaseRules: FileRule[] = [
  {
    id: 'FIRE_001',
    title: 'Firebase Admin SDK no frontend',
    category: 'Firebase',
    severity: 'critical',
    confidence: 'high',
    description: 'Firebase Admin SDK sendo importado em código de cliente (React, Next.js páginas do cliente).',
    impact: 'O Admin SDK tem acesso irrestrito ao Firebase. Exposto no cliente, qualquer usuário pode usar para deletar dados, criar usuários admin, etc.',
    attackScenarioDefensive: 'Usuário inspeciona o bundle, encontra o admin SDK inicializado, extrai as credenciais e tem acesso de admin ao projeto Firebase.',
    remediation: 'Mova o Firebase Admin SDK para Next.js API routes, Cloud Functions ou outro backend. O cliente deve usar apenas o Firebase Client SDK.',
    safeExample: "// ✅ Backend (Next.js API route, Cloud Function):\nimport admin from 'firebase-admin';\nadmin.initializeApp({ credential: admin.credential.cert(serviceAccount) });\n\n// ❌ Nunca no frontend/client:",
    reference: 'Firebase Security - Admin SDK',
    patterns: [
      /firebase-admin/i,
      /require\(['"`]firebase-admin['"`]\)/,
      /from\s+['"`]firebase-admin['"`;]/,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'FIRE_002',
    title: 'Firebase serviceAccountKey.json referenciado',
    category: 'Firebase',
    severity: 'critical',
    confidence: 'high',
    description: 'Referência a serviceAccountKey.json detectada. Este arquivo contém credenciais privadas do Firebase.',
    impact: 'Acesso irrestrito ao Firebase Admin: banco, auth, storage, FCM.',
    attackScenarioDefensive: 'Arquivo commitado no repositório é descoberto por atacante via GitHub search ou histórico do git.',
    remediation: 'Remova o arquivo. Adicione ao .gitignore. Use variável de ambiente com o conteúdo JSON: process.env.FIREBASE_SERVICE_ACCOUNT_JSON',
    safeExample: "const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON || '{}');\nadmin.initializeApp({ credential: admin.credential.cert(serviceAccount) });",
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /serviceAccountKey\.json/i,
      /firebase-adminsdk.*\.json/i,
    ],
    fileExtensions: ['.js', '.ts', '.json', '.env'],
  },
  {
    id: 'FIRE_003',
    title: 'Firebase Realtime Database rules completamente abertas',
    category: 'Firebase',
    severity: 'critical',
    confidence: 'high',
    description: 'Regras do Firebase permitem leitura e/ou escrita para qualquer pessoa sem autenticação.',
    impact: 'Qualquer pessoa no mundo pode ler todos os dados do banco e/ou escrever dados maliciosos.',
    attackScenarioDefensive: 'Atacante descobre a URL do Firebase pelo JS do frontend e faz requests diretos para ler todos os dados de usuários.',
    remediation: 'Configure rules com autenticação obrigatória e restricão por usuário.',
    safeExample: '{\n  "rules": {\n    "users": {\n      "$uid": {\n        ".read": "$uid === auth.uid",\n        ".write": "$uid === auth.uid"\n      }\n    }\n  }\n}',
    reference: 'Firebase Security Rules',
    patterns: [
      /['"`.read['"`.]\s*:\s*["'`]?true["'`]?/,
      /['"`.write['"`.]\s*:\s*["'`]?true["'`]?/,
      /allow\s+read\s*,\s*write\s*:\s*if\s+true/,
      /allow\s+read\s*:\s*if\s+true/,
      /allow\s+write\s*:\s*if\s+true/,
    ],
    fileNamePatterns: [/database\.rules\.json/, /firestore\.rules/, /storage\.rules/],
  },
  {
    id: 'FIRE_004',
    title: 'Firestore sem validação por request.auth.uid',
    category: 'Firebase',
    severity: 'high',
    confidence: 'medium',
    description: 'Regras do Firestore sem verificação de autenticação via request.auth.uid.',
    impact: 'Dados podem ser acessíveis por usuários não autenticados ou por outros usuários autenticados.',
    attackScenarioDefensive: 'Usuário autenticado acessa coleções de outros usuários por manipulação de path.',
    remediation: 'Sempre inclua request.auth != null && request.auth.uid == resource.data.userId nas regras.',
    safeExample: "rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /users/{userId}/{document=**} {\n      allow read, write: if request.auth != null && request.auth.uid == userId;\n    }\n  }\n}",
    reference: 'Firebase Security Rules',
    patterns: [
      /allow\s+(?:read|write|create|update|delete)\s*:\s*if\s+request\.auth\s*!=\s*null(?!\s*&&\s*request\.auth\.uid)/,
    ],
    fileNamePatterns: [/firestore\.rules/],
  },
  {
    id: 'FIRE_005',
    title: 'Firebase Storage rules abertas',
    category: 'Firebase',
    severity: 'high',
    confidence: 'high',
    description: 'Firebase Storage com regras que permitem acesso sem autenticação.',
    impact: 'Qualquer pessoa pode fazer upload ou download de arquivos.',
    attackScenarioDefensive: 'Atacante faz upload de malware ou conteúdo ilegal no bucket de storage público.',
    remediation: 'Configure Storage rules para exigir autenticação.',
    safeExample: "rules_version = '2';\nservice firebase.storage {\n  match /b/{bucket}/o {\n    match /users/{userId}/{allPaths=**} {\n      allow read, write: if request.auth != null && request.auth.uid == userId;\n    }\n  }\n}",
    reference: 'Firebase Storage Security Rules',
    patterns: [
      /allow\s+read\s*,\s*write\s*:\s*if\s+true/,
    ],
    fileNamePatterns: [/storage\.rules/],
  },
  {
    id: 'FIRE_006',
    title: 'Firebase config com projeto de produção hardcoded',
    category: 'Firebase',
    severity: 'low',
    confidence: 'medium',
    description: 'Configuração do Firebase com projectId de produção hardcoded no código.',
    impact: 'Baixo por si só, mas facilita enumeração e ataques direcionados.',
    attackScenarioDefensive: 'Atacante usa o projectId para tentar acessar endpoints Firebase diretamente.',
    remediation: 'Mova a config do Firebase para variáveis de ambiente. Embora seja pública, evite hardcodar em produção.',
    safeExample: "const firebaseConfig = {\n  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,\n  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,\n  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,\n};",
    reference: 'Firebase Security Best Practices',
    patterns: [
      /projectId\s*:\s*["'`][a-z0-9-]{6,}["'`]/i,
      /storageBucket\s*:\s*["'`][a-z0-9-]+\.appspot\.com["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
];
