import { FileRule } from '../types';

export const githubRules: FileRule[] = [
  {
    id: 'CICD_001',
    title: 'Token em workflow do GitHub Actions',
    category: 'CI/CD',
    severity: 'critical',
    description: 'Token ou secret hardcoded em arquivo de workflow do GitHub Actions.',
    impact: 'Token exposto no repositório pode ser usado por qualquer pessoa com acesso ao código.',
    remediation: 'Use ${{ secrets.MY_SECRET }} para todos os secrets em workflows.',
    safeExample: "- name: Deploy\n  env:\n    API_KEY: ${{ secrets.API_KEY }}\n  run: deploy.sh",
    reference: 'OWASP A04:2025 - Cryptographic Failures',
    patterns: [
      /(?:TOKEN|KEY|SECRET|PASSWORD)\s*=\s*["']?[A-Za-z0-9+\/=_\-]{16,}(?!\s*\$\{\{)/,
    ],
    fileNamePatterns: [/\.github\/workflows\/.+\.ya?ml$/],
  },
  {
    id: 'CICD_002',
    title: 'Permissões excessivas no workflow',
    category: 'CI/CD',
    severity: 'medium',
    description: 'Workflow sem declaração explícita de permissions ou com permissions: write-all.',
    impact: 'Workflow pode ter permissões excessivas, facilitando comprometimento do repositório.',
    remediation: 'Declare permissions mínimas necessárias explicitamente.',
    safeExample: "permissions:\n  contents: read\n  pull-requests: write",
    reference: 'CIS GitHub Actions Benchmark',
    patterns: [
      /permissions\s*:\s*write-all/i,
    ],
    fileNamePatterns: [/\.github\/workflows\/.+\.ya?ml$/],
  },
  {
    id: 'CICD_003',
    title: 'Deploy automático sem proteção de branch',
    category: 'CI/CD',
    severity: 'medium',
    description: 'Deploy automático sem verificação de branch protegida ou aprovação.',
    impact: 'Qualquer push pode disparar deploy em produção.',
    remediation: 'Configure branch protection rules. Exija aprovações para PRs em produção.',
    safeExample: "on:\n  push:\n    branches: [main]\n# Configure branch protection no repositório.",
    reference: 'CIS GitHub Actions Benchmark',
    patterns: [
      /on\s*:\s*\n\s*push/m,
    ],
    fileNamePatterns: [/\.github\/workflows\/(?:deploy|prod|release).+\.ya?ml$/i],
  },
  {
    id: 'CICD_004',
    title: 'curl pipe bash sem verificação de integridade',
    category: 'CI/CD',
    severity: 'high',
    description: 'Script CI/CD executa conteúdo remoto via curl | bash sem verificação de hash.',
    impact: 'Se o recurso remoto for comprometido, código malicioso é executado no CI/CD.',
    remediation: 'Verifique a integridade com checksum antes de executar. Prefira actions específicas.',
    safeExample: "# Em vez de: curl -s https://... | bash\n# Faça:\ncurl -s https://... -o script.sh\nsha256sum -c expected.sha256\nbash script.sh",
    reference: 'OWASP A08:2025 - Software and Data Integrity Failures',
    patterns: [
      /curl[^|]+\|\s*(?:bash|sh)/,
    ],
    fileNamePatterns: [/\.github\/workflows\/.+\.ya?ml$/, /\.yml$/, /\.yaml$/],
  },
  {
    id: 'CICD_005',
    title: 'npm install sem lockfile',
    category: 'CI/CD',
    severity: 'medium',
    description: 'CI/CD executando npm install em vez de npm ci (que usa lockfile).',
    impact: 'Versões de dependências podem mudar entre builds, introduzindo supply chain attacks.',
    remediation: 'Use npm ci em vez de npm install em CI/CD.',
    safeExample: "- name: Install dependencies\n  run: npm ci --prefer-offline",
    reference: 'OWASP A08:2025 - Software and Data Integrity Failures',
    patterns: [
      /run\s*:\s*npm\s+install(?!\s+--)/,
    ],
    fileNamePatterns: [/\.github\/workflows\/.+\.ya?ml$/],
  },
];
