import { HttpRule } from '../types';

export const headersRules: HttpRule[] = [
  {
    id: 'HEAD_001',
    title: 'Header HSTS ausente',
    category: 'Headers HTTP',
    severity: 'medium',
    description: 'O header Strict-Transport-Security não está presente.',
    impact: 'Sem HSTS, usuários podem ser forçados a conexões HTTP inseguras (SSL stripping).',
    remediation: 'Adicione HSTS com max-age de pelo menos 1 ano e includeSubDomains.',
    safeExample: 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => !headers['strict-transport-security'],
  },
  {
    id: 'HEAD_002',
    title: 'Content-Security-Policy ausente',
    category: 'Headers HTTP',
    severity: 'medium',
    description: 'O header Content-Security-Policy não está configurado.',
    impact: 'Sem CSP, ataques XSS podem executar scripts de qualquer origem.',
    remediation: 'Configure uma CSP restritiva. Comece com default-src \'self\'.',
    safeExample: "Content-Security-Policy: default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'",
    reference: 'OWASP A03:2021 - Injection (XSS)',
    check: (headers) => !headers['content-security-policy'],
  },
  {
    id: 'HEAD_003',
    title: 'X-Frame-Options ausente',
    category: 'Headers HTTP',
    severity: 'medium',
    description: 'O header X-Frame-Options não está presente.',
    impact: 'A página pode ser embutida em iframes de outros sites (Clickjacking).',
    remediation: 'Adicione X-Frame-Options: DENY ou SAMEORIGIN.',
    safeExample: 'X-Frame-Options: DENY',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => !headers['x-frame-options'] && !headers['content-security-policy']?.includes('frame-ancestors'),
  },
  {
    id: 'HEAD_004',
    title: 'X-Content-Type-Options ausente',
    category: 'Headers HTTP',
    severity: 'low',
    description: 'O header X-Content-Type-Options: nosniff não está presente.',
    impact: 'O navegador pode fazer MIME type sniffing e executar arquivos com tipo errado.',
    remediation: 'Adicione X-Content-Type-Options: nosniff.',
    safeExample: 'X-Content-Type-Options: nosniff',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => headers['x-content-type-options'] !== 'nosniff',
  },
  {
    id: 'HEAD_005',
    title: 'Referrer-Policy ausente ou permissivo',
    category: 'Headers HTTP',
    severity: 'low',
    description: 'O header Referrer-Policy não está configurado ou é permissivo.',
    impact: 'URLs com dados sensíveis podem ser vazados via header Referer para sites terceiros.',
    remediation: 'Configure Referrer-Policy: strict-origin-when-cross-origin ou no-referrer.',
    safeExample: 'Referrer-Policy: strict-origin-when-cross-origin',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => !headers['referrer-policy'],
  },
  {
    id: 'HEAD_006',
    title: 'X-Powered-By expondo tecnologia',
    category: 'Headers HTTP',
    severity: 'info',
    description: 'O header X-Powered-By está expondo a tecnologia do backend (ex: Express, PHP).',
    impact: 'Informação útil para atacantes na fase de reconhecimento.',
    remediation: 'Remova o header X-Powered-By ou substitua por valor neutro.',
    safeExample: "app.disable('x-powered-by'); // Express\n// ou via Helmet: helmet() remove automaticamente",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => !!headers['x-powered-by'],
  },
  {
    id: 'HEAD_007',
    title: 'Server header expondo versão',
    category: 'Headers HTTP',
    severity: 'info',
    description: 'O header Server está expondo a versão do software do servidor.',
    impact: 'Permite identificação de versões vulneráveis específicas.',
    remediation: 'Configure o servidor para não expor a versão no header Server.',
    safeExample: '# nginx.conf:\nserver_tokens off;\n# Apache:\nServerTokens Prod\nServerSignature Off',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => {
      const server = headers['server'] || '';
      return /\d+\.\d+/.test(server);
    },
  },
  {
    id: 'HEAD_008',
    title: 'Permissions-Policy ausente',
    category: 'Headers HTTP',
    severity: 'low',
    description: 'O header Permissions-Policy não está configurado.',
    impact: 'Sem restrição de features do navegador: câmera, microfone, geolocalização podem ser acessados por iframes.',
    remediation: 'Configure Permissions-Policy para restringir features não utilizadas.',
    safeExample: "Permissions-Policy: camera=(), microphone=(), geolocation=(self), payment=()",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) => !headers['permissions-policy'],
  },
  {
    id: 'HEAD_009',
    title: 'CORS permissivo com credentials',
    category: 'Headers HTTP',
    severity: 'high',
    description: 'CORS configurado com Access-Control-Allow-Origin: * e Access-Control-Allow-Credentials: true.',
    impact: 'Configuração inválida que pode levar a comportamento inesperado ou vulnerabilidades em algumas versões de browsers.',
    remediation: 'Nunca combine Allow-Origin: * com Allow-Credentials: true. Use origens específicas.',
    safeExample: 'Access-Control-Allow-Origin: https://meuapp.com\nAccess-Control-Allow-Credentials: true',
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    check: (headers) =>
      headers['access-control-allow-origin'] === '*' &&
      headers['access-control-allow-credentials'] === 'true',
  },
];
