import { FileRule } from '../types';

export const jwtRules: FileRule[] = [
  {
    id: 'JWT_001',
    title: 'jwt.verify aceitando o algoritmo do token (algorithm confusion / alg:none)',
    category: 'JWT',
    severity: 'critical',
    confidence: 'high',
    description: 'jwt.verify chamado sem restringir explicitamente o array de algorithms, permitindo que o token dite o algoritmo.',
    impact: 'Algorithm confusion (RS256 -> HS256) ou alg:none permitem forjar tokens válidos e bypass total de autenticação.',
    attackScenarioDefensive: 'Atacante muda o header para HS256 e assina o token usando a chave pública RSA como segredo HMAC, sendo aceito pelo servidor.',
    remediation: 'Sempre passe algorithms com a lista fixa esperada (ex.: ["RS256"]) na opção de jwt.verify.',
    safeExample: "jwt.verify(token, publicKey, { algorithms: ['RS256'] });",
    testSuggestion: 'Forjar token com alg:none e com HS256 usando a chave pública e confirmar que ambos são rejeitados.',
    reference: 'OWASP A02:2021; CWE-347',
    patterns: [
      /jwt\.verify\s*\(\s*[^,]+,\s*[^,)]+\)/,
      /jwt\.verify\s*\([^)]*\)(?![^;]*algorithms)/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'JWT_002',
    title: 'alg:none habilitado explicitamente',
    category: 'JWT',
    severity: 'critical',
    confidence: 'high',
    description: 'Configuração que inclui "none" na lista de algorithms ou define alg/algorithm como "none".',
    impact: 'Tokens sem assinatura são aceitos como válidos, permitindo forjar qualquer identidade e bypass total de autenticação.',
    attackScenarioDefensive: 'Atacante cria um JWT com header {"alg":"none"} e payload arbitrário, sem assinatura, e é aceito como autenticado.',
    remediation: 'Nunca permita o algoritmo "none". Restrinja a verificação a algoritmos com assinatura forte (RS256/ES256/HS256).',
    safeExample: "jwt.verify(token, key, { algorithms: ['RS256'] }); // 'none' jamais incluído",
    testSuggestion: 'Enviar token com alg:none e confirmar rejeição imediata.',
    reference: 'OWASP A02:2021; CWE-347',
    patterns: [
      /algorithms\s*:\s*\[[^\]]*["'`]none["'`]/i,
      /\balg(?:orithm)?\s*[:=]\s*["'`]none["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs', '.py', '.go'],
  },
  {
    id: 'JWT_003',
    title: 'jwt.decode() usado para autenticação',
    category: 'JWT',
    severity: 'high',
    confidence: 'high',
    description: 'Uso de jwt.decode (jsonwebtoken/jose) que apenas decodifica o payload sem verificar a assinatura.',
    impact: 'Como decode não valida a assinatura, qualquer payload forjado é aceito, permitindo bypass de autenticação/autorização.',
    attackScenarioDefensive: 'Atacante altera o claim role para "admin" num token não assinado; decode lê o valor sem checar a assinatura.',
    remediation: 'Use jwt.verify (com chave e algorithms) para qualquer decisão de segurança. Reserve decode apenas para inspeção sem confiança.',
    safeExample: "const payload = jwt.verify(token, key, { algorithms: ['RS256'] }); // verifica assinatura",
    testSuggestion: 'Enviar token com assinatura inválida e confirmar que o acesso é negado.',
    reference: 'OWASP A02:2021; CWE-347',
    patterns: [
      /jwt\.decode\s*\(/,
      /(?:jsonwebtoken|jose)[\s\S]{0,80}\bdecode\s*\(/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'JWT_004',
    title: 'Segredo JWT fraco ou hardcoded',
    category: 'JWT',
    severity: 'critical',
    confidence: 'medium',
    description: 'jwt.sign com segredo curto (<=15 chars) literal, ou variável de segredo definida como valor trivial (secret/changeme/test/123456).',
    impact: 'Segredos fracos/conhecidos permitem que atacantes forjem tokens válidos por força bruta ou adivinhação.',
    attackScenarioDefensive: 'Atacante adivinha ou descobre o segredo "secret" no código e assina tokens com privilégios arbitrários.',
    remediation: 'Use um segredo aleatório longo (>=32 bytes) carregado de variável de ambiente / cofre de segredos, nunca hardcoded.',
    safeExample: "const secret = process.env.JWT_SECRET; // valor aleatório forte fora do código\njwt.sign(payload, secret, { algorithm: 'HS256', expiresIn: '15m' });",
    testSuggestion: 'Tentar assinar/verificar tokens com segredos comuns de wordlist e confirmar que falham.',
    reference: 'OWASP A02:2021; CWE-321',
    patterns: [
      /jwt\.sign\s*\([^,]+,\s*["'`][^"'`]{1,15}["'`]/,
      /(?:JWT_SECRET|jwtSecret|secret)\s*[:=]\s*["'`](?:secret|changeme|password|test|123456|key)["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'JWT_005',
    title: 'kid do header usado sem validação (kid injection)',
    category: 'JWT',
    severity: 'high',
    confidence: 'medium',
    description: 'Valor kid do header do JWT usado diretamente em caminho de arquivo, join, interpolação ou consulta SQL para obter a chave.',
    impact: 'Kid injection: path traversal/SQLi via kid permite ao atacante apontar para uma chave controlada e forjar tokens.',
    attackScenarioDefensive: 'Atacante define kid como "../../public/key.pem" ou injeta SQL no kid para fazer o servidor usar uma chave conhecida na verificação.',
    remediation: 'Trate kid como identificador opaco e valide contra um conjunto fixo de chaves (allowlist). Nunca o use em caminhos de arquivo ou queries sem sanitização.',
    safeExample: "const key = KEYS[header.kid]; // lookup em mapa fixo\nif (!key) return reject();",
    testSuggestion: 'Enviar kid com sequências ../ e payloads SQL e confirmar que são rejeitados.',
    reference: 'OWASP A02:2021; CWE-347',
    patterns: [
      /(?:header|decoded|payload)\.kid\b[\s\S]{0,60}(?:readFileSync|join\s*\(|`[^`]*\$\{)/,
      /(?:SELECT|WHERE)[\s\S]{0,80}\bkid\b/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
  {
    id: 'JWT_006',
    title: 'JWT ignorando expiração (ignoreExpiration:true)',
    category: 'JWT',
    severity: 'high',
    confidence: 'high',
    description: 'Verificação de JWT configurada com ignoreExpiration:true, desativando a checagem do claim exp.',
    impact: 'Tokens expirados continuam válidos indefinidamente, anulando a revogação por tempo de vida e sessões vazadas.',
    attackScenarioDefensive: 'Atacante reutiliza um token roubado há semanas; como a expiração é ignorada, o acesso permanece válido.',
    remediation: 'Remova ignoreExpiration (ou deixe false) para que exp seja validado, e defina expiresIn curto na emissão.',
    safeExample: "jwt.verify(token, key, { algorithms: ['RS256'] }); // exp é validado por padrão",
    testSuggestion: 'Verificar um token com exp no passado e confirmar que é rejeitado.',
    reference: 'OWASP A02:2021; CWE-613',
    patterns: [
      /ignoreExpiration\s*:\s*true/i,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs'],
  },
];
