import { FileRule } from '../types';

export const logsRules: FileRule[] = [
  {
    id: 'LOG_001',
    title: 'Token em console.log',
    category: 'Logs',
    severity: 'high',
    description: 'Tokens de autenticação sendo logados no console.',
    impact: 'Tokens aparecem em arquivos de log, sistemas de monitoramento, e são visíveis em ambientes compartilhados.',
    remediation: 'Nunca logue tokens. Se precisar debugar, logue apenas parte mascarada.',
    safeExample: '// Em vez de: console.log(token);\nconsole.log("Token length:", token?.length); // mascarado',
    reference: 'OWASP A09:2021 - Security Logging and Monitoring Failures',
    patterns: [
      /console\.log\([^)]*(?:token|jwt|bearer|authorization)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'LOG_002',
    title: 'Senha em log',
    category: 'Logs',
    severity: 'critical',
    description: 'Senhas ou campos de senha sendo logados.',
    impact: 'Senhas aparecem em texto puro em logs, comprometendo todos os usuários afetados.',
    remediation: 'Nunca logue campos de senha. Remova-os do objeto antes de logar.',
    safeExample: "const { password, ...safeUser } = req.body;\nconsole.log('User data:', safeUser); // sem senha",
    reference: 'OWASP A09:2021 - Security Logging and Monitoring Failures',
    patterns: [
      /console\.(?:log|info|warn|error)\([^)]*(?:password|senha|passwd|pwd)[^)]*\)/i,
      /logger\.[a-z]+\([^)]*(?:password|senha|passwd)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'LOG_003',
    title: 'Authorization header em log',
    category: 'Logs',
    severity: 'high',
    description: 'Headers de autorização sendo logados, expondo tokens Bearer.',
    impact: 'Tokens de acesso aparecem em logs e podem ser usados para impersonar usuários.',
    remediation: 'Filtre headers sensíveis antes de logar. Nunca logue Authorization.',
    safeExample: "const safeHeaders = { ...req.headers };\ndelete safeHeaders.authorization;\nconsole.log('Request headers:', safeHeaders);",
    reference: 'OWASP A09:2021 - Security Logging and Monitoring Failures',
    patterns: [
      /console\.log\([^)]*(?:headers|req\.headers)[^)]*\)/i,
      /console\.log\([^)]*authorization[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'LOG_004',
    title: 'Dados pessoais em log',
    category: 'Logs',
    severity: 'medium',
    description: 'CPF, e-mail, telefone ou outros dados pessoais sendo logados.',
    impact: 'Violação de LGPD/GDPR. Dados pessoais em logs de sistema.',
    remediation: 'Aplique mascaramento em dados pessoais antes de logar. Use IDs em vez de dados pessoais.',
    safeExample: "// Use IDs nos logs:\nconsole.log(`User ${userId} performed action`); // não email/cpf",
    reference: 'LGPD / GDPR / OWASP A09',
    patterns: [
      /console\.log\([^)]*(?:email|cpf|telefone|phone|document)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'LOG_005',
    title: 'Erro bruto com stack trace em produção',
    category: 'Logs',
    severity: 'medium',
    description: 'Erros internos sendo enviados para o cliente com stack trace completo.',
    impact: 'Revela estrutura interna, versões, caminhos de arquivo para atacantes.',
    remediation: 'Em produção, retorne mensagens genéricas. Logue internamente com stack trace.',
    safeExample: "app.use((err, req, res, next) => {\n  logger.error(err); // log completo internamente\n  res.status(500).json({ error: 'Internal server error' }); // genérico para o cliente\n});",
    reference: 'OWASP A05:2021 - Security Misconfiguration',
    patterns: [
      /res\.(?:json|send)\s*\(\s*(?:err|error)\.stack/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
];
