import { FileRule } from '../types';

/**
 * Regras "poliglotas": cobrem linguagens além de JS/Python que já são
 * varridas pelo fileWalker (Go, Java, PHP, Ruby) e alguns padrões transversais
 * (Zip Slip, LDAP injection). Regex sem quantificador aninhado.
 */
export const polyglotRules: FileRule[] = [
  {
    id: 'POLY_001',
    title: 'Go: Command Injection via exec.Command com string montada',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'medium',
    description: 'exec.Command recebe argumento montado com fmt.Sprintf ou concatenação, ou invoca um shell (sh -c) com string dinâmica.',
    impact: 'Entrada do usuário no comando permite executar comandos arbitrários no servidor.',
    remediation: 'Passe argumentos como parâmetros separados (exec.Command("cmd", arg1, arg2)), nunca via shell, e valide contra allowlist.',
    safeExample: 'cmd := exec.Command("convert", inputPath, outputPath)',
    reference: 'OWASP A05:2025 - Injection; CWE-78',
    patterns: [
      /exec\.Command\([^)]*(?:fmt\.Sprintf|\+\s*[a-zA-Z_])/,
      /exec\.Command\(\s*"(?:sh|bash|cmd)"\s*,\s*"-c"\s*,\s*[a-zA-Z_]/,
    ],
    fileExtensions: ['.go'],
  },
  {
    id: 'POLY_002',
    title: 'Go: template.HTML/JS com valor dinâmico (bypass do escaping)',
    category: 'Injeção',
    severity: 'high',
    confidence: 'medium',
    description: 'template.HTML(...) ou template.JS(...) aplicado a uma variável desativa o escaping automático do html/template.',
    impact: 'Se o valor vier do usuário, é XSS direto na página renderizada.',
    remediation: 'Não converta entrada do usuário em template.HTML. Deixe o html/template escapar e use apenas para conteúdo estático confiável.',
    safeExample: 'tmpl.Execute(w, map[string]string{"name": userInput}) // escapado automaticamente',
    reference: 'OWASP A05:2025 - Injection (XSS); CWE-79',
    patterns: [
      /template\.(?:HTML|JS|URL|CSS)\(\s*[a-zA-Z_][\w.]*\s*\)/,
    ],
    fileExtensions: ['.go'],
  },
  {
    id: 'POLY_003',
    title: 'Go/Java: SQL montado por concatenação ou Sprintf',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'medium',
    description: 'Query SQL construída com fmt.Sprintf/concatenação em Go, ou com "+" em createStatement/executeQuery/prepareStatement no Java.',
    impact: 'SQL Injection: leitura, alteração ou destruição do banco de dados inteiro.',
    remediation: 'Use placeholders parametrizados ($1/?), PreparedStatement com setX(), ou um ORM com binding.',
    safeExample: 'db.Query("SELECT * FROM users WHERE id = $1", id)\nps = conn.prepareStatement("SELECT * FROM users WHERE id = ?"); ps.setInt(1, id);',
    reference: 'OWASP A05:2025 - Injection; CWE-89',
    patterns: [
      /db\.(?:Query|QueryRow|Exec)(?:Context)?\(\s*(?:ctx\s*,\s*)?(?:fmt\.Sprintf|"[^"]*"\s*\+)/,
      /(?:executeQuery|executeUpdate|execute|prepareStatement|createQuery)\s*\(\s*"[^"]*"\s*\+\s*[a-zA-Z_]/,
    ],
    fileExtensions: ['.go', '.java', '.kt'],
  },
  {
    id: 'POLY_004',
    title: 'PHP: include/require com entrada do usuário (LFI/RFI)',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'high',
    description: 'include/require recebe diretamente $_GET/$_POST/$_REQUEST, permitindo Local/Remote File Inclusion.',
    impact: 'Leitura de arquivos arbitrários (/etc/passwd, configs) e, com allow_url_include ou upload, execução remota de código.',
    remediation: 'Nunca inclua caminhos vindos do usuário. Use um mapa fixo (allowlist) de páginas permitidas.',
    safeExample: "$pages = ['home' => 'home.php', 'about' => 'about.php'];\ninclude $pages[$_GET['p']] ?? 'home.php';",
    reference: 'OWASP A05:2025 - Injection; CWE-98',
    patterns: [
      /\b(?:include|require)(?:_once)?\s*\(?\s*\$_(?:GET|POST|REQUEST|COOKIE)\b/,
      /\b(?:include|require)(?:_once)?\s*\(?\s*["'][^"']*["']\s*\.\s*\$_(?:GET|POST|REQUEST)\b/,
    ],
    fileExtensions: ['.php'],
  },
  {
    id: 'POLY_005',
    title: 'PHP: extract() / register_globals sobre superglobais',
    category: 'Injeção',
    severity: 'high',
    confidence: 'high',
    description: 'extract($_GET/$_POST/$_REQUEST) cria variáveis a partir de qualquer parâmetro da requisição, sobrescrevendo variáveis internas.',
    impact: 'Atacante define variáveis como $isAdmin, $userId ou caminhos de arquivo, contornando lógica de autorização.',
    remediation: 'Nunca use extract() em dados externos. Leia parâmetros explicitamente e valide cada um.',
    safeExample: "$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);",
    reference: 'OWASP A01:2025 - Broken Access Control; CWE-621',
    patterns: [
      /\bextract\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)\b/,
      /\bparse_str\s*\([^,)]*\)\s*;/,
    ],
    fileExtensions: ['.php'],
  },
  {
    id: 'POLY_006',
    title: 'PHP: query SQL com superglobal interpolada',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'high',
    description: 'mysqli_query/->query/->exec recebe uma string contendo $_GET/$_POST/$_REQUEST diretamente.',
    impact: 'SQL Injection clássica com acesso total ao banco.',
    remediation: 'Use PDO/mysqli com prepared statements e bind de parâmetros.',
    safeExample: "$stmt = $pdo->prepare('SELECT * FROM users WHERE id = :id');\n$stmt->execute(['id' => $_GET['id']]);",
    reference: 'OWASP A05:2025 - Injection; CWE-89',
    patterns: [
      /(?:mysqli?_query|->query|->exec|pg_query)\s*\([^;]*\$_(?:GET|POST|REQUEST|COOKIE)\b/,
    ],
    fileExtensions: ['.php'],
  },
  {
    id: 'POLY_007',
    title: 'Ruby: send/constantize/eval com parâmetro da requisição',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'high',
    description: 'params[...] é usado em send/public_send/constantize/eval/instance_eval, permitindo invocar métodos ou classes arbitrárias.',
    impact: 'Execução de código arbitrário ou acesso a métodos internos (ex.: destroy, update_attribute) via nome controlado pelo usuário.',
    remediation: 'Mapeie valores permitidos em uma allowlist explícita antes de invocar dinamicamente.',
    safeExample: "ACTIONS = { 'approve' => :approve!, 'reject' => :reject! }\nrecord.public_send(ACTIONS.fetch(params[:action]))",
    reference: 'OWASP A05:2025 - Injection; CWE-470',
    patterns: [
      /params\[[^\]]+\]\s*\.\s*(?:constantize|safe_constantize|to_sym\s*\)?\s*\.\s*send)/,
      /\.\s*(?:send|public_send|__send__)\s*\(\s*params\[/,
      /\b(?:eval|instance_eval|class_eval)\s*\(?\s*params\[/,
    ],
    fileExtensions: ['.rb'],
  },
  {
    id: 'POLY_008',
    title: 'Ruby: desserialização insegura (YAML.load / Marshal.load) de entrada',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'high',
    description: 'YAML.load ou Marshal.load aplicado a dados de params/request/cookies. Ambos instanciam objetos arbitrários.',
    impact: 'Execução remota de código via gadget chains de desserialização (histórico de CVEs em Rails).',
    remediation: 'Use YAML.safe_load (com permitted_classes) e nunca Marshal.load em dados externos; prefira JSON.',
    safeExample: 'YAML.safe_load(input, permitted_classes: [Date], aliases: false)',
    reference: 'OWASP A08:2025 - Software or Data Integrity Failures; CWE-502',
    patterns: [
      /YAML\.load\s*\(\s*(?:params|request|cookies|Base64)/,
      /Marshal\.load\s*\(\s*(?:params|request|cookies|Base64)/,
    ],
    fileExtensions: ['.rb'],
  },
  {
    id: 'POLY_009',
    title: 'Zip Slip: nome de entrada de arquivo compactado usado em caminho sem validação',
    category: 'Upload',
    severity: 'high',
    confidence: 'medium',
    description: 'O nome de uma entrada de ZIP/TAR (entry.name, entry.fileName, entry.path) é usado em path.join/resolve para gravar em disco sem verificar se o resultado permanece dentro do diretório de destino.',
    impact: 'Um arquivo compactado malicioso com entradas "../../etc/cron.d/x" grava fora do diretório alvo, sobrescrevendo arquivos do sistema e obtendo execução de código.',
    remediation: 'Após resolver o caminho, verifique que ele começa com o diretório de destino (path.resolve + startsWith(dest + path.sep)) e rejeite entradas com "..".',
    safeExample: "const target = path.resolve(dest, entry.name);\nif (!target.startsWith(path.resolve(dest) + path.sep)) throw new Error('Zip Slip');",
    reference: 'OWASP A01:2025 - Broken Access Control (Path Traversal); CWE-22 (Zip Slip)',
    patterns: [
      /path\.(?:join|resolve)\([^)]*\b(?:entry|zipEntry|header|file)\.(?:name|fileName|filename|path|entryName)\b/,
      /(?:os\.path\.join|Path)\([^)]*\b(?:member|info|entry)\.(?:filename|name)\b/,
    ],
    fileExtensions: ['.js', '.ts', '.mjs', '.cjs', '.py', '.java', '.go'],
    suppressIfProjectMatches: /startsWith\(\s*(?:path\.)?resolve\(|Zip ?Slip|isInside|is_within|filepath\.Rel\(/i,
  },
  {
    id: 'POLY_010',
    title: 'LDAP Injection: filtro montado com entrada do usuário',
    category: 'Injeção',
    severity: 'high',
    confidence: 'medium',
    description: 'Filtro LDAP construído por template string/concatenação com valores da requisição, sem escaping dos caracteres especiais ( ) * \\ NUL.',
    impact: 'Atacante altera a lógica do filtro para autenticar sem senha, enumerar usuários ou ler atributos restritos do diretório.',
    remediation: 'Escape os valores (ldap-escape / ldap3.utils.conv.escape_filter_chars) ou use bibliotecas que aceitem parâmetros separados.',
    safeExample: "const { filter } = require('ldap-escape');\nclient.search(base, { filter: filter`(uid=${username})` })",
    reference: 'OWASP A05:2025 - Injection; CWE-90',
    patterns: [
      /filter\s*[:=]\s*`\([^`]*\$\{/,
      /filter\s*[:=]\s*["']\([^"']*["']\s*\+\s*[a-zA-Z_]/,
      /search_filter\s*=\s*f["']\(/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.java'],
    requireContent: /ldap/i,
  },
  {
    id: 'POLY_011',
    title: 'Java: XXE — parser XML sem desabilitar entidades externas',
    category: 'Injeção',
    severity: 'high',
    confidence: 'low',
    description: 'DocumentBuilderFactory/SAXParserFactory/XMLInputFactory instanciado sem setFeature(disallow-doctype-decl) ou sem desativar entidades externas.',
    impact: 'XML External Entity: leitura de arquivos locais, SSRF interno e DoS (billion laughs) a partir de um XML enviado pelo cliente.',
    remediation: 'Desabilite DOCTYPE e entidades externas em todos os parsers XML (ver OWASP XXE Prevention Cheat Sheet).',
    safeExample: 'dbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);\ndbf.setXIncludeAware(false);\ndbf.setExpandEntityReferences(false);',
    reference: 'OWASP A02:2025 - Security Misconfiguration (XXE); CWE-611',
    patterns: [
      /(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory)\.newInstance\(\)/,
    ],
    fileExtensions: ['.java', '.kt'],
    suppressIfProjectMatches: /disallow-doctype-decl|IS_SUPPORTING_EXTERNAL_ENTITIES|ACCESS_EXTERNAL_DTD|external-general-entities/,
  },
  {
    id: 'POLY_012',
    title: 'Java/Kotlin: desserialização Java nativa de entrada externa',
    category: 'Injeção',
    severity: 'critical',
    confidence: 'medium',
    description: 'ObjectInputStream.readObject() sobre um stream vindo de request/socket/arquivo enviado pelo usuário, sem filtro de classes (ObjectInputFilter).',
    impact: 'Gadget chains (ysoserial) permitem execução remota de código na desserialização.',
    remediation: 'Evite serialização Java para dados externos (use JSON). Se inevitável, aplique ObjectInputFilter com allowlist de classes.',
    safeExample: 'ois.setObjectInputFilter(ObjectInputFilter.Config.createFilter("com.minhaapp.dto.*;!*"));',
    reference: 'OWASP A08:2025 - Software or Data Integrity Failures; CWE-502',
    patterns: [
      /new\s+ObjectInputStream\s*\(\s*(?:request|req|socket|in|input|stream|bytes|file)/i,
    ],
    fileExtensions: ['.java', '.kt'],
    suppressIfProjectMatches: /setObjectInputFilter|ObjectInputFilter\.Config/,
  },
];
