import { FileRule } from '../types';

export const privacyRules: FileRule[] = [
  {
    id: 'PRIV_001',
    title: 'Dados pessoais em localStorage',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'CPF, e-mail ou outros dados pessoais sendo armazenados em localStorage.',
    impact: 'Dados pessoais expostos a scripts XSS e acessíveis por extensões de navegador.',
    remediation: 'Não armazene dados pessoais sensíveis no localStorage. Use apenas IDs de referência.',
    safeExample: "// Armazene apenas o ID:\nlocalStorage.setItem('userId', user.id);\n// Não: localStorage.setItem('userCpf', user.cpf)",
    reference: 'LGPD Art. 46 - Segurança e Sigilo de Dados',
    patterns: [
      /localStorage\.setItem\([^,]+,\s*[^)]*(?:cpf|document|email|phone|telefone)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'PRIV_002',
    title: 'Ausência de política de privacidade',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'Nenhum link ou referência a política de privacidade encontrado.',
    impact: 'Descumprimento da LGPD (art. 9). Exposição a multas e sanções.',
    remediation: 'Crie e publique uma política de privacidade. Vincule nas páginas de cadastro e rodapé.',
    safeExample: '// Adicione link para política de privacidade:\n<a href="/privacy-policy">Política de Privacidade</a>',
    reference: 'LGPD Art. 9 - Direito do Titular',
    patterns: [
      /privacy[_-]?policy|política\s+de\s+privacidade/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.html'],
  },
  {
    id: 'PRIV_003',
    title: 'Ausência de funcionalidade de exclusão de conta',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'Nenhuma rota ou endpoint de exclusão de conta de usuário encontrado.',
    impact: 'Violação do direito ao esquecimento (LGPD art. 18, VI).',
    remediation: 'Implemente rota de exclusão de conta com remoção ou anonimização dos dados pessoais.',
    safeExample: "router.delete('/account', auth, async (req, res) => {\n  await User.anonymize(req.user.id);\n  res.json({ message: 'Account deleted' });\n});",
    reference: 'LGPD Art. 18 - Direitos do Titular',
    patterns: [
      /delete.*account|excluir.*conta|deletar.*usuario/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'PRIV_004',
    title: 'Logs contendo dados pessoais identificáveis',
    category: 'Privacidade/LGPD',
    severity: 'high',
    description: 'Sistema de logs registrando CPF, e-mail, ou outros dados pessoais.',
    impact: 'Dados pessoais em logs: acesso por equipe técnica, exposição em violações de dados.',
    remediation: 'Pseudonimize ou remova dados pessoais dos logs. Use IDs internos.',
    safeExample: "// Log com pseudonimização:\nlogger.info(`Request from user_${hashUserId(userId)} to ${endpoint}`);",
    reference: 'LGPD Art. 46 / OWASP A09',
    patterns: [
      /(?:console\.log|logger\.[a-z]+)\([^)]*(?:req\.body|req\.params)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'PRIV_005',
    title: 'Cookies sem aviso de consentimento',
    category: 'Privacidade/LGPD',
    severity: 'low',
    description: 'Nenhum banner ou componente de consentimento de cookies encontrado.',
    impact: 'Violação da LGPD e ePrivacy Directive para usuários europeus.',
    remediation: 'Implemente um banner de consentimento de cookies antes de definir cookies de rastreamento.',
    safeExample: '// Implemente CookieConsent:\n<CookieConsent onAccept={enableAnalytics} onDecline={disableTracking} />',
    reference: 'LGPD Art. 8 - Consentimento',
    patterns: [
      /cookie[Cc]onsent|cookie-consent|lgpd|gdpr/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.html'],
  },
];
