import { FileRule } from '../types';

export const privacyRules: FileRule[] = [
  {
    id: 'PRIV_001',
    title: 'Dados pessoais em localStorage',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'CPF, e-mail ou outros dados pessoais sendo armazenados em localStorage.',
    impact: 'Dados pessoais expostos a scripts XSS e acessíveis por extensões de navegador.',
    remediation: 'Não armazene dados pessoais sensíveis no localStorage. Use apenas IDs de referência.',
    safeExample: "// Armazene apenas o ID:\nlocalStorage.setItem('userId', user.id);\n// Não: localStorage.setItem('userCpf', user.cpf)",
    reference: 'LGPD Art. 46 - Segurança e Sigilo de Dados',
    patterns: [
      /localStorage\.setItem\([^,]+,\s*[^)]*(?:cpf|document|email|phone|telefone)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'PRIV_002',
    title: 'Ausência de política de privacidade',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'Nenhum link ou referência a política de privacidade encontrado.',
    impact: 'Descumprimento da LGPD (art. 9). Exposição a multas e sanções.',
    remediation: 'Crie e publique uma política de privacidade. Vincule nas páginas de cadastro e rodapé.',
    safeExample: '// Adicione link para política de privacidade:\n<a href="/privacy-policy">Política de Privacidade</a>',
    reference: 'LGPD Art. 9 - Direito do Titular',
    patterns: [
      /privacy[_-]?policy|política\s+de\s+privacidade/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.html'],
  },
  {
    id: 'PRIV_003',
    title: 'Ausência de funcionalidade de exclusão de conta',
    category: 'Privacidade/LGPD',
    severity: 'medium',
    description: 'Nenhuma rota ou endpoint de exclusão de conta de usuário encontrado.',
    impact: 'Violação do direito ao esquecimento (LGPD art. 18, VI).',
    remediation: 'Implemente rota de exclusão de conta com remoção ou anonimização dos dados pessoais.',
    safeExample: "router.delete('/account', auth, async (req, res) => {\n  await User.anonymize(req.user.id);\n  res.json({ message: 'Account deleted' });\n});",
    reference: 'LGPD Art. 18 - Direitos do Titular',
    patterns: [
      /delete.*account|excluir.*conta|deletar.*usuario/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'PRIV_004',
    title: 'Logs contendo dados pessoais identificáveis',
    category: 'Privacidade/LGPD',
    severity: 'high',
    description: 'Sistema de logs registrando CPF, e-mail, ou outros dados pessoais.',
    impact: 'Dados pessoais em logs: acesso por equipe técnica, exposição em violações de dados.',
    remediation: 'Pseudonimize ou remova dados pessoais dos logs. Use IDs internos.',
    safeExample: "// Log com pseudonimização:\nlogger.info(`Request from user_${hashUserId(userId)} to ${endpoint}`);",
    reference: 'LGPD Art. 46 / OWASP A09',
    patterns: [
      /(?:console\.log|logger\.[a-z]+)\([^)]*(?:req\.body|req\.params)[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'PRIV_005',
    title: 'Cookies sem aviso de consentimento',
    category: 'Privacidade/LGPD',
    severity: 'low',
    description: 'Nenhum banner ou componente de consentimento de cookies encontrado.',
    impact: 'Violação da LGPD e ePrivacy Directive para usuários europeus.',
    remediation: 'Implemente um banner de consentimento de cookies antes de definir cookies de rastreamento.',
    safeExample: '// Implemente CookieConsent:\n<CookieConsent onAccept={enableAnalytics} onDecline={disableTracking} />',
    reference: 'LGPD Art. 8 - Consentimento',
    patterns: [
      /cookie[Cc]onsent|cookie-consent|lgpd|gdpr/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.html'],
  },
  {
    id: 'PRIVACY_010',
    title: 'Número de cartão hardcoded ou logado',
    category: 'Privacidade/LGPD',
    severity: 'critical',
    confidence: 'medium',
    description: 'Número de cartão de crédito (Visa, Mastercard ou American Express) aparentemente fixo no código-fonte, em arquivos de configuração ou registrado em logs.',
    impact: 'Dados de cartão expostos no repositório ou em logs violam o PCI-DSS e a LGPD. Um vazamento permite fraude financeira direta contra os titulares e responsabiliza a empresa por descumprimento regulatório.',
    attackScenarioDefensive: 'Um atacante com acesso de leitura ao repositório, a backups ou a agregadores de log coleta os números de cartão em texto claro e os utiliza (ou revende) para transações fraudulentas, sem precisar comprometer o ambiente de produção.',
    remediation: 'Nunca armazene PAN (Primary Account Number) em código, configuração ou logs. Use um gateway/tokenizador de pagamento (ex.: Stripe, Pagar.me) e trabalhe apenas com tokens. Mascare qualquer número de cartão antes de registrá-lo (exiba somente os 4 últimos dígitos).',
    safeExample: "// Use tokens do gateway, nunca o PAN:\nconst { token } = await gateway.tokenize(cardForm);\n// Para exibição/log, mascare:\nconst masked = `**** **** **** ${pan.slice(-4)}`;",
    testSuggestion: 'Insira uma string de teste como "4111111111111111" em um arquivo .ts e confirme que o scanner reporta PRIVACY_010 com severidade critical.',
    reference: 'PCI-DSS Req. 3 / LGPD Art. 46 - Segurança e Sigilo de Dados',
    patterns: [
      /\b4[0-9]{12}(?:[0-9]{3})?\b/,
      /\b5[1-5][0-9]{14}\b/,
      /\b3[47][0-9]{13}\b/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py', '.json', '.log'],
  },
  {
    id: 'PRIVACY_011',
    title: 'CPF hardcoded ou em log',
    category: 'Privacidade/LGPD',
    severity: 'high',
    confidence: 'medium',
    description: 'CPF formatado (000.000.000-00) fixo em string literal no código ou variável "cpf" sendo passada diretamente para uma chamada de log.',
    impact: 'O CPF é um dado pessoal sensível para identificação de cidadãos brasileiros. Expô-lo no código ou em logs facilita correlação de identidade, fraude e descumprimento da LGPD.',
    attackScenarioDefensive: 'Um atacante ou colaborador com acesso aos logs ou ao histórico do repositório extrai CPFs em texto claro e os usa para engenharia social, abertura de cadastros fraudulentos ou enriquecimento de bases de dados vazadas.',
    remediation: 'Não fixe CPFs reais no código (use geradores de dados fictícios em testes). Pseudonimize ou mascare o CPF antes de logá-lo, exibindo apenas dígitos parciais (ex.: ***.***.***-00).',
    safeExample: "// Mascare antes de logar:\nconst cpfMascarado = cpf.replace(/^\\d{3}\\.\\d{3}\\.\\d{3}/, '***.***.***');\nlogger.info(`Titular ${cpfMascarado} atualizado`);",
    testSuggestion: 'Adicione `const cpf = "123.456.789-09";` ou `console.log(cpf)` a um arquivo .ts e verifique que PRIVACY_011 é reportado.',
    reference: 'LGPD Art. 5 / Art. 46 - Segurança e Sigilo de Dados',
    patterns: [
      /["'`]\d{3}\.\d{3}\.\d{3}-\d{2}["'`]/,
      /(?:console\.(?:log|info|warn|error)|logger\.[a-z]+)\s*\([^)]*\bcpf\b[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py'],
  },
  {
    id: 'PRIVACY_012',
    title: 'PII em log estruturado ou monitoramento de erros',
    category: 'Privacidade/LGPD',
    severity: 'high',
    confidence: 'low',
    description: 'Dados pessoais (senha, CPF, e-mail, telefone, cartão) sendo enviados para logs ou para ferramentas de monitoramento de erros como Sentry (captureException/captureMessage).',
    impact: 'PII capturada por agregadores de log e plataformas de APM/erros fica retida por terceiros, fora do controle de retenção da LGPD, e amplia a superfície de exposição em caso de incidente.',
    attackScenarioDefensive: 'Um atacante que comprometa a conta da ferramenta de monitoramento (ou um insider com acesso ao painel de erros) coleta senhas, CPFs e e-mails que vazaram nos breadcrumbs e payloads de exceção, reaproveitando-os em ataques de credential stuffing.',
    remediation: 'Configure scrubbing/redaction de campos sensíveis antes de enviar eventos ao monitoramento. Nunca inclua senhas ou documentos em mensagens de log; registre apenas identificadores internos pseudonimizados.',
    safeExample: "// Remova PII antes de capturar o erro:\nSentry.captureException(err, {\n  extra: { userId: hashUserId(user.id) }, // sem email/cpf/senha\n});",
    testSuggestion: 'Inclua `Sentry.captureMessage(`falha login ${password}`)` em um arquivo .ts e confirme que PRIVACY_012 dispara.',
    reference: 'LGPD Art. 46 / OWASP A09:2021 - Security Logging and Monitoring Failures',
    patterns: [
      /(?:console\.(?:log|info|debug)|logger\.[a-z]+|captureException|captureMessage)\s*\([^)]*\b(?:password|senha|cpf|email|phone|telefone|cartao|creditCard)\b[^)]*\)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py'],
  },
  {
    id: 'PRIVACY_013',
    title: 'PII enviada a provedor de IA sem anonimização',
    category: 'Privacidade/LGPD',
    severity: 'high',
    confidence: 'low',
    description: 'Dados pessoais (e-mail, CPF, nome, endereço do usuário) interpolados diretamente em prompts, mensagens ou conteúdo enviados a um provedor de IA/LLM.',
    impact: 'Enviar PII a APIs de IA de terceiros pode transferir dados pessoais para fora do país e fora da base legal definida, além de risco de retenção/treinamento sobre esses dados, violando a LGPD e contratos de processamento.',
    attackScenarioDefensive: 'Dados pessoais enviados em prompts podem ser retidos pelo provedor, aparecer em logs do serviço de IA ou serem expostos por prompt injection/vazamento de contexto, permitindo que terceiros recuperem informações identificáveis dos titulares.',
    remediation: 'Anonimize ou pseudonimize a PII antes de enviá-la ao provedor de IA (remova nome, CPF, e-mail e endereço, ou substitua por tokens). Verifique a base legal e o acordo de processamento de dados (DPA) com o provedor e desative o uso para treinamento.',
    safeExample: "// Substitua PII por placeholders antes de enviar ao LLM:\nconst prompt = `Resuma o pedido do cliente ${'{CLIENTE}'} sobre ${assunto}`;\n// Não interpole user.email/user.cpf/user.name diretamente.",
    testSuggestion: 'Crie `const messages = `Olá ${user.email}`` em um arquivo .ts e verifique que PRIVACY_013 é reportado.',
    reference: 'LGPD Art. 7 / Art. 33 - Transferência Internacional de Dados',
    patterns: [
      /(?:messages|prompt|content|input)\s*[:=][\s\S]{0,200}?\$\{[^}]*\b(?:user\.(?:email|cpf|name|fullName|address)|email|cpf)\b[^}]*\}/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.jsx', '.tsx'],
  },
];
