import { FileRule } from '../types';

export const reactRules: FileRule[] = [
  {
    id: 'REACT_001',
    title: 'Uso de dangerouslySetInnerHTML',
    category: 'React/Frontend',
    severity: 'high',
    description: 'dangerouslySetInnerHTML pode permitir XSS se o conteúdo não for sanitizado.',
    impact: 'Atacante pode injetar scripts maliciosos que executam no contexto do usuário.',
    remediation: 'Use DOMPurify para sanitizar HTML antes de renderizar. Prefira componentes React para conteúdo dinâmico.',
    safeExample: "import DOMPurify from 'dompurify';\n<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(content) }} />",
    reference: 'OWASP A03:2021 - Injection (XSS)',
    patterns: [/dangerouslySetInnerHTML/],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'REACT_002',
    title: 'Token de autenticação em localStorage',
    category: 'React/Frontend',
    severity: 'medium',
    description: 'Tokens JWT ou de autenticação armazenados em localStorage são vulneráveis a ataques XSS.',
    impact: 'Qualquer script na página pode roubar o token e impersonar o usuário.',
    remediation: 'Use cookies HttpOnly com SameSite=Strict e Secure para armazenar tokens de autenticação.',
    safeExample: '// Backend define cookie:\n// res.cookie("token", jwt, { httpOnly: true, secure: true, sameSite: "strict" })',
    reference: 'OWASP A07:2021 - Identification and Authentication Failures',
    patterns: [
      /localStorage\.setItem\(["'`][^"'`]*(?:token|jwt|auth|session)[^"'`]*["'`]/i,
      /localStorage\[["'`][^"'`]*(?:token|jwt|auth)[^"'`]*["'`]\]\s*=/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'REACT_003',
    title: 'Uso direto de innerHTML',
    category: 'React/Frontend',
    severity: 'high',
    description: 'Manipulação direta de innerHTML com dados não sanitizados pode causar XSS.',
    impact: 'Injeção de scripts maliciosos no DOM.',
    remediation: 'Use textContent em vez de innerHTML para texto puro. Para HTML, use DOMPurify.',
    safeExample: "element.textContent = userInput;\n// ou com HTML: element.innerHTML = DOMPurify.sanitize(userInput);",
    reference: 'OWASP A03:2021 - Injection (XSS)',
    patterns: [
      /\.innerHTML\s*=\s*(?!["'`]<[a-z]+[^>]*>[^<]+<\/[a-z]+>["'`])/,
      /document\.write\(/,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'REACT_004',
    title: 'Lógica de autorização apenas no frontend',
    category: 'React/Frontend',
    severity: 'high',
    description: 'Controle de acesso implementado apenas no frontend pode ser facilmente bypassado.',
    impact: 'Usuários podem acessar recursos protegidos manipulando o estado do frontend.',
    remediation: 'Sempre valide permissões no backend. O frontend pode ocultar elementos, mas o backend deve rejeitar requisições não autorizadas.',
    safeExample: '// Backend:\nrouter.get("/admin/data", requireAdmin, (req, res) => { ... });',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /(?:isAdmin|isOwner|hasPermission|userRole)\s*(?:===|!==|==)\s*["'`](?:admin|owner|superuser)["'`]\s*(?:&&|\?)/i,
      /role\s*===\s*["'`]admin["'`]\s*&&\s*(?:<|return)/i,
    ],
    fileExtensions: ['.jsx', '.tsx'],
  },
  {
    id: 'REACT_005',
    title: 'Secret exposto via VITE_',
    category: 'React/Frontend',
    severity: 'high',
    description: 'Variáveis de ambiente com prefixo VITE_ são incluídas no bundle do cliente e expostas publicamente.',
    impact: 'Secrets como API keys ficam visíveis no código-fonte do frontend.',
    remediation: 'Nunca prefixe secrets com VITE_. Use VITE_ apenas para configurações não sensíveis. Secrets devem ficar no backend.',
    safeExample: '# .env\n# Nunca:\n# VITE_SECRET_KEY=...\n# Sim (não sensível):\nVITE_APP_TITLE=MeuApp',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /VITE_(?:SECRET|KEY|TOKEN|PASSWORD|PRIVATE|API_KEY|AUTH)\s*=/i,
      /import\.meta\.env\.VITE_(?:SECRET|KEY|TOKEN|PASSWORD|PRIVATE)/i,
    ],
    fileExtensions: ['.env', '.env.local', '.env.production', '.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'REACT_006',
    title: 'Secret exposto via NEXT_PUBLIC_',
    category: 'React/Frontend',
    severity: 'high',
    description: 'Variáveis com prefixo NEXT_PUBLIC_ são incluídas no bundle do cliente e expostas publicamente.',
    impact: 'Secrets como API keys, tokens de banco de dados ficam expostos no frontend.',
    remediation: 'Use NEXT_PUBLIC_ apenas para valores não sensíveis. Acesse secrets somente em API routes ou getServerSideProps.',
    safeExample: '# .env.local\n# Nunca:\n# NEXT_PUBLIC_SECRET_KEY=...\n# Correto:\nSECRET_KEY=... # só no servidor',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /NEXT_PUBLIC_(?:SECRET|KEY|TOKEN|PASSWORD|PRIVATE|DATABASE|SUPABASE_SERVICE)/i,
    ],
    fileExtensions: ['.env', '.env.local', '.env.production', '.jsx', '.tsx'],
  },
  {
    id: 'REACT_007',
    title: 'sessionStorage com token de autenticação',
    category: 'React/Frontend',
    severity: 'medium',
    description: 'sessionStorage é vulnerável a XSS assim como localStorage.',
    impact: 'Scripts injetados podem roubar tokens de sessão.',
    remediation: 'Use cookies HttpOnly para tokens de autenticação.',
    safeExample: '// Configure cookie HttpOnly no backend:\nres.cookie("session", token, { httpOnly: true, secure: true });',
    reference: 'OWASP A07:2021 - Identification and Authentication Failures',
    patterns: [
      /sessionStorage\.setItem\(["'`][^"'`]*(?:token|jwt|auth|session)[^"'`]*["'`]/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts'],
  },
  {
    id: 'REACT_008',
    title: 'Falta de sanitização em conteúdo dinâmico',
    category: 'React/Frontend',
    severity: 'medium',
    description: 'Renderização de HTML ou texto vindo de API ou usuário sem sanitização prévia.',
    impact: 'Possibilidade de XSS stored ou reflected.',
    remediation: 'Sanitize todo conteúdo externo com DOMPurify antes de renderizar.',
    safeExample: "import DOMPurify from 'dompurify';\nconst clean = DOMPurify.sanitize(dirtyHtml);",
    reference: 'OWASP A03:2021 - Injection (XSS)',
    patterns: [
      /\{[^}]*(?:html|content|markup|body)\s*\}/i,
    ],
    fileExtensions: ['.jsx', '.tsx'],
  },
];
