import { FileRule } from '../types';

export const secretsRules: FileRule[] = [
  {
    id: 'SECRET_001',
    title: 'Hardcoded API Key detectada',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API foi encontrada hardcoded no código-fonte.',
    impact: 'Vazamento da chave permite acesso não autorizado a serviços externos, custos inesperados e comprometimento de dados.',
    remediation: 'Mova a chave para variável de ambiente. Nunca versione secrets.',
    safeExample: 'const apiKey = process.env.API_KEY;\nif (!apiKey) throw new Error("API_KEY not configured");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:api[_-]?key|apikey)\s*[=:]\s*["'`][A-Za-z0-9+\/=_\-]{16,}["'`]/i,
      /AIza[0-9A-Za-z\-_]{35}/,
      /AKIA[0-9A-Z]{16}/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py', '.php', '.rb', '.go', '.java', '.env', '.yaml', '.yml', '.json'],
  },
  {
    id: 'SECRET_002',
    title: 'Chave privada no código-fonte',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave privada (RSA, EC, DSA) foi encontrada no código-fonte ou arquivo de configuração.',
    impact: 'Comprometimento total de criptografia, possibilidade de impersonação, acesso a sistemas seguros.',
    remediation: 'Remova imediatamente a chave, revogue-a e gere uma nova. Use cofre de secrets (Vault, AWS Secrets Manager).',
    safeExample: '# Carregue a chave de um cofre:\nconst privateKey = process.env.PRIVATE_KEY?.replace(/\\\\n/g, "\\n");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /-----BEGIN\s+(?:RSA |EC |DSA )?PRIVATE KEY-----/,
      /-----BEGIN OPENSSH PRIVATE KEY-----/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.pem', '.key', '.p12', '.json', '.yaml', '.yml', '.env'],
  },
  {
    id: 'SECRET_003',
    title: 'JWT secret fraco ou hardcoded',
    category: 'Secrets',
    severity: 'high',
    description: 'Um JWT secret curto, fraco ou hardcoded foi detectado.',
    impact: 'Atacantes podem forjar tokens JWT e obter acesso não autorizado a qualquer conta.',
    remediation: 'Use um secret aleatório de pelo menos 256 bits armazenado em variável de ambiente.',
    safeExample: 'const jwtSecret = process.env.JWT_SECRET;\n// Gere com: openssl rand -hex 64',
    reference: 'OWASP A07:2021 - Identification and Authentication Failures',
    patterns: [
      /jwt\.sign\([^,]+,\s*["'`](?:secret|password|123|test|dev|myapp|change)[^"'`]*["'`]/i,
      /JWT_SECRET\s*=\s*["'`](?!process\.env)[A-Za-z0-9]{1,20}["'`]/i,
      /(?:jwtSecret|jwt_secret|JWT_SECRET)\s*[:=]\s*["'`][a-z0-9_]{1,20}["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.env'],
  },
  {
    id: 'SECRET_004',
    title: 'Arquivo .env versionado no repositório',
    category: 'Secrets',
    severity: 'critical',
    description: 'Um arquivo .env contendo variáveis sensíveis foi versionado no repositório.',
    impact: 'Todos os secrets definidos neste arquivo ficam expostos a qualquer pessoa com acesso ao repositório.',
    remediation: 'Adicione .env ao .gitignore imediatamente. Use .env.example com valores falsos. Rotacione todas as credenciais.',
    safeExample: '# .gitignore\n.env\n.env.local\n.env.production\n*.env',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /^(?:DATABASE_URL|API_KEY|SECRET_KEY|JWT_SECRET|PRIVATE_KEY|PASSWORD)\s*=/m,
    ],
    fileNamePatterns: [/^\.env(\.[a-z]+)?$/],
  },
  {
    id: 'SECRET_005',
    title: 'Firebase Service Account exposto',
    category: 'Secrets',
    severity: 'critical',
    description: 'Credenciais de conta de serviço do Firebase/Google Cloud foram encontradas no código.',
    impact: 'Acesso irrestrito ao Firebase Admin SDK, podendo ler/escrever qualquer dado do projeto.',
    remediation: 'Remova imediatamente, revogue a chave no console Firebase/GCP, e use variável de ambiente.',
    safeExample: 'const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON || "{}");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /"type"\s*:\s*"service_account"/,
      /serviceAccountKey\.json/i,
      /firebase-adminsdk[^"']*/i,
    ],
    fileExtensions: ['.json', '.js', '.ts', '.env'],
  },
  {
    id: 'SECRET_006',
    title: 'Exchange API Key (Binance/MEXC/Kraken) exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API de exchange de criptomoedas foi encontrada no código.',
    impact: 'Acesso total à conta da exchange: saques, operações, leitura de saldo.',
    remediation: 'Revogue imediatamente a chave. Armazene em variável de ambiente. Use permissões mínimas necessárias.',
    safeExample: 'const apiKey = process.env.EXCHANGE_API_KEY;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:binance|mexc|kraken|coinbase|ftx)[_-]?(?:api[_-]?key|secret)\s*[:=]\s*["'`][A-Za-z0-9]{20,}["'`]/i,
      /(?:BINANCE|MEXC|KRAKEN)_(?:API_KEY|SECRET)\s*=\s*["']?[A-Za-z0-9]{20,}/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.env'],
  },
  {
    id: 'SECRET_007',
    title: 'Database URL com credenciais exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma URL de conexão de banco de dados contendo usuário e senha foi encontrada no código.',
    impact: 'Acesso direto ao banco de dados, possibilidade de exfiltração ou destruição de dados.',
    remediation: 'Mova a DATABASE_URL para variável de ambiente. Use .env.example sem senha real.',
    safeExample: 'const db = process.env.DATABASE_URL; // postgresql://user:pass@host/db',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^"'\s]+:[^"'\s]+@[^"'\s]+/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.env', '.yaml', '.yml'],
  },
  {
    id: 'SECRET_008',
    title: 'Webhook secret exposto',
    category: 'Secrets',
    severity: 'high',
    description: 'Um secret de webhook (Stripe, GitHub, Discord etc.) foi encontrado no código.',
    impact: 'Atacantes podem forjar eventos de webhook e manipular a lógica de negócio.',
    remediation: 'Mova o webhook secret para variável de ambiente e valide a assinatura de cada evento.',
    safeExample: 'const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:webhook[_-]?secret|WEBHOOK_SECRET)\s*[:=]\s*["'`][A-Za-z0-9+\/=_\-]{16,}["'`]/i,
      /whsec_[A-Za-z0-9+\/=]{32,}/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.env'],
  },
  {
    id: 'SECRET_009',
    title: 'Mnemônico / Seed Phrase exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma seed phrase ou mnemônico de carteira crypto foi encontrado no código.',
    impact: 'Acesso total e irreversível à carteira. Todos os ativos podem ser roubados.',
    remediation: 'Remova imediatamente. Transfira todos os fundos para carteira nova. Nunca armazene seed phrase em código.',
    safeExample: '// Nunca armazene seed phrase em código.\n// Use hardware wallet ou cofre de secrets.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:mnemonic|seed[_-]?phrase|seed[_-]?words)\s*[:=]\s*["'`][a-z]+(?:\s+[a-z]+){11,}["'`]/i,
      /["'`](?:abandon|ability|able|about|above|absent)\s+(?:[a-z]+\s+){10,}[a-z]+["'`]/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.json', '.env'],
  },
  {
    id: 'SECRET_010',
    title: 'Token sensível no código frontend',
    category: 'Secrets',
    severity: 'high',
    description: 'Um token de autenticação ou API key foi encontrado em código que será exposto ao navegador.',
    impact: 'Qualquer usuário da aplicação pode inspecionar o código e obter o token.',
    remediation: 'Nunca inclua tokens privados em código frontend. Use variáveis de servidor e proxy.',
    safeExample: '// Frontend deve chamar seu backend, que usa o token do lado servidor:\nconst data = await fetch("/api/secure-data");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:token|secret|apiKey)\s*[:=]\s*["'`][A-Za-z0-9+\/=_\-]{20,}["'`]/i,
      /Authorization:\s*["'`]Bearer\s+[A-Za-z0-9+\/=_\-]{20,}["'`]/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts', '.vue'],
  },
  {
    id: 'SECRET_011',
    title: 'Chaves Stripe/Mercado Pago expostas',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API de pagamento (Stripe, Mercado Pago) foi encontrada no código.',
    impact: 'Uso fraudulento da conta de pagamento, cobranças não autorizadas, acesso a dados de clientes.',
    remediation: 'Revogue e regenere a chave imediatamente. Use sempre do lado servidor.',
    safeExample: 'const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /sk_live_[A-Za-z0-9]{24,}/,
      /sk_test_[A-Za-z0-9]{24,}/,
      /APP_USR-[0-9]+-[0-9]+-[A-Za-z0-9-]+/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.env'],
  },
  {
    id: 'SECRET_012',
    title: 'GitHub / GitLab token exposto',
    category: 'Secrets',
    severity: 'critical',
    description: 'Um Personal Access Token do GitHub ou GitLab foi encontrado no código.',
    impact: 'Acesso ao repositório, possibilidade de exfiltrar código, push malicioso, acesso a outros repositórios.',
    remediation: 'Revogue o token imediatamente no GitHub/GitLab. Use secrets gerenciados em CI/CD.',
    safeExample: 'const ghToken = process.env.GITHUB_TOKEN;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /gh[pousr]_[A-Za-z0-9]{36,}/,
      /glpat-[A-Za-z0-9_\-]{20,}/,
      /github[_-]?token\s*[:=]\s*["'`][A-Za-z0-9_]{20,}["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.yml', '.yaml', '.env', '.sh'],
  },
  {
    id: 'SECRET_013',
    title: 'Credencial de nuvem (AWS/GCP/Azure) exposta',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'high',
    description: 'Uma credencial de provedor de nuvem (AWS Access Key, GCP API Key/service account ou Azure Storage Account Key) foi encontrada no código.',
    impact: 'Acesso à infraestrutura de nuvem da organização: criação/destruição de recursos, exfiltração de buckets, custos abusivos e movimentação lateral entre serviços.',
    attackScenarioDefensive: 'Um atacante que obtém a Access Key e o Secret da AWS pode assumir a identidade do projeto, listar buckets S3, ler dados sensíveis e provisionar instâncias para mineração, gerando custos elevados antes da detecção.',
    remediation: 'Revogue e rotacione imediatamente a credencial no console do provedor. Use IAM roles/Workload Identity em vez de chaves estáticas e armazene segredos em cofre (AWS Secrets Manager, GCP Secret Manager, Azure Key Vault).',
    safeExample: '// Use a cadeia de credenciais padrão (IAM role / Workload Identity):\nconst client = new S3Client({ region: process.env.AWS_REGION });',
    testSuggestion: 'Crie um arquivo com AKIAIOSFODNN7EXAMPLE e aws_secret_access_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" e confirme que a regra dispara.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/,
      /aws_secret_access_key\s*=\s*["'`]?[A-Za-z0-9\/+]{40}["'`]?/i,
      /AIza[0-9A-Za-z\-_]{35}/,
      /"private_key_id"\s*:\s*"[a-f0-9]{40}"/,
      /DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+\/=]{40,}/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.rb', '.go', '.java', '.json', '.yaml', '.yml', '.env', '.tf', '.sh'],
  },
  {
    id: 'SECRET_014',
    title: 'Chave de provedor de IA/LLM (OpenAI/Anthropic/HuggingFace) exposta',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'high',
    description: 'Uma chave de API de provedor de IA/LLM (OpenAI, Anthropic ou HuggingFace) foi encontrada no código.',
    impact: 'Uso não autorizado da conta de IA, gerando custos potencialmente altos por consumo de tokens e acesso a modelos privados ou dados de fine-tuning.',
    attackScenarioDefensive: 'Um atacante que captura uma chave OpenAI ou Anthropic pode disparar milhares de requisições caras na conta da vítima, esgotando cotas e acumulando faturas significativas antes de a chave ser revogada.',
    remediation: 'Revogue a chave imediatamente no painel do provedor e gere uma nova. Mantenha chaves apenas no lado servidor, em variáveis de ambiente, e nunca em código frontend ou versionado.',
    safeExample: 'const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });',
    testSuggestion: 'Adicione uma string sk-ant-api03- seguida de 80+ caracteres e verifique que a detecção ocorre.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /\bsk-(?:proj|svcacct|admin)-[A-Za-z0-9_-]{20,}T3BlbkFJ[A-Za-z0-9_-]{20,}\b/,
      /\bsk-[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}\b/,
      /\bsk-ant-api03-[A-Za-z0-9_-]{80,}\b/,
      /\bhf_[A-Za-z0-9]{34,}\b/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py', '.rb', '.go', '.java', '.env', '.json'],
  },
  {
    id: 'SECRET_015',
    title: 'Token de repositório/registro (GitHub/GitLab/npm/PyPI) exposto',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'high',
    description: 'Um token de acesso a repositório de código ou registro de pacotes (GitHub, GitLab, npm ou PyPI) foi encontrado no código.',
    impact: 'Acesso a repositórios privados e à publicação de pacotes, permitindo exfiltração de código, push malicioso e ataques de cadeia de suprimentos.',
    attackScenarioDefensive: 'Com um token npm vazado, um atacante pode publicar uma versão maliciosa de um pacote controlado pela organização, distribuindo código comprometido a todos os consumidores dele.',
    remediation: 'Revogue o token imediatamente no provedor correspondente. Use tokens de escopo mínimo e curta validade, e gerencie-os via secrets de CI/CD em vez de hardcoded.',
    safeExample: 'const token = process.env.GITHUB_TOKEN; // injetado pelo CI, escopo mínimo',
    testSuggestion: 'Inclua um token glpat- com 20+ caracteres ou um npm_ com 36 caracteres e confirme o alerta.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /\bgh[pousr]_[A-Za-z0-9]{36,}\b/,
      /\bgithub_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}\b/,
      /\bglpat-[A-Za-z0-9_-]{20,}\b/,
      /\bnpm_[A-Za-z0-9]{36}\b/,
      /\bpypi-AgEIcHlwaS[A-Za-z0-9_-]{50,}\b/,
    ],
    fileExtensions: ['.js', '.ts', '.yml', '.yaml', '.env', '.sh', '.npmrc', '.json'],
  },
  {
    id: 'SECRET_016',
    title: 'Chave de serviço SaaS/comunicação (Slack/Twilio/SendGrid/Mailgun/Telegram/Discord) exposta',
    category: 'Secrets',
    severity: 'high',
    confidence: 'high',
    description: 'Uma chave ou token de serviço SaaS de comunicação (Slack, Twilio, SendGrid, Mailgun, Telegram ou webhook Discord) foi encontrada no código.',
    impact: 'Envio de mensagens, e-mails e SMS em nome da organização, possibilitando phishing, spam, fraude e custos por uso indevido.',
    attackScenarioDefensive: 'Um atacante de posse de uma chave SendGrid ou de um Auth Token Twilio pode disparar campanhas de phishing usando os domínios verificados da vítima, ganhando credibilidade e contornando filtros de spam.',
    remediation: 'Revogue e regenere a chave no painel do serviço. Restrinja IPs/escopos quando suportado e mantenha o segredo apenas no servidor, em variável de ambiente.',
    safeExample: 'const sg = sgMail.setApiKey(process.env.SENDGRID_API_KEY);',
    testSuggestion: 'Adicione um token Slack xoxb- com 10+ caracteres e confirme a detecção.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /\bxox[baprse]-[A-Za-z0-9-]{10,}\b/,
      /\bSK[0-9a-fA-F]{32}\b/,
      /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/,
      /\bkey-[0-9a-f]{32}\b/,
      /\b\d{8,10}:[A-Za-z0-9_-]{35}\b/,
      /discord(?:app)?\.com\/api\/webhooks\/\d{17,20}\/[A-Za-z0-9_-]{60,}/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.rb', '.go', '.env', '.json', '.yaml', '.yml'],
  },
  {
    id: 'SECRET_017',
    title: 'Chave de hospedagem/infraestrutura (Stripe/DigitalOcean/Cloudflare/Vercel/Netlify) exposta',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'medium',
    description: 'Uma chave de plataforma de hospedagem ou infraestrutura (Stripe restricted/publishable live, DigitalOcean, Cloudflare, Vercel ou Netlify) foi encontrada no código.',
    impact: 'Controle sobre recursos de hospedagem, DNS e/ou pagamentos, permitindo derrubar serviços, redirecionar tráfego e manipular cobranças.',
    attackScenarioDefensive: 'Com um token DigitalOcean ou Cloudflare vazado, um atacante pode alterar registros DNS para sequestrar domínios, redirecionando usuários para infraestrutura maliciosa controlada por ele.',
    remediation: 'Revogue e regenere o token na plataforma correspondente. Use tokens de escopo mínimo e mantenha-os em cofre de secrets, nunca versionados.',
    safeExample: 'const cf = new Cloudflare({ apiToken: process.env.CLOUDFLARE_API_TOKEN });',
    testSuggestion: 'Inclua um token dop_v1_ com 64 caracteres hexadecimais e verifique o alerta.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /\brk_live_[A-Za-z0-9]{24,}\b/,
      /\bpk_live_[A-Za-z0-9]{24,}\b/,
      /\bdop_v1_[a-f0-9]{64}\b/,
      /\b(?:vercel|netlify)[_-]?(?:token|api[_-]?key)\s*[:=]\s*["'`][A-Za-z0-9_-]{20,}["'`]/i,
      /\bcf-[A-Za-z0-9]{40,}\b|cloudflare[_-]?api[_-]?token\s*[:=]\s*["'`][A-Za-z0-9_-]{40}["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.env', '.json', '.yaml', '.yml', '.tf'],
  },
  {
    id: 'SECRET_018',
    title: 'Supabase service_role / JWT de alto privilégio exposto',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'medium',
    description: 'Um JWT do Supabase com papel service_role (ou outro JWT de alto privilégio) foi encontrado no código.',
    impact: 'A chave service_role ignora as políticas de Row Level Security, concedendo acesso administrativo total ao banco de dados Supabase.',
    attackScenarioDefensive: 'Se a chave service_role estiver embutida no frontend, qualquer visitante pode extraí-la do bundle e ler ou modificar toda a base de dados, contornando completamente o RLS configurado.',
    remediation: 'Nunca exponha a chave service_role no cliente. Revogue/rotacione-a no painel Supabase, use apenas no servidor e prefira a chave anon (com RLS) no frontend.',
    safeExample: 'const supabase = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY); // só no servidor',
    testSuggestion: 'Cole um JWT cujo payload contenha o papel service_role e confirme a detecção.',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]*(?:c2VydmljZV9yb2xl|InNlcnZpY2Vfcm9sZSI)[A-Za-z0-9_-]*\.[A-Za-z0-9_-]{10,}/,
      /eyJ[A-Za-z0-9_-]{15,}\.eyJ[A-Za-z0-9_-]{40,}\.[A-Za-z0-9_-]{20,}/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.vue', '.env', '.json'],
  },
  {
    id: 'SECRET_019',
    title: 'Connection string com senha exposta',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'high',
    description: 'Uma string de conexão contendo usuário e senha (PostgreSQL, MySQL, MariaDB, MongoDB, Redis ou AMQP) foi encontrada no código.',
    impact: 'Acesso direto ao serviço de dados/mensageria, permitindo exfiltração, alteração ou destruição de dados e interrupção de serviços.',
    attackScenarioDefensive: 'Um atacante que encontra a connection string com senha pode conectar-se diretamente ao banco de produção, exfiltrar tabelas inteiras de usuários e apagar registros, sem passar pela camada de aplicação.',
    remediation: 'Mova a connection string para variável de ambiente e rotacione a senha. Restrinja o acesso por rede/IP e use credenciais de privilégio mínimo.',
    safeExample: 'const url = process.env.DATABASE_URL; // postgresql://user:****@host/db',
    testSuggestion: 'Use postgres://admin:S3nh4Real@db.example.com:5432/app e confirme que dispara, e que placeholders como ${DB_PASS} não disparam.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:postgres(?:ql)?|mysql|mariadb|mongodb(?:\+srv)?|redis|rediss|amqps?):\/\/[^:@\s"'`]+:[^@\s"'`]+@[^\s"'`\/]+/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.rb', '.go', '.java', '.env', '.yaml', '.yml', '.json'],
  },
  {
    id: 'SECRET_020',
    title: 'Chave privada PEM (todas as variantes) exposta',
    category: 'Secrets',
    severity: 'critical',
    confidence: 'high',
    description: 'Um bloco de chave privada em formato PEM (RSA, EC, DSA, OPENSSH, PGP ou ENCRYPTED) foi encontrado no código.',
    impact: 'Comprometimento de criptografia e identidade: descriptografia de tráfego, impersonação de servidores/usuários e acesso a sistemas protegidos por chave.',
    attackScenarioDefensive: 'Com a chave privada TLS de um servidor, um atacante posicionado na rede pode descriptografar comunicações interceptadas ou montar um servidor falso indistinguível do legítimo para roubar credenciais.',
    remediation: 'Remova a chave do repositório, revogue-a e gere um novo par. Armazene chaves privadas em HSM ou cofre de secrets e nunca as versione.',
    safeExample: '// Carregue a chave de um cofre em runtime:\nconst key = await vault.read("tls/private_key");',
    testSuggestion: 'Adicione uma linha "-----BEGIN OPENSSH PRIVATE KEY-----" e confirme a detecção para essa variante.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY(?: BLOCK)?-----/,
    ],
    fileExtensions: ['.js', '.ts', '.pem', '.key', '.p12', '.ppk', '.json', '.yaml', '.yml', '.env'],
  },
];
