import { FileRule } from '../types';

export const secretsRules: FileRule[] = [
  {
    id: 'SECRET_001',
    title: 'Hardcoded API Key detectada',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API foi encontrada hardcoded no código-fonte.',
    impact: 'Vazamento da chave permite acesso não autorizado a serviços externos, custos inesperados e comprometimento de dados.',
    remediation: 'Mova a chave para variável de ambiente. Nunca versione secrets.',
    safeExample: 'const apiKey = process.env.API_KEY;\nif (!apiKey) throw new Error("API_KEY not configured");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:api[_-]?key|apikey)\s*[=:]\s*["'`][A-Za-z0-9+\/=_\-]{16,}["'`]/i,
      /AIza[0-9A-Za-z\-_]{35}/,
      /AKIA[0-9A-Z]{16}/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py', '.php', '.rb', '.go', '.java', '.env', '.yaml', '.yml', '.json'],
  },
  {
    id: 'SECRET_002',
    title: 'Chave privada no código-fonte',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave privada (RSA, EC, DSA) foi encontrada no código-fonte ou arquivo de configuração.',
    impact: 'Comprometimento total de criptografia, possibilidade de impersonação, acesso a sistemas seguros.',
    remediation: 'Remova imediatamente a chave, revogue-a e gere uma nova. Use cofre de secrets (Vault, AWS Secrets Manager).',
    safeExample: '# Carregue a chave de um cofre:\nconst privateKey = process.env.PRIVATE_KEY?.replace(/\\\\n/g, "\\n");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /-----BEGIN\s+(?:RSA |EC |DSA )?PRIVATE KEY-----/,
      /-----BEGIN OPENSSH PRIVATE KEY-----/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.pem', '.key', '.p12', '.json', '.yaml', '.yml', '.env'],
  },
  {
    id: 'SECRET_003',
    title: 'JWT secret fraco ou hardcoded',
    category: 'Secrets',
    severity: 'high',
    description: 'Um JWT secret curto, fraco ou hardcoded foi detectado.',
    impact: 'Atacantes podem forjar tokens JWT e obter acesso não autorizado a qualquer conta.',
    remediation: 'Use um secret aleatório de pelo menos 256 bits armazenado em variável de ambiente.',
    safeExample: 'const jwtSecret = process.env.JWT_SECRET;\n// Gere com: openssl rand -hex 64',
    reference: 'OWASP A07:2021 - Identification and Authentication Failures',
    patterns: [
      /jwt\.sign\([^,]+,\s*["'`](?:secret|password|123|test|dev|myapp|change)[^"'`]*["'`]/i,
      /JWT_SECRET\s*=\s*["'`](?!process\.env)[A-Za-z0-9]{1,20}["'`]/i,
      /(?:jwtSecret|jwt_secret|JWT_SECRET)\s*[:=]\s*["'`][a-z0-9_]{1,20}["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.env'],
  },
  {
    id: 'SECRET_004',
    title: 'Arquivo .env versionado no repositório',
    category: 'Secrets',
    severity: 'critical',
    description: 'Um arquivo .env contendo variáveis sensíveis foi versionado no repositório.',
    impact: 'Todos os secrets definidos neste arquivo ficam expostos a qualquer pessoa com acesso ao repositório.',
    remediation: 'Adicione .env ao .gitignore imediatamente. Use .env.example com valores falsos. Rotacione todas as credenciais.',
    safeExample: '# .gitignore\n.env\n.env.local\n.env.production\n*.env',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /^(?:DATABASE_URL|API_KEY|SECRET_KEY|JWT_SECRET|PRIVATE_KEY|PASSWORD)\s*=/m,
    ],
    fileNamePatterns: [/^\.env(\.[a-z]+)?$/],
  },
  {
    id: 'SECRET_005',
    title: 'Firebase Service Account exposto',
    category: 'Secrets',
    severity: 'critical',
    description: 'Credenciais de conta de serviço do Firebase/Google Cloud foram encontradas no código.',
    impact: 'Acesso irrestrito ao Firebase Admin SDK, podendo ler/escrever qualquer dado do projeto.',
    remediation: 'Remova imediatamente, revogue a chave no console Firebase/GCP, e use variável de ambiente.',
    safeExample: 'const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON || "{}");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /"type"\s*:\s*"service_account"/,
      /serviceAccountKey\.json/i,
      /firebase-adminsdk[^"']*/i,
    ],
    fileExtensions: ['.json', '.js', '.ts', '.env'],
  },
  {
    id: 'SECRET_006',
    title: 'Exchange API Key (Binance/MEXC/Kraken) exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API de exchange de criptomoedas foi encontrada no código.',
    impact: 'Acesso total à conta da exchange: saques, operações, leitura de saldo.',
    remediation: 'Revogue imediatamente a chave. Armazene em variável de ambiente. Use permissões mínimas necessárias.',
    safeExample: 'const apiKey = process.env.EXCHANGE_API_KEY;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:binance|mexc|kraken|coinbase|ftx)[_-]?(?:api[_-]?key|secret)\s*[:=]\s*["'`][A-Za-z0-9]{20,}["'`]/i,
      /(?:BINANCE|MEXC|KRAKEN)_(?:API_KEY|SECRET)\s*=\s*["']?[A-Za-z0-9]{20,}/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.env'],
  },
  {
    id: 'SECRET_007',
    title: 'Database URL com credenciais exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma URL de conexão de banco de dados contendo usuário e senha foi encontrada no código.',
    impact: 'Acesso direto ao banco de dados, possibilidade de exfiltração ou destruição de dados.',
    remediation: 'Mova a DATABASE_URL para variável de ambiente. Use .env.example sem senha real.',
    safeExample: 'const db = process.env.DATABASE_URL; // postgresql://user:pass@host/db',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^"'\s]+:[^"'\s]+@[^"'\s]+/i,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.env', '.yaml', '.yml'],
  },
  {
    id: 'SECRET_008',
    title: 'Webhook secret exposto',
    category: 'Secrets',
    severity: 'high',
    description: 'Um secret de webhook (Stripe, GitHub, Discord etc.) foi encontrado no código.',
    impact: 'Atacantes podem forjar eventos de webhook e manipular a lógica de negócio.',
    remediation: 'Mova o webhook secret para variável de ambiente e valide a assinatura de cada evento.',
    safeExample: 'const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:webhook[_-]?secret|WEBHOOK_SECRET)\s*[:=]\s*["'`][A-Za-z0-9+\/=_\-]{16,}["'`]/i,
      /whsec_[A-Za-z0-9+\/=]{32,}/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.env'],
  },
  {
    id: 'SECRET_009',
    title: 'Mnemônico / Seed Phrase exposta',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma seed phrase ou mnemônico de carteira crypto foi encontrado no código.',
    impact: 'Acesso total e irreversível à carteira. Todos os ativos podem ser roubados.',
    remediation: 'Remova imediatamente. Transfira todos os fundos para carteira nova. Nunca armazene seed phrase em código.',
    safeExample: '// Nunca armazene seed phrase em código.\n// Use hardware wallet ou cofre de secrets.',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:mnemonic|seed[_-]?phrase|seed[_-]?words)\s*[:=]\s*["'`][a-z]+(?:\s+[a-z]+){11,}["'`]/i,
      /["'`](?:abandon|ability|able|about|above|absent)\s+(?:[a-z]+\s+){10,}[a-z]+["'`]/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.json', '.env'],
  },
  {
    id: 'SECRET_010',
    title: 'Token sensível no código frontend',
    category: 'Secrets',
    severity: 'high',
    description: 'Um token de autenticação ou API key foi encontrado em código que será exposto ao navegador.',
    impact: 'Qualquer usuário da aplicação pode inspecionar o código e obter o token.',
    remediation: 'Nunca inclua tokens privados em código frontend. Use variáveis de servidor e proxy.',
    safeExample: '// Frontend deve chamar seu backend, que usa o token do lado servidor:\nconst data = await fetch("/api/secure-data");',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /(?:token|secret|apiKey)\s*[:=]\s*["'`][A-Za-z0-9+\/=_\-]{20,}["'`]/i,
      /Authorization:\s*["'`]Bearer\s+[A-Za-z0-9+\/=_\-]{20,}["'`]/i,
    ],
    fileExtensions: ['.jsx', '.tsx', '.js', '.ts', '.vue'],
  },
  {
    id: 'SECRET_011',
    title: 'Chaves Stripe/Mercado Pago expostas',
    category: 'Secrets',
    severity: 'critical',
    description: 'Uma chave de API de pagamento (Stripe, Mercado Pago) foi encontrada no código.',
    impact: 'Uso fraudulento da conta de pagamento, cobranças não autorizadas, acesso a dados de clientes.',
    remediation: 'Revogue e regenere a chave imediatamente. Use sempre do lado servidor.',
    safeExample: 'const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /sk_live_[A-Za-z0-9]{24,}/,
      /sk_test_[A-Za-z0-9]{24,}/,
      /APP_USR-[0-9]+-[0-9]+-[A-Za-z0-9-]+/,
    ],
    fileExtensions: ['.js', '.ts', '.py', '.php', '.env'],
  },
  {
    id: 'SECRET_012',
    title: 'GitHub / GitLab token exposto',
    category: 'Secrets',
    severity: 'critical',
    description: 'Um Personal Access Token do GitHub ou GitLab foi encontrado no código.',
    impact: 'Acesso ao repositório, possibilidade de exfiltrar código, push malicioso, acesso a outros repositórios.',
    remediation: 'Revogue o token imediatamente no GitHub/GitLab. Use secrets gerenciados em CI/CD.',
    safeExample: 'const ghToken = process.env.GITHUB_TOKEN;',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /gh[pousr]_[A-Za-z0-9]{36,}/,
      /glpat-[A-Za-z0-9_\-]{20,}/,
      /github[_-]?token\s*[:=]\s*["'`][A-Za-z0-9_]{20,}["'`]/i,
    ],
    fileExtensions: ['.js', '.ts', '.yml', '.yaml', '.env', '.sh'],
  },
];
