import { FileRule } from '../types';

export const supabaseRules: FileRule[] = [
  {
    id: 'SUPA_001',
    title: 'Supabase service_role key no frontend',
    category: 'Supabase',
    severity: 'critical',
    confidence: 'high',
    description: 'A service_role key do Supabase tem acesso de administrador e bypassa RLS. Encontrada em código do cliente.',
    impact: 'Qualquer usuário pode obter acesso de admin ao banco, ler/escrever qualquer dado, bypassar todas as políticas RLS.',
    attackScenarioDefensive: 'Usuário inspeciona o bundle JS no navegador, extrai a service_role key e usa o Supabase SDK diretamente para ler dados de todos os usuários.',
    remediation: 'Remova service_role do frontend. Use somente SUPABASE_ANON_KEY no cliente. A service_role_key deve ficar apenas no backend (servidor), em variável de ambiente.',
    safeExample: '// Frontend: use apenas a anon key\nconst supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);\n// Backend: use service_role somente no servidor\nconst adminClient = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY);',
    testSuggestion: 'Verifique que o bundle de produção não contém a string "service_role". Use: grep -r "service_role" ./dist',
    reference: 'Supabase Security Docs - Service Role Key',
    patterns: [
      /(?:service_role|SERVICE_ROLE).*["'`]ey[A-Za-z0-9._-]{20,}/i,
      /SUPABASE_SERVICE(?:_ROLE)?_KEY\s*=\s*["']?ey[A-Za-z0-9._-]{20,}/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.env'],
  },
  {
    id: 'SUPA_002',
    title: 'Supabase sem Row Level Security detectada',
    category: 'Supabase',
    severity: 'high',
    confidence: 'medium',
    description: 'Consulta ao Supabase sem menção aparente a RLS ou filtro por user_id, em tabela potencialmente sensível.',
    impact: 'Se RLS não estiver ativo, qualquer usuário autenticado pode acessar dados de outros usuários.',
    attackScenarioDefensive: 'Usuário autenticado faz query direta via Supabase SDK sem filtros e acessa registros de outros usuários.',
    remediation: 'Ative RLS em todas as tabelas: ALTER TABLE nome ENABLE ROW LEVEL SECURITY; Crie políticas por usuário: CREATE POLICY "user_policy" ON tabela FOR ALL USING (auth.uid() = user_id);',
    safeExample: '-- SQL no Supabase:\nALTER TABLE orders ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "users_own_orders"\n  ON orders FOR ALL\n  USING (auth.uid() = user_id);',
    testSuggestion: 'No painel Supabase, vá em Database > Tables e verifique se RLS está ativo (cadeado fechado) em cada tabela.',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /supabase\.from\(["'`][^"'`]+["'`]\)\s*\.select\(["'`]\*["'`]\)/i,
      /supabase\.from\(["'`][^"'`]+["'`]\)\.(?:select|delete|update)\(/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'SUPA_003',
    title: 'Supabase anon key exposta em variável de ambiente',
    category: 'Supabase',
    severity: 'low',
    confidence: 'high',
    description: 'A anon key do Supabase está exposta — isso é normal para clientes, mas deve ser verificada com RLS ativo.',
    impact: 'Baixo por si só, mas crítico se RLS não estiver configurado corretamente.',
    attackScenarioDefensive: 'Com anon key + RLS inativo, qualquer pessoa pode acessar dados do banco sem autenticação.',
    remediation: 'A anon key pode ser pública, mas garanta que RLS esteja ativo em todas as tabelas. Monitore uso suspeito no painel Supabase.',
    safeExample: '// Aceitável - anon key é pública por design:\nconst supabase = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);\n// Garanta RLS ativo em todas as tabelas!',
    reference: 'Supabase Security Docs - Keys and Authentication',
    patterns: [
      /NEXT_PUBLIC_SUPABASE_ANON_KEY\s*=\s*["']?ey[A-Za-z0-9._-]{30,}/i,
      /VITE_SUPABASE_ANON_KEY\s*=\s*["']?ey[A-Za-z0-9._-]{30,}/i,
    ],
    fileExtensions: ['.env', '.env.local', '.env.example'],
  },
  {
    id: 'SUPA_004',
    title: 'Supabase storage bucket potencialmente público',
    category: 'Supabase',
    severity: 'medium',
    confidence: 'medium',
    description: 'Código cria ou acessa storage bucket com configuração que pode ser pública.',
    impact: 'Arquivos privados de usuários (documentos, fotos, dados pessoais) acessíveis por qualquer pessoa.',
    attackScenarioDefensive: 'Atacante descobre o nome do bucket e acessa arquivos privados de usuários via URL pública do Supabase Storage.',
    remediation: 'Configure buckets como privados e use signed URLs para acesso controlado.',
    safeExample: "// Gere signed URL com expiração:\nconst { data } = await supabase.storage\n  .from('private-bucket')\n  .createSignedUrl('user-file.pdf', 60); // 60 segundos",
    reference: 'Supabase Storage Security',
    patterns: [
      /\.from\(['"`][^'"`]*['"`]\)\.upload\(/,
      /createBucket\([^)]+public\s*:\s*true/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'SUPA_005',
    title: 'Filtro user_id vindo do cliente Supabase',
    category: 'Supabase',
    severity: 'high',
    confidence: 'medium',
    description: 'Query Supabase filtrando por user_id que pode vir do estado do frontend em vez de auth.uid() no RLS.',
    impact: 'Se RLS não estiver ativo, usuário pode manipular o filtro e acessar dados de outros usuários.',
    attackScenarioDefensive: 'Usuário intercepta a query, muda o user_id para o de outra pessoa e acessa dados privados.',
    remediation: 'Confie apenas no auth.uid() via RLS, não em filtros enviados pelo cliente.',
    safeExample: '-- RLS garante que só o próprio usuário acessa:\nCREATE POLICY "own_data" ON tabela\n  USING (auth.uid() = user_id);\n-- O cliente não precisa filtrar: supabase.from("tabela").select("*");',
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /\.eq\(["'`]user_id["'`],\s*(?:user|session|auth)[\w.]+(?:id|userId)\)/i,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
];
