import { FileRule } from '../types';

export const uploadRules: FileRule[] = [
  {
    id: 'UPLOAD_001',
    title: 'Multer sem fileFilter configurado',
    category: 'Upload',
    severity: 'high',
    description: 'Upload com Multer sem filtro de tipo de arquivo.',
    impact: 'Upload de arquivos executáveis, scripts PHP, webshells e outros tipos perigosos.',
    remediation: 'Configure fileFilter no Multer para validar MIME type e extensão.',
    safeExample: "const upload = multer({\n  fileFilter: (req, file, cb) => {\n    const allowed = ['image/jpeg', 'image/png', 'image/webp'];\n    cb(null, allowed.includes(file.mimetype));\n  }\n});",
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /multer\(\s*\{[^}]*(?:dest|storage)[^}]*\}\s*\)/,
      /multer\(\s*\{\s*dest/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_002',
    title: 'Upload sem limite de tamanho',
    category: 'Upload',
    severity: 'medium',
    description: 'Upload sem limitação de tamanho de arquivo.',
    impact: 'DoS por uploads de arquivos muito grandes. Consumo excessivo de disco/memória.',
    remediation: 'Configure limits.fileSize no Multer.',
    safeExample: "const upload = multer({\n  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB\n  fileFilter: validateFile\n});",
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /multer\s*\(\s*\{(?![^}]*limits)[^}]*\}\s*\)/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_003',
    title: 'Extensão de arquivo não validada',
    category: 'Upload',
    severity: 'high',
    description: 'Upload sem validação de extensão de arquivo permitida.',
    impact: 'Upload de arquivos perigosos: .php, .exe, .sh, .js executável no servidor.',
    remediation: 'Valide a extensão do arquivo e mantenha uma whitelist.',
    safeExample: "const ALLOWED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.pdf'];\nconst ext = path.extname(file.originalname).toLowerCase();\nif (!ALLOWED_EXTENSIONS.includes(ext)) throw new Error('File type not allowed');",
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /req\.file\.originalname/,
      /file\.originalname/,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_004',
    title: 'Path traversal em nome de arquivo',
    category: 'Upload',
    severity: 'critical',
    description: 'Nome original do arquivo usado diretamente no caminho de salvamento.',
    impact: 'Path traversal: sobrescrever arquivos do servidor, incluindo configurações críticas.',
    remediation: 'Use path.basename() e sanitize o nome. Melhor ainda: gere um nome UUID aleatório.',
    safeExample: "import { v4 as uuidv4 } from 'uuid';\nimport path from 'path';\nconst safeFilename = uuidv4() + path.extname(file.originalname);",
    reference: 'OWASP A01:2021 - Broken Access Control',
    patterns: [
      /path\.join\([^)]*originalname[^)]*\)/i,
      /\+\s*(?:file|req\.file)\.originalname/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_005',
    title: 'Upload de SVG sem sanitização',
    category: 'Upload',
    severity: 'high',
    description: 'Arquivos SVG aceitos sem sanitização de conteúdo XML/JavaScript.',
    impact: 'SVG pode conter JavaScript que executa em contexto do domínio quando renderizado diretamente.',
    remediation: 'Sanitize SVGs com DOMPurify (servidor) ou bloqueie SVGs em uploads de usuário.',
    safeExample: "// Sanitizar SVG no backend:\nimport { JSDOM } from 'jsdom';\nimport DOMPurify from 'dompurify';\nconst window = new JSDOM('').window;\nconst purify = DOMPurify(window as any);\nconst clean = purify.sanitize(svgContent);",
    reference: 'OWASP A03:2021 - Injection (XSS)',
    patterns: [
      /["'`]image\/svg\+xml["'`]/,
      /\.svg["'`]\s*,/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_006',
    title: 'Nome original do arquivo usado no storage',
    category: 'Upload',
    severity: 'medium',
    description: 'Nome original do arquivo sendo usado para salvar em disco ou storage.',
    impact: 'Colisão de nomes, sobrescrita de arquivos, path traversal, exposição de informações.',
    remediation: 'Gere nomes únicos (UUID) para todos os arquivos uploaded.',
    safeExample: "const filename = `${uuidv4()}${path.extname(file.originalname)}`;\nawait s3.putObject({ Key: `uploads/${filename}`, Body: file.buffer });",
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /filename\s*:\s*(?:file|req\.file)\.originalname/i,
      /diskStorage.*filename.*originalname/is,
    ],
    fileExtensions: ['.js', '.ts'],
  },
  {
    id: 'UPLOAD_007',
    title: 'Arquivos salvos em pasta pública executável',
    category: 'Upload',
    severity: 'critical',
    description: 'Uploads sendo salvos em pasta public/ acessível diretamente pelo servidor web.',
    impact: 'Se um arquivo executável for uploaded, pode ser acessado e executado via URL.',
    remediation: 'Salve uploads fora da pasta public/. Sirva via endpoint que valida acesso.',
    safeExample: "// Salvar fora do webroot:\nconst uploadDir = path.join(__dirname, '..', '..', 'uploads'); // não em /public\n// Servir via endpoint controlado:\napp.get('/files/:id', auth, serveFile);",
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /dest\s*:\s*["'`](?:\.\/)?public\//i,
      /path\.join\([^)]*['"]public['"]/i,
    ],
    fileExtensions: ['.js', '.ts'],
  },
];
