import { FileRule } from '../types';

export const web3Rules: FileRule[] = [
  {
    id: 'WEB3_001',
    title: 'Private key no frontend',
    category: 'Web3',
    severity: 'critical',
    description: 'Chave privada de wallet crypto encontrada em código frontend.',
    impact: 'Roubo imediato de todos os fundos da carteira.',
    remediation: 'Nunca inclua private keys em código. Use MetaMask, WalletConnect ou hardware wallet.',
    safeExample: '// Use MetaMask/WalletConnect:\nconst provider = new ethers.BrowserProvider(window.ethereum);\nconst signer = await provider.getSigner();',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /privateKey\s*[:=]\s*["'`]0x[0-9a-fA-F]{64}["'`]/,
      /private[_-]?key\s*[:=]\s*["'`][0-9a-fA-F]{64}["'`]/i,
      /new\s+Wallet\s*\(\s*["'`]0x[0-9a-fA-F]{64}/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'WEB3_002',
    title: 'Uso de tx.origin em Solidity',
    category: 'Web3',
    severity: 'high',
    description: 'tx.origin usado para autenticação em contrato Solidity.',
    impact: 'Vulnerável a ataques de phishing. Um contrato malicioso pode fazer chamadas em nome do usuário.',
    remediation: 'Use msg.sender em vez de tx.origin para autenticação.',
    safeExample: 'require(msg.sender == owner, "Not owner"); // Correto\n// Nunca: require(tx.origin == owner)',
    reference: 'SWC-115',
    patterns: [
      /tx\.origin/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_003',
    title: 'delegatecall para endereço controlado pelo usuário',
    category: 'Web3',
    severity: 'critical',
    description: 'delegatecall para endereço que pode ser controlado externamente.',
    impact: 'Execução de código arbitrário no contexto do contrato chamador. Possível roubo de todos os fundos.',
    remediation: 'Evite delegatecall para endereços não confiáveis. Use whitelist de endereços aprovados.',
    safeExample: '// Use apenas endereços verificados em whitelist:\nrequire(whitelist[implementation], "Not whitelisted");\n(bool success,) = implementation.delegatecall(data);',
    reference: 'SWC-112',
    patterns: [
      /\.delegatecall\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_004',
    title: 'Falta de proteção contra reentrancy',
    category: 'Web3',
    severity: 'critical',
    description: 'Função que envia Ether sem ReentrancyGuard ou pattern checks-effects-interactions.',
    impact: 'Ataques de reentrancy podem drenar todos os fundos do contrato (como no hack do DAO).',
    remediation: 'Use ReentrancyGuard do OpenZeppelin ou implemente o pattern checks-effects-interactions.',
    safeExample: 'import "@openzeppelin/contracts/security/ReentrancyGuard.sol";\ncontract Safe is ReentrancyGuard {\n    function withdraw() external nonReentrant {\n        // ...\n    }\n}',
    reference: 'SWC-107',
    patterns: [
      /function\s+withdraw/i,
      /\.call\{value/,
      /\.transfer\(/,
      /\.send\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_005',
    title: 'Approve ilimitado sem aviso ao usuário',
    category: 'Web3',
    severity: 'medium',
    description: 'Código solicita approve de uint256 máximo sem informar o usuário do risco.',
    impact: 'Se o contrato for comprometido, todos os tokens aprovados podem ser roubados.',
    remediation: 'Use approve apenas pelo valor necessário. Informe o usuário claramente. Considere ERC-4626 permit.',
    safeExample: '// Aprove apenas o valor necessário:\nawait token.approve(spender, amountNeeded);\n// Não: approve(spender, ethers.MaxUint256)',
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /approve\s*\([^,]+,\s*(?:ethers\.MaxUint256|2\s*\*\*\s*256|type\(uint256\)\.max|0xffffffff)/i,
    ],
    fileExtensions: ['.sol', '.js', '.ts'],
  },
  {
    id: 'WEB3_006',
    title: 'Owner único sem timelock ou multisig',
    category: 'Web3',
    severity: 'high',
    description: 'Contrato com único owner capaz de executar funções críticas sem timelock.',
    impact: 'Comprometimento da chave do owner ou insider attack pode drenar o protocolo instantaneamente.',
    remediation: 'Use Gnosis Safe (multisig) e timelock para funções administrativas críticas.',
    safeExample: '// Use Governor + Timelock do OpenZeppelin para funções críticas.\nimport "@openzeppelin/contracts/governance/TimelockController.sol";',
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /onlyOwner/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_007',
    title: 'Proxy upgrade sem proteção adequada',
    category: 'Web3',
    severity: 'critical',
    description: 'Padrão de proxy upgradeable sem proteção adequada na função de upgrade.',
    impact: 'Owner pode substituir a implementação por código malicioso a qualquer momento.',
    remediation: 'Use UUPS com acesso restrito + timelock. Considere proxies imutáveis quando possível.',
    safeExample: 'import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";\nfunction _authorizeUpgrade(address) internal override onlyOwner timelocked {}',
    reference: 'SWC-112',
    patterns: [
      /upgradeTo\s*\(/,
      /upgradeToAndCall\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
];
