import { FileRule } from '../types';

export const web3Rules: FileRule[] = [
  {
    id: 'WEB3_001',
    title: 'Private key no frontend',
    category: 'Web3',
    severity: 'critical',
    description: 'Chave privada de wallet crypto encontrada em código frontend.',
    impact: 'Roubo imediato de todos os fundos da carteira.',
    remediation: 'Nunca inclua private keys em código. Use MetaMask, WalletConnect ou hardware wallet.',
    safeExample: '// Use MetaMask/WalletConnect:\nconst provider = new ethers.BrowserProvider(window.ethereum);\nconst signer = await provider.getSigner();',
    reference: 'OWASP A02:2021 - Cryptographic Failures',
    patterns: [
      /privateKey\s*[:=]\s*["'`]0x[0-9a-fA-F]{64}["'`]/,
      /private[_-]?key\s*[:=]\s*["'`][0-9a-fA-F]{64}["'`]/i,
      /new\s+Wallet\s*\(\s*["'`]0x[0-9a-fA-F]{64}/,
    ],
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx'],
  },
  {
    id: 'WEB3_002',
    title: 'Uso de tx.origin em Solidity',
    category: 'Web3',
    severity: 'high',
    description: 'tx.origin usado para autenticação em contrato Solidity.',
    impact: 'Vulnerável a ataques de phishing. Um contrato malicioso pode fazer chamadas em nome do usuário.',
    remediation: 'Use msg.sender em vez de tx.origin para autenticação.',
    safeExample: 'require(msg.sender == owner, "Not owner"); // Correto\n// Nunca: require(tx.origin == owner)',
    reference: 'SWC-115',
    patterns: [
      /tx\.origin/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_003',
    title: 'delegatecall para endereço controlado pelo usuário',
    category: 'Web3',
    severity: 'critical',
    description: 'delegatecall para endereço que pode ser controlado externamente.',
    impact: 'Execução de código arbitrário no contexto do contrato chamador. Possível roubo de todos os fundos.',
    remediation: 'Evite delegatecall para endereços não confiáveis. Use whitelist de endereços aprovados.',
    safeExample: '// Use apenas endereços verificados em whitelist:\nrequire(whitelist[implementation], "Not whitelisted");\n(bool success,) = implementation.delegatecall(data);',
    reference: 'SWC-112',
    patterns: [
      /\.delegatecall\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_004',
    title: 'Falta de proteção contra reentrancy',
    category: 'Web3',
    severity: 'critical',
    description: 'Função que envia Ether sem ReentrancyGuard ou pattern checks-effects-interactions.',
    impact: 'Ataques de reentrancy podem drenar todos os fundos do contrato (como no hack do DAO).',
    remediation: 'Use ReentrancyGuard do OpenZeppelin ou implemente o pattern checks-effects-interactions.',
    safeExample: 'import "@openzeppelin/contracts/security/ReentrancyGuard.sol";\ncontract Safe is ReentrancyGuard {\n    function withdraw() external nonReentrant {\n        // ...\n    }\n}',
    reference: 'SWC-107',
    patterns: [
      /function\s+withdraw/i,
      /\.call\{value/,
      /\.transfer\(/,
      /\.send\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_005',
    title: 'Approve ilimitado sem aviso ao usuário',
    category: 'Web3',
    severity: 'medium',
    description: 'Código solicita approve de uint256 máximo sem informar o usuário do risco.',
    impact: 'Se o contrato for comprometido, todos os tokens aprovados podem ser roubados.',
    remediation: 'Use approve apenas pelo valor necessário. Informe o usuário claramente. Considere ERC-4626 permit.',
    safeExample: '// Aprove apenas o valor necessário:\nawait token.approve(spender, amountNeeded);\n// Não: approve(spender, ethers.MaxUint256)',
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /approve\s*\([^,]+,\s*(?:ethers\.MaxUint256|2\s*\*\*\s*256|type\(uint256\)\.max|0xffffffff)/i,
    ],
    fileExtensions: ['.sol', '.js', '.ts'],
  },
  {
    id: 'WEB3_006',
    title: 'Owner único sem timelock ou multisig',
    category: 'Web3',
    severity: 'high',
    description: 'Contrato com único owner capaz de executar funções críticas sem timelock.',
    impact: 'Comprometimento da chave do owner ou insider attack pode drenar o protocolo instantaneamente.',
    remediation: 'Use Gnosis Safe (multisig) e timelock para funções administrativas críticas.',
    safeExample: '// Use Governor + Timelock do OpenZeppelin para funções críticas.\nimport "@openzeppelin/contracts/governance/TimelockController.sol";',
    reference: 'OWASP A04:2021 - Insecure Design',
    patterns: [
      /onlyOwner/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_007',
    title: 'Proxy upgrade sem proteção adequada',
    category: 'Web3',
    severity: 'critical',
    description: 'Padrão de proxy upgradeable sem proteção adequada na função de upgrade.',
    impact: 'Owner pode substituir a implementação por código malicioso a qualquer momento.',
    remediation: 'Use UUPS com acesso restrito + timelock. Considere proxies imutáveis quando possível.',
    safeExample: 'import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";\nfunction _authorizeUpgrade(address) internal override onlyOwner timelocked {}',
    reference: 'SWC-112',
    patterns: [
      /upgradeTo\s*\(/,
      /upgradeToAndCall\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_010',
    title: 'Aleatoriedade insegura (block.timestamp/blockhash)',
    category: 'Web3',
    severity: 'high',
    confidence: 'high',
    description: 'Geração de aleatoriedade baseada em variáveis de bloco como block.timestamp, block.difficulty, block.prevrandao ou blockhash.',
    impact: 'Mineradores e validadores podem prever ou manipular esses valores, permitindo que um atacante vença sorteios, loterias ou qualquer mecanismo que dependa dessa aleatoriedade.',
    attackScenarioDefensive: 'Em um contrato de loteria, o atacante calcula previamente o resultado usando block.timestamp dentro de uma transação e só executa a entrada quando garante a vitória, drenando o prêmio acumulado.',
    remediation: 'Use uma fonte de aleatoriedade verificável e off-chain, como Chainlink VRF. Nunca derive valores secretos ou sorteios de variáveis de bloco previsíveis.',
    safeExample: '// Use Chainlink VRF para aleatoriedade verificável:\nimport "@chainlink/contracts/src/v0.8/vrf/VRFConsumerBaseV2.sol";\n// Solicite randomWords ao coordenador VRF e use o callback fulfillRandomWords.',
    testSuggestion: 'Crie um contrato com uint winner = uint(keccak256(abi.encodePacked(block.timestamp))) % players; e confirme que a regra dispara.',
    reference: 'SWC-120',
    patterns: [
      /keccak256\s*\([^)]*(?:block\.(?:timestamp|number|difficulty|prevrandao)|blockhash)/,
      /(?:random|rand|winner|seed)\s*=\s*[^;]*(?:block\.(?:timestamp|difficulty|prevrandao)|blockhash)/i,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_011',
    title: 'Retorno de low-level call não verificado',
    category: 'Web3',
    severity: 'high',
    confidence: 'medium',
    description: 'Chamada de baixo nível (.call, .delegatecall ou .send) cujo valor de retorno de sucesso não é verificado.',
    impact: 'Falhas silenciosas: se a chamada externa reverter, o contrato continua a execução como se tivesse tido sucesso, podendo creditar saldos, emitir tokens ou marcar pagamentos como concluídos indevidamente.',
    attackScenarioDefensive: 'Um atacante força a falha de uma transferência via .send (gas insuficiente para o fallback do destinatário) enquanto o contrato registra o pagamento como bem-sucedido, ficando com fundos sem entregar o valor.',
    remediation: 'Sempre capture e verifique o retorno booleano de chamadas de baixo nível com require, ou prefira métodos de alto nível que revertem automaticamente.',
    safeExample: '(bool success, ) = recipient.call{value: amount}("");\nrequire(success, "Transferência falhou");',
    testSuggestion: 'Adicione uma linha addr.call{value: 1 ether}(""); sem atribuir o retorno e confirme que a regra dispara; depois verifique que (bool ok,) = addr.call... com require não gera ruído indevido em revisão manual.',
    reference: 'SWC-104',
    patterns: [
      /(?<![\w)])\.(?:call|delegatecall|send)\s*(?:\{[^}]*\})?\s*\([^;]*\)\s*;/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_012',
    title: 'Interação externa antes de update de estado (CEI/reentrancy)',
    category: 'Web3',
    severity: 'critical',
    confidence: 'low',
    description: 'Chamada externa que envia Ether (.call{value:...}) ocorrendo antes da atualização de saldos internos, violando o padrão checks-effects-interactions.',
    impact: 'Permite ataques de reentrancy: o destinatário pode reentrar na função antes que o saldo seja zerado, drenando todos os fundos do contrato (vetor usado no hack do DAO).',
    attackScenarioDefensive: 'Um contrato malicioso reentra em withdraw() pelo seu fallback enquanto balances[msg.sender] ainda não foi decrementado, repetindo o saque até esvaziar o contrato.',
    remediation: 'Aplique o padrão checks-effects-interactions: atualize todos os estados (saldos) ANTES de qualquer chamada externa, e use ReentrancyGuard (nonReentrant) do OpenZeppelin.',
    safeExample: 'uint256 amount = balances[msg.sender];\nbalances[msg.sender] = 0; // efeito antes da interação\n(bool ok, ) = msg.sender.call{value: amount}("");\nrequire(ok, "Falha");',
    testSuggestion: 'Escreva uma função que faça msg.sender.call{value: amount}(""); e só depois balances[msg.sender] -= amount; e confirme que a regra dispara.',
    reference: 'SWC-107',
    patterns: [
      /\.call\s*\{\s*value[\s\S]{0,200}?(?:balances|balanceOf|deposits|_balances)\s*\[[^\]]+\]\s*[-+]?=/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_013',
    title: 'Uso de selfdestruct (deprecado)',
    category: 'Web3',
    severity: 'high',
    confidence: 'high',
    description: 'Uso de selfdestruct (ou do antigo suicide), opcode deprecado a partir do EIP-6049 e com comportamento alterado pelo EIP-4758.',
    impact: 'Pode remover o código do contrato e enviar todo o saldo a um endereço arbitrário, quebrando integrações dependentes e, se acessível por atacante, destruindo o protocolo. O comportamento futuro do opcode é instável.',
    attackScenarioDefensive: 'Se a função que invoca selfdestruct não tiver controle de acesso robusto, um atacante a aciona e destrói o contrato, ou força o envio de saldo inesperado a um contrato vítima para burlar verificações de this.balance.',
    remediation: 'Evite selfdestruct. Para desativar contratos use um padrão de pausa (Pausable) ou flags de estado. Se for imprescindível, restrinja com controle de acesso forte e timelock.',
    safeExample: 'import "@openzeppelin/contracts/security/Pausable.sol";\n// Use _pause()/_unpause() em vez de destruir o contrato.',
    testSuggestion: 'Inclua selfdestruct(payable(owner)); em uma função e confirme que a regra dispara; teste também a variante legada suicide(owner);.',
    reference: 'SWC-106',
    patterns: [
      /\b(?:selfdestruct|suicide)\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_014',
    title: 'Bloco unchecked com aritmética sobre saldos',
    category: 'Web3',
    severity: 'medium',
    confidence: 'low',
    description: 'Bloco unchecked contendo operações aritméticas sobre saldos, montantes ou supply, desabilitando a proteção automática contra overflow/underflow do Solidity 0.8+.',
    impact: 'Overflow ou underflow não detectado pode inflar saldos ou totalSupply, permitindo cunhagem indevida de tokens ou saques maiores que o depósito.',
    attackScenarioDefensive: 'Um atacante explora um underflow dentro de um bloco unchecked (ex.: balances[user] -= amount com amount > saldo) para obter um saldo enorme por wrap-around e drenar o pool.',
    remediation: 'Use unchecked apenas quando provar matematicamente que overflow/underflow é impossível (ex.: contadores limitados). Para saldos e supply, mantenha a verificação padrão ou use SafeMath/limites explícitos.',
    safeExample: '// Mantenha a checagem padrão do compilador:\nbalances[msg.sender] -= amount; // reverte em underflow no Solidity >=0.8\n// Use unchecked só em loops comprovadamente seguros.',
    testSuggestion: 'Escreva unchecked { balances[to] += amount; } e confirme que a regra dispara, sinalizando aritmética de saldo sem proteção.',
    reference: 'SWC-101',
    patterns: [
      /unchecked\s*\{[^}]*(?:balance|balances|amount|supply|totalSupply)[^}]*[-+*]=/i,
    ],
    fileExtensions: ['.sol'],
  },
  {
    id: 'WEB3_015',
    title: 'delegatecall com destino derivado de parâmetro externo',
    category: 'Web3',
    severity: 'critical',
    confidence: 'medium',
    description: 'Função recebe um parâmetro do tipo address e executa delegatecall, indicando que o destino do delegatecall pode ser controlado por quem chama a função.',
    impact: 'Execução de código arbitrário no contexto (storage e saldo) do contrato chamador. Um atacante pode sobrescrever variáveis de estado críticas como owner e tomar controle total, drenando todos os fundos.',
    attackScenarioDefensive: 'O atacante chama a função passando o endereço de um contrato malicioso que, via delegatecall, reescreve o slot do owner para si mesmo e em seguida saca todo o saldo do contrato.',
    remediation: 'Nunca permita que o destino de delegatecall seja controlado externamente. Restrinja a uma whitelist imutável de implementações aprovadas e adicione controle de acesso à função.',
    safeExample: '// Restrinja a implementações aprovadas e imutáveis:\nrequire(approvedImplementations[impl], "Implementação não aprovada");\n(bool ok, ) = impl.delegatecall(data);\nrequire(ok, "Falha");',
    testSuggestion: 'Defina function exec(address target, bytes calldata data) { target.delegatecall(data); } e confirme que a regra dispara por causa do address parametrizado seguido de delegatecall.',
    reference: 'SWC-112',
    patterns: [
      /function\s+\w+\s*\([^)]*\baddress\s+\w+[^)]*\)[^{]*\{[\s\S]{0,400}?\.delegatecall\s*\(/,
    ],
    fileExtensions: ['.sol'],
  },
];
